In [6]:
import create_population
import create_population3
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction
from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_kaiki_cross import Trainer_lightgbm_rank_kaiki_cv
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross

import pandas as pd


import condition_prediction


from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki

from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
%autoreload

In [8]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [4]:
population = create_population.create(from_="2016-01-01", to_="2024-11-30")

In [9]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

agg_horse_n_races_relative:   0%|          | 0/4 [00:00<?, ?it/s]

###　12/21 第5回目レース

In [11]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050705",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp
running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

In [12]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050705,2022105014,1077,1150,1,1,23.8,6,55.0,1,2,NaN,NaN,16,2.0,2.0,2
1,202406050705,2022103169,1160,1167,2,1,47.6,9,56.0,0,2,NaN,NaN,16,2.0,2.0,2
2,202406050705,2022106888,1162,417,3,2,80.8,16,55.0,1,2,NaN,NaN,16,2.0,2.0,2
3,202406050705,2022102087,726,1059,4,2,29.3,8,55.0,1,2,NaN,NaN,16,2.0,2.0,2
4,202406050705,2022104767,1170,1097,5,3,3.0,1,55.0,1,2,NaN,NaN,16,2.0,2.0,2
5,202406050705,2022105454,1075,1132,6,3,9.5,4,55.0,1,2,NaN,NaN,16,2.0,2.0,2
6,202406050705,2022106794,1009,1089,7,4,61.8,11,56.0,0,2,NaN,NaN,16,2.0,2.0,2
7,202406050705,2022106962,1150,1189,8,4,48.0,10,55.0,1,2,NaN,NaN,16,2.0,2.0,2
8,202406050705,2022106228,5386,1038,9,5,4.8,3,56.0,0,2,NaN,NaN,16,2.0,2.0,2
9,202406050705,2022104773,5626,1201,10,5,3.3,2,56.0,0,2,NaN,NaN,16,2.0,2.0,2
10,202406050705,2022101789,1214,1029,11,6,79.1,15,52.0,1,2,NaN,NaN,16,2.0,2.0,2
11,202406050705,2022104350,1143,1031,12,6,14.6,5,56.0,0,2,NaN,NaN,16,2.0,2.0,2
12,202406050705,2022106116,1184,1116,13,7,67.0,12,54.0,1,2,NaN,NaN,16,2.0,2.0,2
13,202406050705,2022104441,1179,1182,14,7,25.3,7,55.0,1,2,NaN,NaN,16,2.0,2.0,2
14,202406050705,2022100332,1203,1116,15,8,69.6,14,53.0,0,2,NaN,NaN,16,2.0,2.0,2
15,202406050705,2022102022,1091,1051,16,8,67.0,13,56.0,0,2,NaN,NaN,16,2.0,2.0,2

In [13]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050705,1,0,1800,1,0,0,6,5,73875005,4,64,641,5,51,7,71,5,51,64071,2,6421,2,601,1,310,2,3,3.1,6411800,2,24,55,0.5

In [ ]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

In [14]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
14,202406050705,15,69.6,14,0.233405,0.205882,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.841680
11,202406050705,12,14.6,5,0.202326,0.162791,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.468077
10,202406050705,11,79.1,15,0.202326,0.201031,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.455368
2,202406050705,3,80.8,16,0.217262,0.258475,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.337429
12,202406050705,13,67.0,12,0.232143,0.245161,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.250060
7,202406050705,8,48.0,10,0.240409,0.229787,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.172080
6,202406050705,7,61.8,11,0.240409,0.245763,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.989051
15,202406050705,16,67.0,13,0.233405,NaN,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.975004
13,202406050705,14,25.3,7,0.232143,0.156250,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.912101
5,202406050705,6,9.5,4,0.245232,0.224576,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.860720
0,202406050705,1,23.8,6,0.216561,0.203390,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.694559
3,202406050705,4,29.3,8,0.217262,0.256410,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.630637
4,202406050705,5,3.0,1,0.245232,0.253165,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.542041
1,202406050705,2,47.6,9,0.216561,0.245763,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.538116
8,202406050705,9,4.8,3,0.212195,0.215517,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.417897
9,202406050705,10,3.3,2,0.212195,0.250000,NaN,NaN,NaN,NaN,2,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.356340

### 12/21 第n回目レース

In [ ]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408060411",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

In [ ]:
pfc.results

In [ ]:
pfc.race_info

In [ ]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)