In [1]:
import create_population
import create_population3
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction
from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_kaiki_cross import Trainer_lightgbm_rank_kaiki_cv
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross

import pandas as pd


import condition_prediction


from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki

from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

In [2]:
%autoreload

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [4]:
population = create_population.create(from_="2016-01-01", to_="2024-11-30")

In [5]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

agg_horse_n_races_relative:   0%|          | 0/4 [00:00<?, ?it/s]

###　12/21 第1回目レース

In [ ]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070701",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

In [ ]:
pfc.results

In [ ]:
pfc.race_info

In [ ]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

###　12/21 第2回目レース

In [6]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070702",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [7]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070702,2022100215,1202,1140,1,1,72.0,9,53.0,0,2,544.0,0.0,16,2.0,2.0,2
1,202408070702,2022102800,732,1138,2,1,16.4,5,56.0,0,2,464.0,6.0,16,2.0,2.0,2
2,202408070702,2022103701,1186,1121,3,2,237.1,14,55.0,1,2,450.0,-2.0,16,2.0,2.0,2
3,202408070702,2022107199,1174,1028,4,2,103.8,10,55.0,1,2,486.0,-2.0,16,2.0,2.0,2
4,202408070702,2022104600,1102,1117,5,3,2.3,1,56.0,0,2,508.0,0.0,16,2.0,2.0,2
5,202408070702,2022107288,1216,1166,6,3,157.4,13,53.0,1,2,444.0,-4.0,16,2.0,2.0,2
6,202408070702,2022106939,1215,1135,7,4,325.5,15,53.0,0,2,480.0,0.0,16,2.0,2.0,2
7,202408070702,2022103080,1163,1193,8,4,7.7,4,55.0,1,2,424.0,2.0,16,2.0,2.0,2
8,202408070702,2022103749,1114,1033,9,5,20.6,6,56.0,0,2,458.0,-4.0,16,2.0,2.0,2
9,202408070702,2022101117,1185,1046,10,5,41.8,8,55.0,0,2,474.0,8.0,16,2.0,2.0,2
10,202408070702,2022106121,1015,1033,11,6,416.1,16,55.0,1,2,460.0,2.0,16,2.0,2.0,2
11,202408070702,2022103165,1178,1206,12,6,110.7,11,55.0,1,2,458.0,6.0,16,2.0,2.0,2
12,202408070702,2022103195,1093,1121,13,7,31.0,7,55.0,1,2,474.0,-10.0,16,2.0,2.0,2
13,202408070702,2022100739,1213,1158,14,7,149.9,12,54.0,0,2,494.0,-2.0,16,2.0,2.0,2
14,202408070702,2022100696,5339,1185,15,8,4.0,2,55.0,1,2,494.0,4.0,16,2.0,2.0,2
15,202408070702,2022103485,5473,1193,16,8,4.5,3,55.0,1,2,434.0,16.0,16,2.0,2.0,2

In [8]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070702,0,0,1200,2,0,1,8,2,73875002,4,84,840,2,20,7,70,7,70,84070,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401200,-1,24,60,1.0

In [9]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
7,202408070702,8,7.7,4,0.182195,0.192913,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.441527,0.749656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.912303
10,202408070702,11,416.1,16,0.186508,0.184739,-1.421743,-1.452983,0.313743,-0.418860,4,2,NaN,NaN,-0.447398,-0.441527,-1.181660,NaN,-0.942741,-0.825743,NaN,NaN,-0.778817,-0.709427,NaN,NaN,120.030528,142.198370,105.865655,136.637237,-1.034381,0.213052,75.276414
11,202408070702,12,110.7,11,0.186508,0.232365,-0.395569,-0.212736,0.719851,-0.646405,2,2,NaN,NaN,-0.447398,-0.441527,0.749656,NaN,0.415337,0.095174,NaN,NaN,0.844198,0.715804,NaN,NaN,128.410209,140.405012,122.368175,137.252295,-0.516802,-0.105161,75.132643
2,202408070702,3,237.1,14,0.200441,0.208494,-0.975510,-1.735360,0.462120,-0.297257,2,2,NaN,NaN,-0.447398,-0.441527,0.749656,NaN,-0.629010,-0.710929,NaN,NaN,0.467371,0.359112,NaN,NaN,131.042497,137.636133,117.362196,136.637237,-0.354216,-0.596471,75.003456
12,202408070702,13,31.0,7,0.217899,0.158590,-0.336859,0.043411,0.259091,-0.719697,2,2,NaN,NaN,-0.447398,-0.441527,0.749656,NaN,-0.586387,-0.795734,NaN,NaN,0.482750,0.321586,NaN,NaN,136.836230,139.733666,136.836230,139.733666,0.003639,-0.224285,74.998298
4,202408070702,5,2.3,1,0.206383,0.193798,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.441527,0.749656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.916172
6,202408070702,7,325.5,15,0.182195,0.189189,0.138496,0.486810,0.335714,0.442451,3,2,NaN,NaN,-0.447398,-0.441527,-1.283309,NaN,-0.197724,0.018779,NaN,NaN,-1.122712,-1.148555,NaN,NaN,157.128734,149.359503,90.145725,137.104629,1.257025,1.483722,74.878820
13,202408070702,14,149.9,12,0.217899,0.188679,-0.871688,-0.455464,0.487500,-0.542708,3,2,NaN,NaN,-0.447398,-0.441527,-1.283309,NaN,-1.138448,-1.157313,NaN,NaN,-0.783275,-0.628145,NaN,NaN,104.168175,131.052295,104.168175,131.052295,-2.014135,-1.764706,74.828637
5,202408070702,6,157.4,13,0.206383,0.178295,-0.445688,-0.058102,0.242754,-0.352536,3,2,NaN,NaN,-0.447398,-0.441527,-1.283309,NaN,-1.553812,-1.469729,NaN,NaN,-0.633401,-0.489905,NaN,NaN,137.125999,131.106951,137.125999,131.106951,0.021537,-1.755008,74.640857
3,202408070702,4,103.8,10,0.200441,0.214008,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.441527,0.749656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.606208
9,202408070702,10,41.8,8,0.206827,0.244094,-0.296344,-0.286616,0.322108,-0.594883,2,2,NaN,NaN,-0.447398,-0.441527,0.749656,NaN,-0.033409,-0.057377,NaN,NaN,0.682278,0.648302,NaN,NaN,146.386788,146.617557,135.869563,141.433666,0.593539,0.997192,74.466781
0,202408070702,1,72.0,9,0.204225,0.210117,-0.632968,-0.845022,0.627271,-0.286492,4,2,NaN,NaN,-0.447398,-0.441527,-1.181660,NaN,0.409843,0.523007,NaN,NaN,-1.218059,-1.246554,NaN,NaN,121.276886,141.702578,112.962727,139.162879,-0.957399,0.125079,74.466615
1,202408070702,2,16.4,5,0.204225,0.209302,1.684798,1.483744,0.929474,-0.809896,2,2,NaN,NaN,0.049711,0.439325,0.749656,NaN,0.339320,0.316421,NaN,NaN,0.816769,0.813703,NaN,NaN,156.952243,144.057728,154.118910,143.557728,1.246124,0.542976,73.644511
15,202408070702,16,4.5,3,0.209393,0.204819,1.532106,1.439838,1.017058,-0.511480,1,2,NaN,NaN,0.298265,0.879751,0.749656,NaN,1.491498,1.357780,NaN,NaN,1.232503,1.274494,NaN,NaN,138.523448,137.541775,128.895527,136.637237,0.107852,-0.613214,73.500563
8,202408070702,9,20.6,6,0.206827,0.226562,1.187825,0.943852,0.959506,-0.343790,3,2,NaN,NaN,3.131784,3.363754,-1.283309,NaN,0.505892,0.724411,NaN,NaN,-1.376594,-1.460789,NaN,NaN,140.464201,145.197528,138.918910,144.557728,0.227724,0.745222,73.500277
14,202408070702,15,4.0,2,0.209393,0.184615,0.833144,0.648628,0.603704,-0.177034,2,2,NaN,NaN,0.546819,0.615495,0.749656,NaN,1.919641,1.981253,NaN,NaN,1.386988,1.550375,NaN,NaN,159.759112,146.360629,155.895401,141.962879,1.419493,0.951603,73.494535

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第3回目レース

In [10]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070703",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [11]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070703,2022102639,1141,1142,1,1,22.2,6,56.0,0,2,492.0,4.0,16,2.0,2.0,2
1,202408070703,2022105726,1171,1092,2,1,50.3,10,56.0,0,2,472.0,6.0,16,2.0,2.0,2
2,202408070703,2022106680,1213,1087,3,2,36.9,8,54.0,0,2,456.0,-2.0,16,2.0,2.0,2
3,202408070703,2022106566,1152,1206,4,2,13.1,4,56.0,0,2,484.0,6.0,16,2.0,2.0,2
4,202408070703,2022102282,1180,1149,5,3,29.5,7,56.0,0,2,496.0,2.0,16,2.0,2.0,2
5,202408070703,2022105436,732,1193,6,3,15.3,5,56.0,0,2,456.0,0.0,16,2.0,2.0,2
6,202408070703,2022106852,1181,1129,7,4,100.8,15,55.0,1,2,472.0,22.0,16,2.0,2.0,2
7,202408070703,2022103378,1157,1123,8,4,51.6,11,56.0,0,2,480.0,-10.0,16,2.0,2.0,2
8,202408070703,2022100154,1126,1099,9,5,1.7,1,56.0,0,2,492.0,-8.0,16,2.0,2.0,2
9,202408070703,2022104654,5473,1176,10,5,4.3,2,56.0,0,2,522.0,16.0,16,2.0,2.0,2
10,202408070703,2022103087,1185,1139,11,6,142.0,16,55.0,0,2,474.0,8.0,16,2.0,2.0,2
11,202408070703,2022106638,1034,1111,12,6,93.0,13,55.0,1,2,446.0,-2.0,16,2.0,2.0,2
12,202408070703,2022100124,1208,1110,13,7,41.6,9,55.0,0,2,532.0,4.0,16,2.0,2.0,2
13,202408070703,2022104461,1215,1107,14,7,99.7,14,53.0,0,2,494.0,16.0,16,2.0,2.0,2
14,202408070703,2022104636,5366,1105,15,8,11.7,3,56.0,0,2,472.0,2.0,16,2.0,2.0,2
15,202408070703,2022102756,1216,1002,16,8,70.4,12,54.0,0,2,462.0,6.0,16,2.0,2.0,2

In [12]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070703,0,0,1800,2,0,1,8,3,73875003,4,84,840,3,30,7,70,7,70,84070,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401800,-1,24,60,1.0

In [13]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
6,202408070703,7,100.8,15,0.238482,0.252273,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.970880
11,202408070703,12,93.0,13,0.215517,0.175439,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.468375
13,202408070703,14,99.7,14,0.216825,0.166008,-1.173974,-0.953989,0.430452,-0.493285,4,1,NaN,-0.408248,-0.569116,-0.442874,-1.026691,NaN,-0.672527,-0.643906,NaN,NaN,-0.386473,-0.339234,NaN,NaN,109.349212,136.239990,92.095527,133.646314,-2.423928,-0.916439,118.264759
5,202408070703,6,15.3,5,0.216954,0.239278,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.091540
9,202408070703,10,4.3,2,0.220102,0.180693,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.926324
10,202408070703,11,142.0,16,0.215517,0.192412,-0.014579,0.299963,0.740465,-0.192239,3,1,NaN,NaN,-0.569116,-0.442874,-1.125649,NaN,-1.034404,-0.972470,NaN,NaN,-0.337918,-0.278395,NaN,NaN,128.045605,138.357313,127.112272,137.957313,-0.558778,-0.388327,117.713337
1,202408070703,2,50.3,10,0.238487,0.262443,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.676341
15,202408070703,16,70.4,12,0.212471,0.164634,0.661452,1.054648,0.806250,-0.028265,3,1,NaN,-0.408248,-0.569116,-0.442874,-1.125649,NaN,-0.548854,-0.571877,NaN,NaN,-0.517601,-0.447404,NaN,NaN,137.602863,134.136793,137.602863,134.136793,0.394654,-1.441028,117.625593
4,202408070703,5,29.5,7,0.216954,0.240363,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.442874,0.853514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.607510
7,202408070703,8,51.6,11,0.238482,0.243182,-1.626979,-1.372301,NaN,NaN,3,1,NaN,NaN,-0.569116,-0.442874,-1.125649,NaN,-1.059525,-1.214981,NaN,NaN,-0.328622,-0.176079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.512324
12,202408070703,13,41.6,9,0.216825,0.197324,-0.964735,-1.111628,0.578395,-0.332809,2,1,NaN,-0.408248,-0.137967,0.056139,0.853514,NaN,-0.221213,-0.238067,NaN,NaN,1.068713,1.059520,NaN,NaN,139.335639,137.704192,134.112272,137.651071,0.567515,-0.551231,116.750494
2,202408070703,3,36.9,8,0.232170,0.197309,0.211665,0.577636,1.034615,0.373695,2,1,NaN,-0.408248,-0.569116,-0.442874,0.853514,NaN,0.047350,-0.163592,NaN,NaN,1.168097,1.090941,NaN,NaN,142.897641,147.077128,142.897641,147.077128,0.922861,1.786609,116.631953
0,202408070703,1,22.2,6,0.238487,0.243243,0.941762,0.894518,0.836726,-0.072667,3,1,NaN,NaN,-0.569116,-0.442874,-1.125649,NaN,-0.328958,-0.164135,NaN,NaN,-0.598975,-0.619430,NaN,NaN,137.345605,143.657313,137.345605,143.657313,0.368990,0.933623,115.666580
3,202408070703,4,13.1,4,0.232170,0.269841,-0.252702,-1.089957,0.587059,0.070487,4,1,NaN,2.041241,2.535153,3.150022,-1.026691,NaN,1.258035,1.497198,NaN,NaN,-1.029454,-1.152230,NaN,NaN,133.273822,140.884404,128.092340,139.851071,-0.037211,0.241992,115.506597
14,202408070703,15,11.7,3,0.212471,0.207373,0.834507,0.850554,1.094688,-0.221771,3,1,NaN,-0.408248,0.293181,0.555152,-1.125649,NaN,0.560747,0.772499,NaN,NaN,-0.928219,-1.014595,NaN,NaN,139.101924,142.488565,105.248221,133.006951,0.544200,0.642109,115.339465
8,202408070703,9,1.7,1,0.220102,0.240566,1.383582,0.850554,2.214013,-0.350000,2,1,NaN,NaN,0.724329,1.553179,0.853514,NaN,1.999350,1.699332,NaN,NaN,1.890453,1.876906,NaN,NaN,135.869135,138.682132,129.059332,133.706951,0.221697,-0.307309,114.708164

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第7回目レース

In [14]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070707",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [15]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070707,2019101620,1185,1128,1,1,91.4,14,55.0,1,5,NaN,NaN,15,3.6,4.0,3
1,202408070707,2021105394,1034,1105,2,2,3.6,1,55.0,1,3,NaN,NaN,15,3.6,4.0,3
2,202408070707,2020101077,1216,1084,3,2,63.6,13,54.0,1,4,NaN,NaN,15,3.6,4.0,3
3,202408070707,2020103991,1208,1065,4,3,39.9,11,55.0,1,4,NaN,NaN,15,3.6,4.0,3
4,202408070707,2021101289,1152,1135,5,3,141.4,15,55.0,1,3,NaN,NaN,15,3.6,4.0,3
5,202408070707,2021106177,1174,1198,6,4,9.5,5,55.0,1,3,NaN,NaN,15,3.6,4.0,3
6,202408070707,2021104413,660,1044,7,4,6.3,3,55.0,1,3,NaN,NaN,15,3.6,4.0,3
7,202408070707,2020106035,1144,1066,8,5,9.5,6,56.0,1,4,NaN,NaN,15,3.6,4.0,3
8,202408070707,2021105052,1178,1017,9,5,13.7,7,55.0,1,3,NaN,NaN,15,3.6,4.0,3
9,202408070707,2021101426,1157,1185,10,6,6.1,2,55.0,1,3,NaN,NaN,15,3.6,4.0,3
10,202408070707,2020103365,1213,1192,11,6,46.2,12,54.0,1,4,NaN,NaN,15,3.6,4.0,3
11,202408070707,2020102919,1102,1149,12,7,6.6,4,56.0,1,4,NaN,NaN,15,3.6,4.0,3
12,202408070707,2020103556,5212,1211,13,7,22.4,10,56.0,1,4,NaN,NaN,15,3.6,4.0,3
13,202408070707,2021104780,1190,1075,14,8,21.3,9,52.0,1,3,NaN,NaN,15,3.6,4.0,3
14,202408070707,2020103209,1171,1148,15,8,18.8,8,56.0,1,4,NaN,NaN,15,3.6,4.0,3

In [16]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070707,0,0,1800,2,0,2,8,7,73875007,4,84,840,7,70,7,70,7,70,84070,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401800,-1,34,70,2.0

In [17]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
8,202408070707,9,13.7,7,0.220102,0.240566,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.495247,0.788420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.705863
14,202408070707,15,18.8,8,0.212471,0.207373,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.495247,0.788420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.687410
4,202408070707,5,141.4,15,0.216954,0.240363,-1.341112,-0.233748,0.790413,-0.127162,4,1,NaN,-0.781916,-0.571983,-0.495247,-1.148647,NaN,-1.478970,-1.255935,NaN,NaN,-0.834506,-0.790130,NaN,NaN,146.257613,151.022306,142.649532,147.790367,-0.084064,0.162531,116.551633
10,202408070707,11,46.2,12,0.215517,0.192412,NaN,NaN,NaN,0.861341,3,1,NaN,-0.781916,-0.571983,-0.495247,-1.250597,NaN,-0.248668,-0.037630,NaN,NaN,-1.190138,-1.191985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.298169
7,202408070707,8,9.5,6,0.220102,0.243182,-0.243015,0.036619,1.338897,0.163763,1,1,NaN,-0.781916,1.669961,0.621851,0.788420,NaN,0.511373,0.335635,NaN,NaN,0.852873,0.835262,NaN,NaN,148.089782,149.390250,138.899619,148.880571,0.171071,-0.246618,115.382478
13,202408070707,14,21.3,9,0.212471,0.166008,-0.140283,0.286117,NaN,0.288725,2,1,NaN,-0.781916,-0.571983,-0.495247,0.788420,NaN,0.803794,-0.259563,NaN,NaN,0.918427,0.673079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.331587
9,202408070707,10,6.1,2,0.215517,0.180693,-1.955198,-3.070585,1.026226,0.050231,2,1,NaN,0.670213,0.548989,0.435668,0.788420,NaN,-0.486257,-0.637347,NaN,NaN,0.629227,0.570138,NaN,NaN,144.554671,146.478779,124.776390,137.357313,-0.321203,-0.976509,115.259258
11,202408070707,12,6.6,4,0.216825,0.175439,-0.680042,0.193274,0.264515,0.189313,2,1,NaN,-0.781916,-0.571983,-0.495247,0.788420,NaN,-0.752463,-0.896976,NaN,NaN,0.569550,0.499393,NaN,NaN,142.344063,147.880571,142.344063,147.880571,-0.629035,-0.625087,115.189312
2,202408070707,3,63.6,13,0.232170,0.197309,-0.306740,0.118984,NaN,NaN,3,1,NaN,-0.781916,-0.571983,-0.495247,-1.250597,NaN,-0.509591,-0.292106,NaN,NaN,-1.131645,-1.122644,NaN,NaN,NaN,NaN,125.325663,145.709607,NaN,NaN,115.097787
12,202408070707,13,22.4,10,0.216825,0.197324,0.243713,0.290118,1.006496,-0.043651,4,1,NaN,0.089362,-0.571983,-0.495247,-1.148647,NaN,-0.699881,-0.496094,NaN,NaN,-0.991694,-0.976471,NaN,NaN,147.220104,154.777622,139.576390,154.776987,0.049966,1.103969,114.869768
6,202408070707,7,6.3,3,0.238482,0.252273,0.912680,0.314803,NaN,NaN,2,1,NaN,1.396278,-0.571983,-0.122881,0.788420,NaN,1.494610,1.294580,NaN,NaN,1.073292,1.096561,NaN,NaN,NaN,NaN,147.056716,140.851071,NaN,NaN,114.630155
3,202408070707,4,39.9,11,0.216954,0.269841,0.391556,0.439826,1.124627,-0.048913,4,1,NaN,0.089362,-0.571983,-0.495247,-1.148647,NaN,-0.605932,-0.404466,NaN,NaN,-1.010650,-0.998942,NaN,NaN,141.215279,151.526987,140.920835,151.376987,-0.786221,0.289052,114.592773
0,202408070707,1,91.4,14,0.238487,0.243243,0.880091,0.637148,0.898337,-0.207440,4,1,NaN,-0.781916,-0.571983,-0.495247,-1.148647,NaN,-0.773873,-0.568259,NaN,NaN,-0.976766,-0.958774,NaN,NaN,138.723249,150.293297,128.914552,144.109607,-1.133243,-0.020228,114.437623
5,202408070707,6,9.5,5,0.238482,0.239278,0.662023,0.257122,2.026297,0.115000,2,1,NaN,1.831916,0.548989,0.808034,0.788420,NaN,0.972113,0.784991,NaN,NaN,0.956160,0.957705,NaN,NaN,149.811668,144.555722,137.992340,133.751071,0.410848,-1.458610,114.417885
1,202408070707,2,3.6,1,0.232170,0.262443,1.576327,0.730322,2.411011,0.362105,2,1,NaN,1.396278,2.379910,3.209795,0.788420,NaN,1.773744,2.433170,NaN,NaN,1.135868,1.406810,NaN,NaN,163.535181,157.440340,144.354168,145.080571,2.321882,1.771500,113.909966

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第8回目レース

In [18]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070708",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [19]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070708,2020102910,1125,1091,1,1,92.2,14,58.0,2,4,NaN,NaN,16,3.5,3.0,3
1,202408070708,2020106995,1195,1184,2,1,13.6,7,55.0,0,4,NaN,NaN,16,3.5,3.0,3
2,202408070708,2021102244,1088,1159,3,2,5.6,3,57.0,0,3,NaN,NaN,16,3.5,3.0,3
3,202408070708,2021110123,1216,1002,4,2,27.8,10,55.0,0,3,NaN,NaN,16,3.5,3.0,3
4,202408070708,2021105537,1163,1075,5,3,3.8,1,57.0,0,3,NaN,NaN,16,3.5,3.0,3
5,202408070708,2021110135,1152,1085,6,3,97.6,15,57.0,0,3,NaN,NaN,16,3.5,3.0,3
6,202408070708,2020100800,1180,1101,7,4,56.1,13,58.0,0,4,NaN,NaN,16,3.5,3.0,3
7,202408070708,2019100249,1185,1128,8,4,53.9,12,55.0,1,5,NaN,NaN,16,3.5,3.0,3
8,202408070708,2021102982,1034,1105,9,5,12.7,5,55.0,1,3,NaN,NaN,16,3.5,3.0,3
9,202408070708,2020104768,1176,1078,10,5,116.1,16,58.0,0,4,NaN,NaN,16,3.5,3.0,3
10,202408070708,2021105677,5473,1146,11,6,13.5,6,57.0,0,3,NaN,NaN,16,3.5,3.0,3
11,202408070708,2021102754,5339,1146,12,6,13.8,8,55.0,1,3,NaN,NaN,16,3.5,3.0,3
12,202408070708,2021105447,1126,1144,13,7,16.5,9,57.0,0,3,NaN,NaN,16,3.5,3.0,3
13,202408070708,2021110072,1157,1092,14,7,7.1,4,55.0,1,3,NaN,NaN,16,3.5,3.0,3
14,202408070708,2019102672,1178,1046,15,8,39.8,11,58.0,0,5,NaN,NaN,16,3.5,3.0,3
15,202408070708,2021101650,1174,1098,16,8,5.2,2,57.0,0,3,NaN,NaN,16,3.5,3.0,3

In [20]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070708,0,0,1400,2,0,2,8,8,73875008,4,84,840,8,80,7,70,7,70,84070,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401400,-1,34,70,2.0

In [21]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
13,202408070708,14,7.1,4,0.198895,0.207373,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.727920,0.558772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.378821
14,202408070708,15,39.8,11,0.196330,0.172589,NaN,NaN,NaN,0.584955,2,2,NaN,-0.681797,-0.615591,2.327495,0.558772,NaN,-0.902544,-0.996301,NaN,NaN,0.188201,0.126648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.520773
4,202408070708,5,3.8,1,0.186475,0.168498,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.727920,0.558772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.513599
5,202408070708,6,97.6,15,0.186475,0.230769,-2.546525,-3.007829,1.018049,-0.417419,2,2,NaN,NaN,-0.615591,-0.399381,0.558772,NaN,-1.085377,-1.205138,NaN,NaN,0.128121,0.052315,NaN,NaN,157.175006,154.070798,132.662727,142.862879,0.183665,0.139300,87.490096
0,202408070708,1,92.2,14,0.220957,0.215328,-0.090760,0.238877,1.118725,-0.342798,3,2,NaN,-0.681797,-0.615591,-0.727920,-1.733626,NaN,-0.794647,-0.974735,NaN,NaN,-1.504380,-1.397272,NaN,NaN,146.360168,152.132319,129.185577,143.348665,-1.632508,-0.406341,87.047830
12,202408070708,13,16.5,9,0.198895,0.192308,-0.309832,-0.415578,0.777271,0.402186,2,2,NaN,1.686550,-0.615591,-0.727920,0.558772,NaN,0.440161,0.537374,NaN,NaN,0.629421,0.672539,NaN,NaN,160.878397,153.312361,150.292390,151.280571,0.805589,-0.074184,87.044294
6,202408070708,7,56.1,13,0.190196,0.208029,-0.400466,-0.211371,0.737515,-0.110516,4,2,NaN,NaN,-0.615591,-0.727920,-1.619006,NaN,-0.626688,-0.453089,NaN,NaN,-1.456401,-1.481998,NaN,NaN,149.513818,157.428257,145.092390,157.278257,-1.102905,1.084356,86.753009
9,202408070708,10,116.1,16,0.209524,0.223048,-0.638198,-0.238370,0.659324,-0.177423,3,2,NaN,NaN,-0.615591,-0.727920,-1.733626,NaN,-1.218836,-1.117450,NaN,NaN,-1.364989,-1.346475,NaN,NaN,151.723639,156.475440,144.994006,142.166493,-0.731802,0.816158,86.708743
7,202408070708,8,53.9,12,0.190196,0.172794,-0.438161,0.210273,2.000000,-0.022466,2,2,NaN,-0.681797,-0.615591,-0.727920,0.558772,NaN,-0.037981,0.640658,NaN,NaN,0.472301,0.709302,NaN,NaN,152.198612,153.176987,152.198612,153.176987,-0.652038,-0.112289,86.547228
11,202408070708,12,13.8,8,0.212687,0.204000,0.126017,0.052322,0.993791,0.143135,2,2,NaN,-0.681797,0.254942,0.586237,0.558772,NaN,1.519987,0.672188,NaN,NaN,0.984257,0.720525,NaN,NaN,155.204049,145.255677,140.797641,140.862879,-0.147324,-2.341974,86.328957
10,202408070708,11,13.5,6,0.212687,0.192453,0.131362,0.387949,1.042488,-0.086802,2,2,NaN,1.686550,0.037309,0.093428,0.558772,NaN,-0.376264,-0.395170,NaN,NaN,0.361139,0.340612,NaN,NaN,161.820794,155.643311,146.380672,143.575371,0.963849,0.581931,86.275377
3,202408070708,4,27.8,10,0.214894,0.244526,0.426205,0.582263,1.104746,-0.200729,4,2,NaN,-0.681797,-0.615591,-0.727920,-1.619006,NaN,-0.403812,-0.198513,NaN,NaN,-1.522315,-1.563550,NaN,NaN,149.266483,156.332863,143.996125,153.209607,-1.144441,0.776025,86.162588
8,202408070708,9,12.7,5,0.209524,0.186131,0.236353,0.037911,1.452875,0.097500,2,2,NaN,-0.681797,2.170115,1.374732,0.558772,NaN,0.868274,0.396302,NaN,NaN,0.770101,0.622326,NaN,NaN,155.902158,149.377693,145.670118,139.651071,-0.030088,-1.181711,86.089926
1,202408070708,2,13.6,7,0.220957,0.249084,0.730860,0.590390,1.630680,0.391186,2,2,NaN,-0.681797,1.734848,1.489720,0.558772,NaN,0.407734,0.500335,NaN,NaN,0.618765,0.659356,NaN,NaN,162.965592,157.660006,152.203441,154.809607,1.156099,1.149588,85.935601
15,202408070708,16,5.2,2,0.196330,0.182927,1.360582,1.172202,1.598131,0.506140,2,2,NaN,0.502377,-0.615591,-0.399381,0.558772,NaN,0.026747,0.065162,NaN,NaN,0.493571,0.504461,NaN,NaN,164.699619,150.680571,147.362727,141.562879,1.447300,-0.814978,85.672996
2,202408070708,3,5.6,3,0.214894,0.186813,1.412562,0.600962,2.636921,0.530051,2,2,NaN,0.897101,1.343108,0.750507,0.558772,NaN,2.183246,2.528375,NaN,NaN,1.202208,1.381210,NaN,NaN,161.348920,154.940554,142.692390,147.178257,0.884605,0.384119,85.546949

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

In [ ]:
202408070701

### 12/21 第10回目レース

In [22]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070710",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [23]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070710,2021100838,1126,1194,1,1,2.2,1,56.0,0,3,NaN,NaN,16,4.1875,4.0,4
1,202408070710,2019106475,5366,1065,2,1,21.3,8,56.0,0,5,NaN,NaN,16,4.1875,4.0,4
2,202408070710,2020101861,1174,1058,3,2,16.7,6,56.0,0,4,NaN,NaN,16,4.1875,4.0,4
3,202408070710,2019106868,1152,1085,4,2,170.4,16,52.0,1,5,NaN,NaN,16,4.1875,4.0,4
4,202408070710,2021103140,5558,437,5,3,17.5,7,55.0,0,3,NaN,NaN,16,4.1875,4.0,4
5,202408070710,2020101941,1157,1128,6,3,58.2,14,56.0,0,4,NaN,NaN,16,4.1875,4.0,4
6,202408070710,2018103828,1144,1042,7,4,90.2,15,55.0,0,6,NaN,NaN,16,4.1875,4.0,4
7,202408070710,2020102343,1213,1166,8,4,38.3,12,56.0,0,4,NaN,NaN,16,4.1875,4.0,4
8,202408070710,2019102983,1093,1069,9,5,21.6,9,56.0,0,5,NaN,NaN,16,4.1875,4.0,4
9,202408070710,2020110104,1102,427,10,5,57.0,13,55.0,0,4,NaN,NaN,16,4.1875,4.0,4
10,202408070710,2019105095,5473,1028,11,6,15.4,5,56.0,0,5,NaN,NaN,16,4.1875,4.0,4
11,202408070710,2020102703,1095,1067,12,6,14.7,4,53.0,1,4,NaN,NaN,16,4.1875,4.0,4
12,202408070710,2020100960,1208,1028,13,7,31.8,11,55.0,0,4,NaN,NaN,16,4.1875,4.0,4
13,202408070710,2020106936,1171,1173,14,7,26.5,10,56.0,2,4,NaN,NaN,16,4.1875,4.0,4
14,202408070710,2021105630,1163,1075,15,8,3.9,2,56.0,0,3,NaN,NaN,16,4.1875,4.0,4
15,202408070710,2020101579,732,1058,16,8,13.9,3,56.0,0,4,NaN,NaN,16,4.1875,4.0,4

In [24]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070710,0,0,1800,2,0,4,8,10,73875010,4,84,840,10,100,7,70,7,70,84070,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401800,-1,44,85,3.5

In [25]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
9,202408070710,10,57.0,13,0.220102,0.180693,-1.813662,-2.753290,1.790290,0.565714,2,1,NaN,-1.092124,-0.383483,-0.099306,1.097334,NaN,-0.357265,-1.042034,NaN,NaN,0.962192,0.901021,NaN,NaN,179.481256,170.052618,151.224088,149.909607,0.328376,0.617655,114.461933
3,202408070710,4,170.4,16,0.232170,0.269841,-0.479432,-0.237688,NaN,NaN,2,1,NaN,-0.444940,-0.971716,-0.945919,1.097334,NaN,-0.146375,-0.088594,NaN,NaN,0.990326,1.041594,NaN,NaN,NaN,NaN,163.411619,156.503683,NaN,NaN,114.169180
5,202408070710,6,58.2,14,0.216954,0.239278,-1.163200,-0.425213,0.711364,0.959811,3,1,NaN,0.202245,-0.383483,-0.612405,-0.875401,NaN,-0.221360,-0.224991,NaN,NaN,-0.900638,-0.853781,NaN,NaN,184.957671,169.857238,170.452381,164.910769,0.804039,0.585124,113.482111
1,202408070710,2,21.3,8,0.238487,0.262443,0.384969,0.231255,2.733518,0.646875,2,1,NaN,-1.092124,-0.971716,-0.612405,1.097334,NaN,0.229125,0.021853,NaN,NaN,1.040422,1.057878,NaN,NaN,188.762049,171.500000,170.585714,165.210769,1.134475,0.858649,113.419326
8,202408070710,9,21.6,9,0.220102,0.240566,0.421548,0.670158,2.178522,-0.209320,4,1,NaN,-0.444940,-0.971716,-0.945919,-0.776764,NaN,-1.494700,-1.306312,NaN,NaN,-0.643462,-0.612963,NaN,NaN,164.053670,168.200000,155.474603,167.100000,-1.011612,0.309188,113.416765
6,202408070710,7,90.2,15,0.238482,0.252273,0.131547,0.253390,NaN,NaN,3,1,NaN,-0.444940,-0.971716,-0.945919,-0.875401,NaN,0.229420,1.189452,NaN,NaN,-0.960777,-1.062324,NaN,NaN,NaN,NaN,184.958268,177.786656,NaN,NaN,113.396013
4,202408070710,5,17.5,7,0.216954,0.240363,-1.163122,-0.389871,3.361714,0.533452,3,1,NaN,0.202245,0.506408,-0.107858,-0.875401,NaN,-0.053766,0.737209,NaN,NaN,-0.922997,-0.995646,NaN,NaN,154.911370,166.136176,152.578625,156.445192,-1.805682,-0.034445,113.236154
10,202408070710,11,15.4,5,0.215517,0.192412,1.433940,1.372404,2.796370,0.762167,2,1,NaN,-1.092124,0.204750,-0.278891,1.097334,NaN,2.223073,2.257804,NaN,NaN,1.306433,1.387541,NaN,NaN,168.378286,158.803683,168.378286,158.803683,-0.635991,-1.255329,113.107980
7,202408070710,8,38.3,12,0.238482,0.243182,-0.065548,-0.207649,3.058739,1.045313,2,1,NaN,-0.444940,0.506408,1.913751,1.097334,NaN,1.084380,1.502468,NaN,NaN,1.154521,1.276176,NaN,NaN,184.215523,175.354025,150.977396,151.180571,0.739579,1.500357,113.077834
2,202408070710,3,16.7,6,0.232170,0.197309,0.530704,0.845720,1.823504,0.685732,3,1,NaN,-0.444940,-0.292985,-0.561095,-0.875401,NaN,-0.674803,-0.342030,NaN,NaN,-0.840145,-0.836525,NaN,NaN,181.103236,169.366667,176.660500,167.100000,0.469256,0.503442,112.721372
11,202408070710,12,14.7,4,0.215517,0.175439,-0.840961,-0.623583,0.276548,-0.416961,4,1,NaN,0.525838,0.385745,0.593377,-0.776764,NaN,-0.544925,-0.227663,NaN,NaN,-0.757500,-0.756093,NaN,NaN,163.633433,163.500000,155.233433,161.900000,-1.048113,-0.473377,112.662398
13,202408070710,14,26.5,10,0.216825,0.166008,0.070336,0.228961,1.679527,1.094444,3,1,NaN,0.849430,0.506408,1.400652,-0.875401,NaN,-0.898402,-0.506854,NaN,NaN,-0.810314,-0.812224,NaN,NaN,193.207811,171.188763,182.741144,171.188763,1.520619,0.806827,112.383542
0,202408070710,1,2.2,1,0.238487,0.243243,2.214808,1.723527,2.878038,0.373994,2,1,NaN,2.143800,2.050898,1.599051,1.097334,NaN,1.481654,-0.206341,NaN,NaN,1.207521,1.024234,NaN,NaN,160.749560,153.340335,160.422730,152.276987,-1.298596,-2.164994,112.098027
15,202408070710,16,13.9,3,0.212471,0.164634,0.332226,-0.604077,2.245410,0.561522,3,1,NaN,1.334819,-0.971716,-0.945919,-0.875401,NaN,-1.342162,-1.099942,NaN,NaN,-0.751113,-0.724781,NaN,NaN,182.024194,168.766667,172.519048,166.500000,0.549247,0.403540,111.999654
14,202408070710,15,3.9,2,0.212471,0.207373,0.428141,-0.185513,3.774835,1.756917,3,1,NaN,1.334819,2.141395,1.161206,-0.875401,NaN,0.820798,0.352376,NaN,NaN,-1.039672,-0.938907,NaN,NaN,174.981493,159.184667,149.041184,145.392699,-0.062458,-1.191894,111.622747
12,202408070710,13,31.8,11,0.216825,0.197324,-0.422293,0.101471,1.953370,0.966630,2,1,NaN,-1.092124,-0.383483,-0.612405,1.097334,NaN,-0.334693,-1.016400,NaN,NaN,0.965203,0.904800,NaN,NaN,179.348667,163.551841,163.489397,154.803683,0.316860,-0.464745,111.256371

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)