In [1]:
import create_population
import create_population3
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction
from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_kaiki_cross import Trainer_lightgbm_rank_kaiki_cv
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross

import pandas as pd


import condition_prediction


from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki

from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

In [2]:
%autoreload

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [4]:
population = create_population.create(from_="2016-01-01", to_="2024-11-30")

In [5]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

agg_horse_n_races_relative:   0%|          | 0/4 [00:00<?, ?it/s]

###　12/21 第1回目レース

In [ ]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050701",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

In [ ]:
pfc.results

In [ ]:
pfc.race_info

In [ ]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

###　12/21 第2回目レース

In [6]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050702",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [7]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050702,2022105255,1207,1008,1,1,156.4,15,52.0,1,2,520.0,-2.0,16,2.0,2.0,2
1,202406050702,2022103895,1209,1201,2,1,31.6,9,52.0,1,2,440.0,0.0,16,2.0,2.0,2
2,202406050702,2022102994,1179,399,3,2,7.9,4,55.0,1,2,470.0,-8.0,16,2.0,2.0,2
3,202406050702,2022105221,1160,1177,4,2,214.9,16,55.0,1,2,474.0,2.0,16,2.0,2.0,2
4,202406050702,2022105239,1214,1199,5,3,87.9,12,52.0,1,2,418.0,2.0,16,2.0,2.0,2
5,202406050702,2022105685,1140,1115,6,3,9.6,6,55.0,1,2,492.0,-6.0,16,2.0,2.0,2
6,202406050702,2022103753,1170,1023,7,4,3.1,1,55.0,1,2,480.0,-4.0,16,2.0,2.0,2
7,202406050702,2022104378,5386,1074,8,4,9.0,5,55.0,1,2,456.0,0.0,16,2.0,2.0,2
8,202406050702,2022106024,1203,1035,9,5,97.4,13,52.0,1,2,440.0,0.0,16,2.0,2.0,2
9,202406050702,2022104699,5625,1064,10,5,24.9,8,55.0,1,2,446.0,0.0,16,2.0,2.0,2
10,202406050702,2022101090,1143,1031,11,6,70.1,11,55.0,1,2,498.0,-2.0,16,2.0,2.0,2
11,202406050702,2022106771,1158,1089,12,6,146.9,14,55.0,1,2,438.0,2.0,16,2.0,2.0,2
12,202406050702,2022105787,1150,1086,13,7,23.3,7,55.0,1,2,468.0,-10.0,16,2.0,2.0,2
13,202406050702,2022107156,1162,1047,14,7,4.1,2,55.0,1,2,470.0,0.0,16,2.0,2.0,2
14,202406050702,2022103537,1091,1131,15,8,34.6,10,55.0,1,2,454.0,-12.0,16,2.0,2.0,2
15,202406050702,2022105859,5626,1153,16,8,6.6,3,55.0,1,2,430.0,6.0,16,2.0,2.0,2

In [8]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050702,0,0,1800,1,0,1,6,2,73875002,4,64,640,2,20,7,70,5,50,64070,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401800,-1,24,60,1.0

In [9]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
11,202406050702,12,146.9,14,0.207064,0.222059,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.077092
0,202406050702,1,156.4,15,0.182594,0.180707,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.060942
10,202406050702,11,70.1,11,0.207064,0.221751,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.059448
4,202406050702,5,87.9,12,0.178354,0.195387,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.926389
3,202406050702,4,214.9,16,0.196187,0.211460,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.909110
1,202406050702,2,31.6,9,0.182594,0.200272,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.880527
12,202406050702,13,23.3,7,0.242279,0.228707,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.579710
2,202406050702,3,7.9,4,0.196187,0.203274,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.614366,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.034753
8,202406050702,9,97.4,13,0.219168,0.193460,-1.430730,-1.073960,0.754071,-0.288964,3,2,NaN,NaN,-1.099026,-0.614366,-1.478100,NaN,-1.302140,-1.086765,NaN,NaN,-0.479147,-0.540136,NaN,NaN,125.705193,136.339939,111.102819,136.245687,-1.005947,-1.718309,119.717033
14,202406050702,15,34.6,10,0.211853,0.197343,-1.084828,-0.396411,NaN,NaN,4,2,NaN,NaN,-1.099026,-0.614366,-1.371571,NaN,-1.287563,-1.464951,NaN,NaN,-0.421001,-0.368348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.874913
5,202406050702,6,9.6,6,0.178354,0.171662,0.292428,0.095932,1.035083,-0.093813,2,2,NaN,NaN,-0.759559,-0.229824,0.652495,NaN,-0.213123,-0.179701,NaN,NaN,0.900310,0.857461,NaN,NaN,142.010179,141.505129,133.254624,140.305129,0.647144,0.790421,118.113344
9,202406050702,10,24.9,8,0.219168,0.229282,0.350400,0.188848,0.979826,0.029167,3,2,NaN,NaN,-0.335224,0.250853,-1.478100,NaN,-0.216949,-0.207908,NaN,NaN,-0.798615,-0.822987,NaN,NaN,137.652020,140.258081,120.093862,137.811033,0.205290,0.184731,118.063855
15,202406050702,16,6.6,3,0.211853,0.193622,-0.077593,0.410782,1.204545,0.066667,4,2,NaN,NaN,0.734098,1.462160,-1.371571,NaN,0.143790,0.287480,NaN,NaN,-0.800238,-0.875950,NaN,NaN,119.951084,140.335029,119.951084,140.335029,-1.589330,0.222104,117.707667
6,202406050702,7,3.1,1,0.184862,0.174863,-0.149295,-1.262468,1.113684,-0.165720,2,2,NaN,NaN,0.785019,1.519841,0.652495,NaN,1.673243,1.586183,NaN,NaN,1.455635,1.425792,NaN,NaN,133.586283,138.044819,107.517942,133.384508,-0.206917,-0.890250,117.634133
7,202406050702,8,9.0,5,0.184862,0.223881,0.232692,0.068168,0.949796,0.132738,2,2,NaN,NaN,0.123057,0.640202,0.652495,NaN,0.673532,0.996997,NaN,NaN,1.161332,1.236168,NaN,NaN,143.569402,140.250161,132.380352,135.875407,0.805227,0.180884,117.595975
13,202406050702,14,4.1,2,0.242279,0.216123,1.866925,1.969108,1.166220,0.123810,3,2,NaN,NaN,1.650661,2.500423,-1.478100,NaN,0.529210,0.068666,NaN,NaN,-1.018276,-0.912000,NaN,NaN,146.916084,142.411033,146.916084,142.411033,1.144533,1.230419,117.374496

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第4回目レース

In [10]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050704",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [11]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050704,2022106337,1209,1114,1,1,54.5,13,53.0,0,2,NaN,NaN,16,2.0,2.0,2
1,202406050704,2022105508,1117,1074,2,1,72.6,15,56.0,0,2,NaN,NaN,16,2.0,2.0,2
2,202406050704,2022105448,1140,1189,3,2,7.5,3,56.0,0,2,NaN,NaN,16,2.0,2.0,2
3,202406050704,2022107286,1206,1020,4,2,35.5,10,52.0,0,2,NaN,NaN,16,2.0,2.0,2
4,202406050704,2022101023,1075,405,5,3,44.3,12,56.0,0,2,NaN,NaN,16,2.0,2.0,2
5,202406050704,2022105823,5626,1179,6,3,2.3,1,56.0,0,2,NaN,NaN,16,2.0,2.0,2
6,202406050704,2022102486,1091,1056,7,4,26.2,7,56.0,0,2,NaN,NaN,16,2.0,2.0,2
7,202406050704,2022105979,1122,1097,8,4,5.3,2,56.0,0,2,NaN,NaN,16,2.0,2.0,2
8,202406050704,2022106785,5386,1094,9,5,19.5,6,56.0,0,2,NaN,NaN,16,2.0,2.0,2
9,202406050704,2022107159,1203,1124,10,5,112.5,16,53.0,0,2,NaN,NaN,16,2.0,2.0,2
10,202406050704,2022105901,1161,1047,11,6,42.4,11,55.0,1,2,NaN,NaN,16,2.0,2.0,2
11,202406050704,2022104062,1179,1133,12,6,8.3,4,56.0,0,2,NaN,NaN,16,2.0,2.0,2
12,202406050704,2022103375,1109,1190,13,7,28.3,8,56.0,0,2,NaN,NaN,16,2.0,2.0,2
13,202406050704,2022100195,1160,1177,14,7,10.1,5,56.0,0,2,NaN,NaN,16,2.0,2.0,2
14,202406050704,2022105647,1143,423,15,8,55.0,14,56.0,0,2,NaN,NaN,16,2.0,2.0,2
15,202406050704,2022103851,1162,1076,16,8,29.8,9,56.0,0,2,NaN,NaN,16,2.0,2.0,2

In [12]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050704,0,0,1800,1,0,1,6,4,73875004,4,64,640,4,40,7,70,5,50,64070,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401800,-1,24,60,1.0

In [13]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
15,202406050704,16,29.8,9,0.211853,0.193622,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.416547,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.426967
14,202406050704,15,55.0,14,0.211853,0.197343,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.416547,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.164871
3,202406050704,4,35.5,10,0.196187,0.211460,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.416547,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.974554
9,202406050704,10,112.5,16,0.219168,0.229282,-1.184963,-0.854059,0.617647,-0.145692,4,1,NaN,-0.647150,-0.500269,-0.416547,-0.776764,NaN,-0.901350,-0.671279,NaN,NaN,-0.126736,-0.173522,NaN,NaN,145.297180,143.700161,138.928626,143.605129,1.137578,1.386911,120.828028
4,202406050704,5,44.3,12,0.178354,0.195387,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.416547,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.737712
12,202406050704,13,28.3,8,0.242279,0.228707,-1.168441,-0.778859,0.235366,-0.544309,3,1,NaN,NaN,-0.500269,-0.416547,-0.875401,NaN,-1.085583,-1.154438,NaN,NaN,-0.137520,-0.040220,NaN,NaN,128.202896,140.433666,128.202896,140.433666,-0.696601,0.098540,120.233972
1,202406050704,2,72.6,15,0.182594,0.200272,-1.251566,-0.854059,0.272222,-0.430556,2,1,NaN,NaN,-0.500269,-0.416547,1.097334,NaN,-0.382984,-0.635882,NaN,NaN,1.271506,1.088267,NaN,NaN,123.817942,137.684508,123.817942,137.684508,-1.167097,-0.985782,119.875525
0,202406050704,1,54.5,13,0.182594,0.180707,0.346685,0.278540,0.878154,-0.235134,4,1,NaN,-0.647150,-0.500269,-0.416547,-0.776764,NaN,-0.505297,-0.228387,NaN,NaN,-0.265852,-0.350556,NaN,NaN,131.954624,136.338462,127.062193,135.005129,-0.294049,-1.516690,119.170214
8,202406050704,9,19.5,6,0.219168,0.193460,-0.442081,-1.817941,0.819599,-0.527122,2,1,NaN,-0.647150,-0.084821,0.052802,1.097334,NaN,0.264058,0.266068,NaN,NaN,1.524037,1.488855,NaN,NaN,140.152089,139.795222,129.535907,137.475407,0.585521,-0.153275,119.071232
13,202406050704,14,10.1,5,0.242279,0.216123,-0.193140,-0.420304,0.508455,-0.193659,3,1,NaN,NaN,-0.500269,-0.416547,-0.875401,NaN,-0.777515,-0.738661,NaN,NaN,-0.257754,-0.224881,NaN,NaN,126.192884,140.670910,116.817942,137.684508,-0.912271,0.192115,119.032101
10,202406050704,11,42.4,11,0.207064,0.221751,0.492650,0.723856,0.895455,-0.024242,3,1,NaN,-0.647150,-0.500269,-0.416547,-0.875401,NaN,-0.742213,-0.866454,NaN,NaN,-0.271532,-0.168124,NaN,NaN,148.693862,142.411033,148.693862,142.411033,1.502034,0.878454,119.021343
6,202406050704,7,26.2,7,0.184862,0.174863,-0.692185,-0.348012,0.311111,-0.220833,3,1,NaN,-0.647150,-0.500269,-0.416547,-0.875401,NaN,-0.888860,-0.989447,NaN,NaN,-0.214298,-0.113498,NaN,NaN,121.217942,139.084508,121.217942,139.084508,-1.446071,-0.433594,118.735957
2,202406050704,3,7.5,3,0.196187,0.203274,0.112741,0.380169,0.938462,-0.060119,3,1,NaN,-0.647150,2.864860,3.385180,-0.875401,NaN,1.646051,1.136579,NaN,NaN,-1.203634,-1.057743,NaN,NaN,128.692665,136.006951,128.692665,136.006951,-0.644050,-1.647444,117.796003
11,202406050704,12,8.3,4,0.207064,0.222059,1.363158,1.374488,1.283463,-0.493196,2,1,NaN,1.016950,-0.084821,-0.064536,1.097334,NaN,0.896672,1.137853,NaN,NaN,1.770936,1.876046,NaN,NaN,145.910179,141.405129,142.365735,140.105129,1.203351,0.481705,117.786248
5,202406050704,6,2.3,1,0.178354,0.171662,1.691854,1.242423,1.271930,-0.053810,3,1,NaN,1.849001,0.995344,1.273109,-0.875401,NaN,1.311136,1.548900,NaN,NaN,-1.072922,-1.240869,NaN,NaN,140.380514,143.450161,134.832402,140.105129,0.610031,1.288306,117.162383
7,202406050704,8,5.3,2,0.184862,0.223881,0.925288,1.073758,0.970553,-0.303066,3,1,NaN,1.016950,-0.188683,-0.064536,-0.875401,NaN,1.165884,1.195148,NaN,NaN,-1.016233,-1.083755,NaN,NaN,135.828608,141.225243,130.424796,137.475407,0.121621,0.410754,117.093719

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第7回目レース

In [14]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050707",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [15]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050707,2022100837,1112,1084,1,1,17.7,8,56.0,0,2,NaN,NaN,16,2.0,2.0,2
1,202406050707,2022106689,1179,1159,2,1,9.6,4,55.0,1,2,NaN,NaN,16,2.0,2.0,2
2,202406050707,2022107203,1184,1156,3,2,49.0,13,54.0,1,2,NaN,NaN,16,2.0,2.0,2
3,202406050707,2022106698,1214,1076,4,2,44.6,12,52.0,1,2,NaN,NaN,16,2.0,2.0,2
4,202406050707,2022105965,1122,1151,5,3,2.9,1,56.0,0,2,NaN,NaN,16,2.0,2.0,2
5,202406050707,2022106405,1077,1063,6,3,128.8,16,55.0,1,2,NaN,NaN,16,2.0,2.0,2
6,202406050707,2022106500,1206,1174,7,4,51.0,14,51.0,1,2,NaN,NaN,16,2.0,2.0,2
7,202406050707,2022102790,1192,1167,8,4,4.7,2,55.0,0,2,NaN,NaN,16,2.0,2.0,2
8,202406050707,2022110001,1170,1071,9,5,10.9,5,55.0,1,2,NaN,NaN,16,2.0,2.0,2
9,202406050707,2022106418,5386,1035,10,5,41.5,11,56.0,0,2,NaN,NaN,16,2.0,2.0,2
10,202406050707,2022100216,1092,1094,11,6,13.8,7,55.0,1,2,NaN,NaN,16,2.0,2.0,2
11,202406050707,2022104533,1117,437,12,6,60.0,15,56.0,0,2,NaN,NaN,16,2.0,2.0,2
12,202406050707,2022102711,422,1169,13,7,29.4,10,56.0,0,2,NaN,NaN,16,2.0,2.0,2
13,202406050707,2022100618,1140,1195,14,7,8.3,3,55.0,1,2,NaN,NaN,16,2.0,2.0,2
14,202406050707,2022105598,1197,1059,15,8,13.7,6,56.0,0,2,NaN,NaN,16,2.0,2.0,2
15,202406050707,2022103959,1162,1106,16,8,21.8,9,55.0,1,2,NaN,NaN,16,2.0,2.0,2

In [16]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050707,0,0,1200,1,0,2,6,7,73875007,4,64,640,7,70,7,70,5,50,64070,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401200,-1,24,70,2.0

In [17]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
0,202406050707,1,17.7,8,0.174194,0.188623,NaN,NaN,NaN,NaN,2,4,NaN,NaN,NaN,-1.071764,0.365963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.769405
11,202406050707,12,60.0,15,0.211510,0.239394,NaN,NaN,NaN,NaN,2,4,NaN,NaN,NaN,-1.071764,0.365963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.756864
6,202406050707,7,51.0,14,0.176471,0.154762,-2.036179,-0.691971,0.872759,-0.125380,2,4,NaN,NaN,-1.205735,-1.071764,0.365963,NaN,-1.517024,-2.051635,NaN,NaN,-0.241612,-0.342810,NaN,NaN,134.072337,142.531221,132.565735,140.505129,-1.588512,-0.238690,74.686960
5,202406050707,6,128.8,16,0.192982,0.209199,-0.420860,0.196772,0.672917,-0.336979,3,4,NaN,NaN,-1.205735,-1.071764,-2.561738,NaN,-1.462848,-1.918116,NaN,NaN,-1.934149,-1.989231,NaN,NaN,134.229002,141.339939,130.536152,139.745687,-1.564567,-0.531528,73.973953
2,202406050707,3,49.0,13,0.179209,0.174107,-0.397249,-0.137439,0.795000,0.143730,2,4,NaN,NaN,0.445149,1.403558,0.365963,NaN,0.370884,0.706950,NaN,NaN,0.460791,0.547048,NaN,NaN,142.745204,145.289657,141.694881,141.346314,-0.262944,0.439382,73.615049
12,202406050707,13,29.4,10,0.205970,0.198157,-0.690276,-0.118113,0.936774,-0.139086,2,4,NaN,NaN,-0.277113,-0.196060,0.365963,NaN,0.391747,0.114195,NaN,NaN,0.468553,0.355838,NaN,NaN,147.522970,148.223408,136.796408,140.568560,0.467294,1.160548,73.569040
10,202406050707,11,13.8,7,0.211510,0.181682,-1.081413,-1.696623,0.853172,-0.114166,2,4,NaN,NaN,-0.380293,-0.487961,0.365963,NaN,0.049014,0.823173,NaN,NaN,0.341038,0.584539,NaN,NaN,136.170919,147.665922,110.184418,141.235029,-1.267763,1.023509,73.535987
9,202406050707,10,41.5,11,0.189940,0.203593,0.642129,0.369817,1.541392,-0.561077,2,4,NaN,NaN,-0.380293,-0.604722,0.365963,NaN,-0.234854,0.637647,NaN,NaN,0.235424,0.524692,NaN,NaN,151.385793,145.693539,137.336152,137.946314,1.057690,0.538663,73.527503
15,202406050707,16,21.8,9,0.208644,0.189895,-0.585676,-1.701421,0.273770,-0.374716,2,4,NaN,NaN,-0.586653,-0.487961,0.365963,NaN,-0.168138,-0.408191,NaN,NaN,0.260246,0.187328,NaN,NaN,141.749709,143.952052,137.278625,137.758913,-0.415096,0.110575,73.473770
3,202406050707,4,44.6,12,0.179209,0.194362,0.337876,0.641264,0.693891,-0.464405,2,4,NaN,NaN,-1.205735,-0.254441,0.365963,NaN,-1.316073,-0.598114,NaN,NaN,-0.166847,0.126063,NaN,NaN,148.042613,150.486883,139.145725,136.504629,0.546716,1.716950,73.390193
8,202406050707,9,10.9,5,0.189940,0.183036,-0.147835,-0.215896,1.117778,-0.385787,2,4,NaN,NaN,1.765856,1.730487,0.365963,NaN,0.550418,0.243373,NaN,NaN,0.527587,0.397508,NaN,NaN,150.808489,144.911721,143.862193,142.746314,0.969455,0.346478,72.973803
14,202406050707,15,13.7,6,0.208644,0.207792,0.252014,0.259776,1.702356,-0.392222,1,4,NaN,NaN,-0.380293,-0.293361,0.365963,NaN,-0.056738,0.633885,NaN,NaN,0.301693,0.523479,NaN,NaN,143.720562,141.222612,128.004973,138.611033,-0.113869,-0.560369,72.967986
1,202406050707,2,9.6,4,0.174194,0.158209,0.118010,-0.242569,1.090000,-0.008904,3,4,NaN,NaN,1.765856,1.730487,-2.561738,NaN,0.007162,-0.233188,NaN,NaN,-2.481071,-2.532751,NaN,NaN,153.477012,141.962879,153.477012,141.962879,1.377314,-0.378398,72.740821
13,202406050707,14,8.3,3,0.205970,0.218553,1.609116,1.927221,2.098593,-0.793333,2,4,NaN,NaN,0.651510,0.679643,0.365963,NaN,2.136794,1.106416,NaN,NaN,1.117804,0.675907,NaN,NaN,142.073052,135.804424,142.073052,135.804424,-0.365676,-1.892253,72.714368
4,202406050707,5,2.9,1,0.192982,0.177083,0.734216,-0.085428,1.040213,-0.374007,2,4,NaN,NaN,0.032428,0.095841,0.365963,NaN,-0.006391,-0.162809,NaN,NaN,0.320424,0.266483,NaN,NaN,152.619530,143.071540,143.120149,141.585351,1.246256,-0.105870,72.703906
7,202406050707,8,4.7,2,0.176471,0.206538,1.666128,1.494609,1.540561,-0.557500,2,4,NaN,NaN,0.961050,0.971544,0.365963,NaN,1.256047,1.106416,NaN,NaN,0.790119,0.675907,NaN,NaN,143.900956,136.875369,140.006385,132.404424,-0.086298,-1.628996,72.500875

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

### 12/21 第8回目レース

In [18]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050708",  # 予測するレースidを指定
    date_content_a = "2024年12月21日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [19]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050708,2020103438,1108,1063,1,1,78.0,15,56.0,1,4,NaN,NaN,16,3.5,3.0,3
1,202406050708,2021101776,1184,1156,2,1,67.7,12,56.0,0,3,NaN,NaN,16,3.5,3.0,3
2,202406050708,2021104276,1075,1027,3,2,7.3,4,57.0,0,3,NaN,NaN,16,3.5,3.0,3
3,202406050708,2021105974,1170,1038,4,2,5.6,2,55.0,1,3,NaN,NaN,16,3.5,3.0,3
4,202406050708,2020103900,1197,1112,5,3,18.2,9,56.0,1,4,NaN,NaN,16,3.5,3.0,3
5,202406050708,2021103894,1192,1077,6,3,16.5,8,54.0,1,3,NaN,NaN,16,3.5,3.0,3
6,202406050708,2021103513,5386,1086,7,4,13.1,7,55.0,1,3,NaN,NaN,16,3.5,3.0,3
7,202406050708,2021103535,422,1156,8,4,31.6,11,57.0,0,3,NaN,NaN,16,3.5,3.0,3
8,202406050708,2020103530,1043,1079,9,5,8.3,5,56.0,1,4,NaN,NaN,16,3.5,3.0,3
9,202406050708,2021106064,1092,1026,10,5,19.0,10,57.0,0,3,NaN,NaN,16,3.5,3.0,3
10,202406050708,2021102617,726,1081,11,6,76.3,13,55.0,1,3,NaN,NaN,16,3.5,3.0,3
11,202406050708,2019100097,1214,1035,12,6,77.5,14,53.0,1,5,NaN,NaN,16,3.5,3.0,3
12,202406050708,2020106979,1183,1089,13,7,89.6,16,56.0,0,4,NaN,NaN,16,3.5,3.0,3
13,202406050708,2021105779,1140,1202,14,7,4.5,1,57.0,0,3,NaN,NaN,16,3.5,3.0,3
14,202406050708,2019105338,1179,1070,15,8,10.1,6,58.0,2,5,NaN,NaN,16,3.5,3.0,3
15,202406050708,2021102516,5626,1043,16,8,6.1,3,55.0,1,3,NaN,NaN,16,3.5,3.0,3

In [20]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050708,0,0,1200,1,0,2,6,8,73875008,4,64,640,8,80,7,70,5,50,64070,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401200,-1,34,70,2.0

In [21]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
8,202406050708,9,8.3,5,0.189940,0.183036,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.730446,0.652598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.195717
7,202406050708,8,31.6,11,0.176471,0.206538,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.730446,0.652598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.124757
0,202406050708,1,78.0,15,0.174194,0.188623,-2.138160,-2.654071,0.632276,-0.401350,2,2,NaN,-0.333333,-0.638384,-0.730446,0.652598,NaN,-1.082082,-1.088907,NaN,NaN,0.431603,0.327666,NaN,NaN,143.558338,146.453758,134.494006,138.066493,-0.561400,-0.474257,73.878794
4,202406050708,5,18.2,9,0.192982,0.177083,-0.970280,-0.987051,1.389892,-0.168572,2,2,NaN,-0.333333,-0.245532,-0.019478,0.652598,NaN,-0.070423,0.045499,NaN,NaN,0.657013,0.695767,NaN,NaN,164.993136,152.691829,157.160623,148.793957,1.265818,0.556361,73.842534
11,202406050708,12,77.5,14,0.211510,0.239394,-1.034185,-0.338297,0.772293,-0.583069,2,2,NaN,-0.333333,-0.638384,-0.730446,0.652598,NaN,-0.888110,-0.630529,NaN,NaN,0.474823,0.476404,NaN,NaN,149.693206,153.105011,148.910352,152.669256,-0.038431,0.624624,73.820001
1,202406050708,2,67.7,12,0.174194,0.158209,-0.154062,0.019867,1.198540,-0.115910,3,2,NaN,NaN,-0.638384,-0.730446,-1.456809,NaN,-1.558572,-0.975476,NaN,NaN,-0.983779,-0.923285,NaN,NaN,163.202314,153.998196,139.676846,140.505129,1.113158,0.772191,73.567994
10,202406050708,11,76.3,13,0.211510,0.181682,-0.203047,0.215126,1.335602,-0.738759,2,2,NaN,-0.333333,-0.638384,-0.493456,0.652598,NaN,-0.545627,-1.071176,NaN,NaN,0.551132,0.333420,NaN,NaN,152.348845,142.764531,142.228626,141.834191,0.187950,-1.083769,73.331654
12,202406050708,13,89.6,16,0.205970,0.198157,-0.321534,-0.389391,0.449882,-0.281333,3,2,NaN,-0.333333,-0.638384,-0.730446,-1.456809,NaN,-1.498807,-1.506814,NaN,NaN,-0.997095,-0.750873,NaN,NaN,134.325239,142.670440,131.521853,141.345687,-1.348479,-1.099314,72.882233
9,202406050708,10,19.0,10,0.189940,0.203593,-0.890836,-0.800467,NaN,-1.016667,2,2,NaN,NaN,-0.343745,-0.286091,0.652598,NaN,0.537870,-0.748656,NaN,NaN,0.792548,0.438074,NaN,NaN,126.206385,134.604424,126.206385,134.604424,-2.040574,-2.431934,72.773805
5,202406050708,6,16.5,8,0.192982,0.209199,1.111432,1.183901,2.235714,-0.238077,2,2,NaN,2.666667,-0.245532,0.392884,0.652598,NaN,0.590652,1.003224,NaN,NaN,0.804308,1.006537,NaN,NaN,166.209393,147.940765,166.209393,147.940765,1.369498,-0.228582,72.772891
6,202406050708,7,13.1,7,0.176471,0.154762,0.390427,0.300785,1.271695,0.474028,2,2,NaN,-0.333333,-0.638384,-0.730446,0.652598,NaN,0.722441,0.701005,NaN,NaN,0.833673,0.908471,NaN,NaN,142.280708,149.486883,130.952024,147.633001,-0.670312,0.026859,72.469258
15,202406050708,16,6.1,3,0.208644,0.189895,1.141224,0.984434,1.877433,0.199792,3,2,NaN,NaN,2.190148,1.829040,-1.456809,NaN,1.132085,1.249042,NaN,NaN,-1.583289,-1.645115,NaN,NaN,149.315442,149.976911,134.709393,148.046912,-0.070634,0.107818,72.451842
3,202406050708,4,5.6,2,0.179209,0.194362,0.724765,0.551350,2.459891,0.289632,3,2,NaN,-0.333333,2.190148,1.829040,-1.456809,NaN,1.112979,1.233246,NaN,NaN,-1.579032,-1.639989,NaN,NaN,148.800547,151.744863,141.362791,148.833001,-0.114526,0.399909,72.353966
13,202406050708,14,4.5,1,0.205970,0.218553,0.302579,0.551350,1.415824,-0.281457,4,2,NaN,NaN,0.775882,2.018631,-1.351338,NaN,-0.305984,0.049641,NaN,NaN,-1.160312,-1.153662,NaN,NaN,148.019425,152.993838,146.276059,152.646912,-0.181113,0.606257,72.314269
2,202406050708,3,7.3,4,0.179209,0.174107,0.841693,0.805351,2.520510,-0.027381,2,2,NaN,NaN,-0.245532,-0.137972,0.652598,NaN,0.392849,0.428512,NaN,NaN,0.760236,0.820051,NaN,NaN,148.859393,154.590765,139.636152,144.034191,-0.109510,0.870092,72.284072
14,202406050708,15,10.1,6,0.208644,0.207792,1.199984,0.557114,2.943618,-0.158611,2,2,NaN,-0.333333,-0.245532,-0.019478,0.652598,NaN,1.460728,1.311389,NaN,NaN,0.998172,1.106533,NaN,NaN,164.204081,157.518195,153.534759,156.640765,1.198554,1.353745,72.210922

In [ ]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)