In [1]:
import create_population
import create_population3
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction
from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_kaiki_cross import Trainer_lightgbm_rank_kaiki_cv
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross

import pandas as pd


import condition_prediction


from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki

from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

In [2]:
%autoreload

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [ ]:
population = create_population.create(from_="2016-01-01", to_="2024-11-30")

In [4]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

,horse_id,rank_per_horse,date,rank,prize,rank_diff,umaban,wakuban,weather,race_type,course_len,impost,ground_state,race_class,n_horses,time,time_courselen,nobori,win,rentai,show,place,goal_range,curve,goal_slope,goal_range_100,place_course_category,place_course_tough,corner_1_per_horse,corner_2_per_horse,corner_3_per_horse,corner_4_per_horse,race_position,race_grade,race_grade_scaled,pace_diff,pace_category,place_season_condition_type_categori,corner_1,corner_2,corner_3,corner_4,pace_1,pace_2
3,2022110128,0.187500,2024-11-17,3.0,140.0,0.4,8,4,1,0,1300,56.0,0,1,16,79.3,0.061000,36.7,0,0,1,5,NaN,NaN,NaN,NaN,-1,-1,0.375,0.3125,<NA>,<NA>,3,60,1.0,NaN,NaN,-1,6,5,<NA>,<NA>,29.5,36.9
4,2022110128,0.133333,2024-10-19,2.0,220.0,0.1,11,6,1,0,1400,56.0,0,1,15,85.9,0.061357,37.3,0,1,1,5,NaN,NaN,NaN,NaN,-1,-1,0.133333,0.133333,<NA>,<NA>,2,60,1.0,1.7,1.0,-1,2,2,<NA>,<NA>,35.6,37.3
5,2022110128,0.125000,2024-09-29,2.0,290.0,0.5,3,2,2,1,1200,55.0,0,0,16,69.8,0.058167,34.7,0,1,1,6,310.0,5.0,3.0,3.100,602,1,0.1875,0.1875,<NA>,<NA>,2,55,0.5,-0.5,3.0,4,3,3,<NA>,<NA>,34.9,34.4
7,2022102442,0.625000,2024-11-03,10.0,0.0,1.9,16,8,1,0,1150,55.0,3,1,16,69.9,0.060783,37.8,0,0,0,3,NaN,NaN,NaN,NaN,-1,-1,0.4375,0.4375,<NA>,<NA>,3,60,1.0,NaN,NaN,-2,7,7,<NA>,<NA>,31.4,36.6
8,2022102442,0.714286,2024-09-16,10.0,0.0,4.3,14,8,1,0,1400,54.0,2,0,14,88.2,0.063000,40.5,0,0,0,7,NaN,NaN,NaN,NaN,-1,-1,0.5,0.428571,<NA>,<NA>,3,55,0.5,1.9,1.0,-3,7,6,<NA>,<NA>,34.9,36.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3557,2021106601,0.166667,2024-06-15,3.0,140.0,0.2,13,7,1,1,1400,57.0,0,1,18,80.2,0.057286,33.6,0,0,1,8,345.0,5.0,1.0,3.450,803,2,0.444444,0.444444,<NA>,<NA>,3,60,1.0,0.1,2.0,4,8,8,<NA>,<NA>,34.2,34.3
3558,2021106601,0.200000,2024-04-14,3.0,111.5,0.1,13,7,1,0,1400,57.0,0,1,15,85.5,0.061071,37.3,0,0,1,9,NaN,NaN,NaN,NaN,-1,-1,0.333333,0.333333,<NA>,<NA>,3,60,1.0,3.1,1.0,-2,5,5,<NA>,<NA>,35.0,38.1
3559,2021106601,0.111111,2024-03-24,2.0,220.0,0.5,18,8,3,1,1600,56.0,1,1,18,95.1,0.059437,35.9,0,1,1,9,473.6,5.0,3.0,4.736,902,3,0.222222,0.222222,<NA>,<NA>,2,60,1.0,0.6,2.0,3,4,4,<NA>,<NA>,35.0,35.6
3560,2021106601,0.444444,2024-01-27,4.0,83.0,1.0,1,1,2,1,1800,57.0,0,1,9,108.3,0.060167,36.5,0,0,0,8,403.7,5.0,1.0,4.037,802,3,0.555556,0.444444,<NA>,<NA>,2,60,1.0,1.0,2.0,2,5,4,<NA>,<NA>,34.8,35.8
3561,2021106601,0.388889,2024-01-14,7.0,0.0,1.4,9,5,1,1,1600,57.0,0,0,18,96.5,0.060312,36.0,0,0,0,8,345.0,5.0,1.0,3.450,803,2,0.5,0.5,<NA>,<NA>,3,55,0.5,0.9,2.0,2,9,9,<NA>,<NA>,34.7,35.6

In [5]:
# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

       horse_id     sire_id      bms_id
2    2022110128  000a01c067  000a015377
4    2022102442  2014106046  2007102923
5    2022106686  2010110102  000a0022e1
6    2022100399  2001190004  1998110135
10   2022100325  2005109202  1999100226
..          ...         ...         ...
369  2019106076  2011103328  000a000006
370  2020106727  2012102013  000a0115e2
372  2020104825  2007103143  2000101517
377  2018103368  2010104298  1995103211
378  2021106601  2011103565  000a00fa34

[184 rows x 3 columns]

In [6]:
pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

agg_horse_n_races_relative:   0%|          | 0/4 [00:00<?, ?it/s]

,date,race_id,horse_id,rank_1races,rank_per_horse_1races,prize_1races,rank_3races,rank_per_horse_3races,prize_3races,rank_5races,rank_per_horse_5races,prize_5races,rank_10races,rank_per_horse_10races,prize_10races,rank_1000races,rank_per_horse_1000races,prize_1000races
0,2024-12-22,202406050801,2022110128,3.0,0.187500,140.0,2.333333,0.148611,216.666667,2.333333,0.148611,216.666667,2.333333,0.148611,216.666667,2.333333,0.148611,216.666667
1,2024-12-22,202406050801,2022102442,10.0,0.625000,0.0,10.000000,0.669643,0.000000,10.000000,0.669643,0.000000,10.000000,0.669643,0.000000,10.000000,0.669643,0.000000
2,2024-12-22,202406050801,2022106686,2.0,0.181818,290.0,2.000000,0.181818,290.000000,2.000000,0.181818,290.000000,2.000000,0.181818,290.000000,2.000000,0.181818,290.000000
3,2024-12-22,202406050801,2022100399,13.0,0.866667,0.0,9.333333,0.646032,27.666667,7.600000,0.569437,44.600000,7.600000,0.569437,44.600000,7.600000,0.569437,44.600000
4,2024-12-22,202406050801,2022100325,11.0,0.733333,0.0,7.333333,0.585714,18.333333,7.250000,0.585119,13.750000,7.250000,0.585119,13.750000,7.250000,0.585119,13.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,2024-12-22,202408070812,2019106076,12.0,0.923077,0.0,12.666667,0.849359,0.000000,11.600000,0.776282,0.000000,9.700000,0.670136,101.380000,8.071429,0.570481,163.128571
180,2024-12-22,202408070812,2020106727,8.0,0.666667,0.0,7.000000,0.583528,0.000000,6.800000,0.575117,160.000000,5.900000,0.536276,167.000000,5.900000,0.536276,167.000000
181,2024-12-22,202408070812,2020104825,12.0,0.800000,0.0,11.333333,0.706618,0.000000,11.200000,0.722185,0.000000,10.000000,0.670026,80.000000,9.421053,0.596534,94.210526
182,2024-12-22,202408070812,2018103368,2.0,0.166667,460.0,7.000000,0.498413,153.333333,7.000000,0.455910,184.000000,5.800000,0.434878,217.450000,5.843750,0.415960,186.871875
183,2024-12-22,202408070812,2021106601,3.0,0.230769,200.0,5.666667,0.343127,113.333333,4.600000,0.279209,118.300000,4.500000,0.292561,111.812500,4.500000,0.292561,111.812500

In [7]:
# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

###　12/22 第1回目レース

In [8]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070801",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [9]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070801,2022106318,1195,1136,1,1,121.4,13,52.0,1,2,NaN,NaN,16,2.0,2.0,2
1,202408070801,2022107239,1144,1200,2,1,181.8,15,55.0,1,2,NaN,NaN,16,2.0,2.0,2
2,202408070801,2022104165,1180,1069,3,2,100.9,12,55.0,1,2,NaN,NaN,16,2.0,2.0,2
3,202408070801,2022102739,1124,1095,4,2,23.0,9,55.0,1,2,NaN,NaN,16,2.0,2.0,2
4,202408070801,2022103527,1190,1121,5,3,5.1,2,52.0,1,2,NaN,NaN,16,2.0,2.0,2
5,202408070801,2022106661,1197,1154,6,3,15.0,7,55.0,1,2,NaN,NaN,16,2.0,2.0,2
6,202408070801,2022106631,1174,1158,7,4,2.3,1,55.0,1,2,NaN,NaN,16,2.0,2.0,2
7,202408070801,2022104408,1034,1078,8,4,20.1,8,55.0,1,2,NaN,NaN,16,2.0,2.0,2
8,202408070801,2022106552,1152,1206,9,5,195.2,16,55.0,1,2,NaN,NaN,16,2.0,2.0,2
9,202408070801,2022105774,1171,1148,10,5,11.8,5,55.0,1,2,NaN,NaN,16,2.0,2.0,2
10,202408070801,2022104653,1216,1172,11,6,63.2,10,53.0,1,2,NaN,NaN,16,2.0,2.0,2
11,202408070801,2022101068,5212,1130,12,6,6.6,3,55.0,1,2,NaN,NaN,16,2.0,2.0,2
12,202408070801,2022101656,1213,1066,13,7,11.3,4,53.0,1,2,NaN,NaN,16,2.0,2.0,2
13,202408070801,2022103047,1091,1072,14,7,12.4,6,55.0,1,2,NaN,NaN,16,2.0,2.0,2
14,202408070801,2022102919,1095,1101,15,8,169.0,14,55.0,1,2,NaN,NaN,16,2.0,2.0,2
15,202408070801,2022102035,1208,431,16,8,72.5,11,54.0,1,2,NaN,NaN,16,2.0,2.0,2

In [10]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070801,0,0,1400,2,0,1,8,1,73875101,4,84,840,1,10,8,80,7,70,84080,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401400,-1,24,60,1.0

In [11]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
9,202408070801,8,20.1,8,0.190196,0.172794,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.918761
4,202408070801,16,72.5,11,0.196330,0.182927,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.837406
8,202408070801,1,121.4,13,0.220957,0.215328,-2.069930,-1.878315,0.750000,-0.133333,3,1,NaN,NaN,-0.820812,-0.622770,-1.111623,NaN,-1.583293,-1.590812,NaN,NaN,-0.196229,-0.106440,NaN,NaN,124.013974,137.436793,124.013974,137.436793,-1.425867,-1.044174,89.584147
12,202408070801,15,169.0,14,0.196330,0.172589,-0.389732,-0.166407,0.327419,0.215094,2,1,NaN,-0.711512,-0.820812,-0.622770,0.853677,NaN,-0.388909,-0.482584,NaN,NaN,0.777562,0.706364,NaN,NaN,145.795401,147.359503,145.795401,147.359503,1.426775,2.245140,89.431247
5,202408070801,10,11.8,5,0.209524,0.223048,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.275669
13,202408070801,6,15.0,7,0.186475,0.230769,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.049338
2,202408070801,12,6.6,3,0.212687,0.204000,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.947975
6,202408070801,9,195.2,16,0.209524,0.186131,-0.600751,-0.381409,0.334848,-0.203030,3,1,NaN,-0.711512,-0.820812,-0.622770,-1.111623,NaN,-0.897726,-1.017426,NaN,NaN,-0.469882,-0.358704,NaN,NaN,129.117942,137.984508,129.117942,137.984508,-0.757417,-0.862610,88.896574
3,202408070801,2,181.8,15,0.220957,0.249084,-0.863773,-0.840073,0.810055,-0.325654,3,1,NaN,-0.711512,-0.820812,-0.622770,-1.111623,NaN,-0.907698,-0.854754,NaN,NaN,-0.465901,-0.430273,NaN,NaN,142.228938,143.207313,137.434494,142.857313,0.959687,0.868716,88.374704
1,202408070801,3,100.9,12,0.214894,0.186813,-0.114544,-0.348094,0.674630,-0.308055,4,1,NaN,0.474342,0.843933,1.214442,-1.013358,NaN,-0.623272,-0.559823,NaN,NaN,-0.502298,-0.487683,NaN,NaN,138.465898,143.370004,133.197641,141.362879,0.466854,0.922647,88.146400
0,202408070801,11,63.2,10,0.212687,0.192453,-0.193575,-0.531313,0.541739,-0.452020,2,1,NaN,-0.711512,-0.820812,-0.622770,0.853677,NaN,0.039444,0.012952,NaN,NaN,0.948545,0.924378,NaN,NaN,123.770907,139.748273,122.705584,139.733666,-1.457701,-0.277933,87.931895
10,202408070801,4,23.0,9,0.214894,0.244526,0.229241,-0.042728,0.650000,-0.067763,3,1,NaN,0.474342,-0.358383,-0.112434,-1.111623,NaN,0.723435,0.888408,NaN,NaN,-1.116988,-1.197187,NaN,NaN,131.207048,138.550058,121.562727,137.337237,-0.483814,-0.675134,87.412823
14,202408070801,14,12.4,6,0.198895,0.207373,0.795856,1.041556,1.188353,0.399302,2,1,NaN,-0.711512,-0.127168,0.142735,0.853677,NaN,1.093843,1.020721,NaN,NaN,1.369421,1.367752,NaN,NaN,132.391298,139.162879,132.391298,139.162879,-0.328717,-0.471987,87.203271
7,202408070801,13,11.3,4,0.198895,0.192308,0.889244,0.812295,0.754871,-0.214062,3,1,NaN,-0.711512,1.676306,2.133049,-1.111623,NaN,0.058167,0.120859,NaN,NaN,-0.851438,-0.859499,NaN,NaN,133.331648,138.807183,123.937084,134.137237,-0.205562,-0.589899,86.844333
11,202408070801,7,2.3,1,0.190196,0.208029,0.810608,0.568003,0.893771,-0.037500,2,1,NaN,1.660196,0.393065,0.716864,0.853677,NaN,1.747349,1.605063,NaN,NaN,1.630276,1.624836,NaN,NaN,140.278477,139.050058,139.262727,136.637237,0.704241,-0.509387,86.752377
15,202408070801,5,5.1,2,0.186475,0.168498,1.507356,1.766485,2.646210,-0.305682,3,1,NaN,1.660196,1.676306,2.133049,-1.111623,NaN,0.738660,0.857396,NaN,NaN,-1.123066,-1.183543,NaN,NaN,143.311927,141.777128,143.311927,141.777128,1.101522,0.394619,86.563493

In [12]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
12,202408070801,15,169.0,14,0.196330,0.172589,-0.389732,-0.166407,0.327419,0.215094,2,1,NaN,-0.711512,-0.820812,-0.622770,0.853677,NaN,-0.388909,-0.482584,NaN,NaN,0.777562,0.706364,NaN,NaN,145.795401,147.359503,145.795401,147.359503,1.426775,2.245140,90.186665
4,202408070801,16,72.5,11,0.196330,0.182927,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.013755
9,202408070801,8,20.1,8,0.190196,0.172794,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.746434
8,202408070801,1,121.4,13,0.220957,0.215328,-2.069930,-1.878315,0.750000,-0.133333,3,1,NaN,NaN,-0.820812,-0.622770,-1.111623,NaN,-1.583293,-1.590812,NaN,NaN,-0.196229,-0.106440,NaN,NaN,124.013974,137.436793,124.013974,137.436793,-1.425867,-1.044174,89.713678
5,202408070801,10,11.8,5,0.209524,0.223048,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.128448
6,202408070801,9,195.2,16,0.209524,0.186131,-0.600751,-0.381409,0.334848,-0.203030,3,1,NaN,-0.711512,-0.820812,-0.622770,-1.111623,NaN,-0.897726,-1.017426,NaN,NaN,-0.469882,-0.358704,NaN,NaN,129.117942,137.984508,129.117942,137.984508,-0.757417,-0.862610,89.099565
3,202408070801,2,181.8,15,0.220957,0.249084,-0.863773,-0.840073,0.810055,-0.325654,3,1,NaN,-0.711512,-0.820812,-0.622770,-1.111623,NaN,-0.907698,-0.854754,NaN,NaN,-0.465901,-0.430273,NaN,NaN,142.228938,143.207313,137.434494,142.857313,0.959687,0.868716,89.019233
0,202408070801,11,63.2,10,0.212687,0.192453,-0.193575,-0.531313,0.541739,-0.452020,2,1,NaN,-0.711512,-0.820812,-0.622770,0.853677,NaN,0.039444,0.012952,NaN,NaN,0.948545,0.924378,NaN,NaN,123.770907,139.748273,122.705584,139.733666,-1.457701,-0.277933,88.967953
13,202408070801,6,15.0,7,0.186475,0.230769,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.816886
2,202408070801,12,6.6,3,0.212687,0.204000,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.622770,0.853677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.654894
1,202408070801,3,100.9,12,0.214894,0.186813,-0.114544,-0.348094,0.674630,-0.308055,4,1,NaN,0.474342,0.843933,1.214442,-1.013358,NaN,-0.623272,-0.559823,NaN,NaN,-0.502298,-0.487683,NaN,NaN,138.465898,143.370004,133.197641,141.362879,0.466854,0.922647,88.609783
14,202408070801,14,12.4,6,0.198895,0.207373,0.795856,1.041556,1.188353,0.399302,2,1,NaN,-0.711512,-0.127168,0.142735,0.853677,NaN,1.093843,1.020721,NaN,NaN,1.369421,1.367752,NaN,NaN,132.391298,139.162879,132.391298,139.162879,-0.328717,-0.471987,88.114343
10,202408070801,4,23.0,9,0.214894,0.244526,0.229241,-0.042728,0.650000,-0.067763,3,1,NaN,0.474342,-0.358383,-0.112434,-1.111623,NaN,0.723435,0.888408,NaN,NaN,-1.116988,-1.197187,NaN,NaN,131.207048,138.550058,121.562727,137.337237,-0.483814,-0.675134,88.032058
7,202408070801,13,11.3,4,0.198895,0.192308,0.889244,0.812295,0.754871,-0.214062,3,1,NaN,-0.711512,1.676306,2.133049,-1.111623,NaN,0.058167,0.120859,NaN,NaN,-0.851438,-0.859499,NaN,NaN,133.331648,138.807183,123.937084,134.137237,-0.205562,-0.589899,87.896378
15,202408070801,5,5.1,2,0.186475,0.168498,1.507356,1.766485,2.646210,-0.305682,3,1,NaN,1.660196,1.676306,2.133049,-1.111623,NaN,0.738660,0.857396,NaN,NaN,-1.123066,-1.183543,NaN,NaN,143.311927,141.777128,143.311927,141.777128,1.101522,0.394619,87.422849
11,202408070801,7,2.3,1,0.190196,0.208029,0.810608,0.568003,0.893771,-0.037500,2,1,NaN,1.660196,0.393065,0.716864,0.853677,NaN,1.747349,1.605063,NaN,NaN,1.630276,1.624836,NaN,NaN,140.278477,139.050058,139.262727,136.637237,0.704241,-0.509387,87.252325

###　12/22 第7回目レース

In [13]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070807",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [14]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070807,2021102336,1174,1039,1,1,5.6,3,57.0,0,3,NaN,NaN,16,4.1875,3.0,4
1,202408070807,2021100410,1204,1171,2,1,47.1,14,51.0,1,3,NaN,NaN,16,4.1875,3.0,4
2,202408070807,2019105232,1187,1082,3,2,38.4,13,54.0,1,5,NaN,NaN,16,4.1875,3.0,4
3,202408070807,2020104206,1181,1073,4,2,36.8,12,58.0,2,4,NaN,NaN,16,4.1875,3.0,4
4,202408070807,2021105973,1195,1188,5,3,10.9,4,52.0,1,3,NaN,NaN,16,4.1875,3.0,4
5,202408070807,2020105881,1091,1072,6,3,84.3,16,58.0,0,4,NaN,NaN,16,4.1875,3.0,4
6,202408070807,2021107019,1125,1170,7,4,77.0,15,55.0,1,3,NaN,NaN,16,4.1875,3.0,4
7,202408070807,2021103842,1208,1065,8,4,3.3,1,56.0,0,3,NaN,NaN,16,4.1875,3.0,4
8,202408070807,2021105849,1197,1105,9,5,13.7,5,57.0,0,3,NaN,NaN,16,4.1875,3.0,4
9,202408070807,2021101057,1034,1078,10,5,16.6,6,57.0,0,3,NaN,NaN,16,4.1875,3.0,4
10,202408070807,2021106150,1193,1139,11,6,18.1,7,52.0,1,3,NaN,NaN,16,4.1875,3.0,4
11,202408070807,2017103656,1128,1188,12,6,30.5,11,58.0,2,7,NaN,NaN,16,4.1875,3.0,4
12,202408070807,2017104086,1212,431,13,7,30.0,10,53.0,1,7,NaN,NaN,16,4.1875,3.0,4
13,202408070807,2018103388,1144,1069,14,7,27.2,9,58.0,0,6,NaN,NaN,16,4.1875,3.0,4
14,202408070807,2021105862,1171,1154,15,8,4.0,2,57.0,0,3,NaN,NaN,16,4.1875,3.0,4
15,202408070807,2017103155,1185,1032,16,8,23.9,8,57.0,0,7,NaN,NaN,16,4.1875,3.0,4

In [15]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070807,0,0,1200,2,0,2,8,7,73875107,4,84,840,7,70,8,80,7,70,84080,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401200,-1,44,70,2.0

In [16]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
0,202408070807,7,77.0,15,0.182195,0.189189,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.987467,0.967642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.908332
9,202408070807,2,47.1,14,0.204225,0.209302,-0.753298,-0.083717,0.907245,-0.271726,4,1,NaN,-0.829830,-0.949196,-0.987467,-0.930185,NaN,-1.945098,-1.744539,NaN,NaN,-0.550877,-0.484271,NaN,NaN,132.406417,146.575186,125.328626,142.195192,-2.072090,-1.349227,73.764278
10,202408070807,4,36.8,12,0.200441,0.214008,-0.191450,-1.507211,1.661823,-0.037769,2,1,NaN,-0.829830,-0.330155,-0.529953,0.967642,NaN,0.381543,0.269518,NaN,NaN,0.994133,1.014249,NaN,NaN,166.331113,156.632741,162.810503,154.224209,0.555867,0.624235,73.554984
13,202408070807,3,38.4,13,0.200441,0.208494,-1.121551,-0.724067,1.000128,-0.167305,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.908947,-1.034089,NaN,NaN,0.717341,0.686108,NaN,NaN,169.197368,155.244330,166.978104,153.178257,0.777900,0.351806,73.343859
8,202408070807,6,84.3,16,0.206383,0.178295,-1.455184,-1.336301,0.600531,-0.488256,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.109425,-1.230846,NaN,NaN,0.888827,0.636581,NaN,NaN,148.734471,142.933789,141.480672,136.366493,-0.807247,-2.063730,73.308889
11,202408070807,13,30.0,10,0.217899,0.158590,-0.327719,-0.186827,1.309492,0.004550,4,1,NaN,0.301756,-0.949196,0.659582,-0.930185,NaN,-0.534689,-0.319794,NaN,NaN,-0.823138,-0.807042,NaN,NaN,147.136329,152.310693,144.329458,148.546912,-0.931046,-0.223824,73.184105
3,202408070807,11,18.1,7,0.186508,0.184739,-0.883106,-1.225299,1.632619,0.197576,3,1,NaN,1.433343,1.279351,1.117095,-1.030070,NaN,0.119034,0.358270,NaN,NaN,-1.061537,-1.072136,NaN,NaN,154.469981,148.694092,151.177170,145.061779,-0.362949,-0.933462,73.157938
14,202408070807,12,30.5,11,0.186508,0.232365,0.151245,0.447496,1.147805,-0.069000,4,1,NaN,-0.829830,1.279351,0.659582,-0.930185,NaN,-0.477664,-0.262189,NaN,NaN,-0.834146,-0.820092,NaN,NaN,164.785255,159.529818,152.951722,154.924209,0.436118,1.192691,73.086326
2,202408070807,14,27.2,9,0.217899,0.188679,-0.197239,0.088211,0.965732,-0.234697,3,1,NaN,-0.829830,-0.949196,-0.987467,-1.030070,NaN,-0.426531,-0.192840,NaN,NaN,-0.944522,-0.933412,NaN,NaN,157.663033,155.963152,154.810503,154.141272,-0.115601,0.492851,73.045007
4,202408070807,10,16.6,6,0.206827,0.244094,-0.412384,0.049692,0.789971,-0.119866,3,1,NaN,1.433343,1.279351,0.964591,-1.030070,NaN,-0.236225,-0.000600,NaN,NaN,-0.985339,-0.981802,NaN,NaN,173.321614,158.441272,134.928860,139.146314,1.097382,0.979100,72.993235
15,202408070807,5,10.9,4,0.206383,0.193798,0.070907,0.289215,1.454024,-0.044254,4,1,NaN,1.433343,1.279351,0.659582,-0.930185,NaN,0.723490,0.951174,NaN,NaN,-1.066013,-1.094975,NaN,NaN,137.678695,149.011699,132.629458,148.741272,-1.663676,-0.871142,72.966010
5,202408070807,16,23.9,8,0.209393,0.204819,0.465956,0.169454,2.224693,-0.126812,2,1,NaN,0.301756,-0.330155,-0.072440,0.967642,NaN,0.759951,0.651772,NaN,NaN,1.075296,1.110470,NaN,NaN,172.493340,159.085031,159.201425,154.761779,1.033220,1.105416,72.930332
6,202408070807,8,3.3,1,0.182195,0.192913,0.721767,0.145616,1.722992,-0.338385,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.309195,-0.428241,NaN,NaN,0.845979,0.838611,NaN,NaN,174.844896,156.475906,164.149532,153.778257,1.215382,0.593462,72.771401
12,202408070807,1,5.6,3,0.204225,0.210117,1.827726,1.285829,2.724178,0.165000,2,1,NaN,1.433343,0.288886,0.232569,0.967642,NaN,2.429577,2.338369,NaN,NaN,1.433407,1.535016,NaN,NaN,158.288547,150.653577,139.794006,140.166493,-0.067146,-0.548978,72.734308
1,202408070807,9,13.7,5,0.206827,0.226562,-0.088792,0.169454,1.034341,-0.117083,4,1,NaN,0.301756,1.279351,2.306630,-0.930185,NaN,-0.515478,-0.300388,NaN,NaN,-0.826846,-0.811438,NaN,NaN,165.843837,158.741272,152.363818,152.278257,0.518120,1.037965,72.710348
7,202408070807,15,4.0,2,0.209393,0.184615,2.193122,2.418457,1.441908,-0.134343,2,1,NaN,-0.829830,-0.330155,-0.072440,0.967642,NaN,1.049657,0.944423,NaN,NaN,1.137434,1.184135,NaN,NaN,164.135247,151.478257,162.649532,151.478257,0.385765,-0.387162,72.447382

In [17]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
0,202408070807,7,77.0,15,0.182195,0.189189,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.987467,0.967642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.971990
9,202408070807,2,47.1,14,0.204225,0.209302,-0.753298,-0.083717,0.907245,-0.271726,4,1,NaN,-0.829830,-0.949196,-0.987467,-0.930185,NaN,-1.945098,-1.744539,NaN,NaN,-0.550877,-0.484271,NaN,NaN,132.406417,146.575186,125.328626,142.195192,-2.072090,-1.349227,74.763169
8,202408070807,6,84.3,16,0.206383,0.178295,-1.455184,-1.336301,0.600531,-0.488256,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.109425,-1.230846,NaN,NaN,0.888827,0.636581,NaN,NaN,148.734471,142.933789,141.480672,136.366493,-0.807247,-2.063730,74.754397
13,202408070807,3,38.4,13,0.200441,0.208494,-1.121551,-0.724067,1.000128,-0.167305,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.908947,-1.034089,NaN,NaN,0.717341,0.686108,NaN,NaN,169.197368,155.244330,166.978104,153.178257,0.777900,0.351806,74.284443
11,202408070807,13,30.0,10,0.217899,0.158590,-0.327719,-0.186827,1.309492,0.004550,4,1,NaN,0.301756,-0.949196,0.659582,-0.930185,NaN,-0.534689,-0.319794,NaN,NaN,-0.823138,-0.807042,NaN,NaN,147.136329,152.310693,144.329458,148.546912,-0.931046,-0.223824,74.235744
10,202408070807,4,36.8,12,0.200441,0.214008,-0.191450,-1.507211,1.661823,-0.037769,2,1,NaN,-0.829830,-0.330155,-0.529953,0.967642,NaN,0.381543,0.269518,NaN,NaN,0.994133,1.014249,NaN,NaN,166.331113,156.632741,162.810503,154.224209,0.555867,0.624235,74.146581
3,202408070807,11,18.1,7,0.186508,0.184739,-0.883106,-1.225299,1.632619,0.197576,3,1,NaN,1.433343,1.279351,1.117095,-1.030070,NaN,0.119034,0.358270,NaN,NaN,-1.061537,-1.072136,NaN,NaN,154.469981,148.694092,151.177170,145.061779,-0.362949,-0.933462,73.807006
14,202408070807,12,30.5,11,0.186508,0.232365,0.151245,0.447496,1.147805,-0.069000,4,1,NaN,-0.829830,1.279351,0.659582,-0.930185,NaN,-0.477664,-0.262189,NaN,NaN,-0.834146,-0.820092,NaN,NaN,164.785255,159.529818,152.951722,154.924209,0.436118,1.192691,73.703751
6,202408070807,8,3.3,1,0.182195,0.192913,0.721767,0.145616,1.722992,-0.338385,2,1,NaN,-0.829830,-0.949196,-0.987467,0.967642,NaN,-0.309195,-0.428241,NaN,NaN,0.845979,0.838611,NaN,NaN,174.844896,156.475906,164.149532,153.778257,1.215382,0.593462,73.687071
4,202408070807,10,16.6,6,0.206827,0.244094,-0.412384,0.049692,0.789971,-0.119866,3,1,NaN,1.433343,1.279351,0.964591,-1.030070,NaN,-0.236225,-0.000600,NaN,NaN,-0.985339,-0.981802,NaN,NaN,173.321614,158.441272,134.928860,139.146314,1.097382,0.979100,73.679316
2,202408070807,14,27.2,9,0.217899,0.188679,-0.197239,0.088211,0.965732,-0.234697,3,1,NaN,-0.829830,-0.949196,-0.987467,-1.030070,NaN,-0.426531,-0.192840,NaN,NaN,-0.944522,-0.933412,NaN,NaN,157.663033,155.963152,154.810503,154.141272,-0.115601,0.492851,73.658491
5,202408070807,16,23.9,8,0.209393,0.204819,0.465956,0.169454,2.224693,-0.126812,2,1,NaN,0.301756,-0.330155,-0.072440,0.967642,NaN,0.759951,0.651772,NaN,NaN,1.075296,1.110470,NaN,NaN,172.493340,159.085031,159.201425,154.761779,1.033220,1.105416,73.646875
1,202408070807,9,13.7,5,0.206827,0.226562,-0.088792,0.169454,1.034341,-0.117083,4,1,NaN,0.301756,1.279351,2.306630,-0.930185,NaN,-0.515478,-0.300388,NaN,NaN,-0.826846,-0.811438,NaN,NaN,165.843837,158.741272,152.363818,152.278257,0.518120,1.037965,73.575474
12,202408070807,1,5.6,3,0.204225,0.210117,1.827726,1.285829,2.724178,0.165000,2,1,NaN,1.433343,0.288886,0.232569,0.967642,NaN,2.429577,2.338369,NaN,NaN,1.433407,1.535016,NaN,NaN,158.288547,150.653577,139.794006,140.166493,-0.067146,-0.548978,73.452670
7,202408070807,15,4.0,2,0.209393,0.184615,2.193122,2.418457,1.441908,-0.134343,2,1,NaN,-0.829830,-0.330155,-0.072440,0.967642,NaN,1.049657,0.944423,NaN,NaN,1.137434,1.184135,NaN,NaN,164.135247,151.478257,162.649532,151.478257,0.385765,-0.387162,73.236205
15,202408070807,5,10.9,4,0.206383,0.193798,0.070907,0.289215,1.454024,-0.044254,4,1,NaN,1.433343,1.279351,0.659582,-0.930185,NaN,0.723490,0.951174,NaN,NaN,-1.066013,-1.094975,NaN,NaN,137.678695,149.011699,132.629458,148.741272,-1.663676,-0.871142,73.188909

### 12/22 第8回目レース

In [18]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070808",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [19]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070808,2019103556,1142,1128,1,1,26.7,11,58.0,0,5,NaN,NaN,16,4.0625,4.0,4
1,202408070808,2021106191,1204,1018,2,1,23.4,10,51.0,1,3,NaN,NaN,16,4.0625,4.0,4
2,202408070808,2020102468,1015,1008,3,2,17.7,8,58.0,0,4,NaN,NaN,16,4.0625,4.0,4
3,202408070808,2021100639,1095,1180,4,2,14.6,6,57.0,2,3,NaN,NaN,16,4.0625,4.0,4
4,202408070808,2020104893,1171,1148,5,3,3.3,1,58.0,0,4,NaN,NaN,16,4.0625,4.0,4
5,202408070808,2020102687,1180,1183,6,3,17.5,7,58.0,0,4,NaN,NaN,16,4.0625,4.0,4
6,202408070808,2021103073,1174,1129,7,4,5.1,2,57.0,0,3,NaN,NaN,16,4.0625,4.0,4
7,202408070808,2021105598,1115,1002,8,4,9.6,4,57.0,0,3,NaN,NaN,16,4.0625,4.0,4
8,202408070808,2019102202,1178,1101,9,5,45.9,13,58.0,0,5,NaN,NaN,16,4.0625,4.0,4
9,202408070808,2020105929,1186,1140,10,5,35.1,12,56.0,1,4,NaN,NaN,16,4.0625,4.0,4
10,202408070808,2019106932,1216,1193,11,6,82.9,16,56.0,0,5,NaN,NaN,16,4.0625,4.0,4
11,202408070808,2019106028,1147,1146,12,6,63.3,15,56.0,1,5,NaN,NaN,16,4.0625,4.0,4
12,202408070808,2020103325,1176,1148,13,7,12.9,5,58.0,0,4,NaN,NaN,16,4.0625,4.0,4
13,202408070808,2020100673,1181,1078,14,7,19.4,9,58.0,0,4,NaN,NaN,16,4.0625,4.0,4
14,202408070808,2021105775,1160,1061,15,8,5.8,3,55.0,1,3,NaN,NaN,16,4.0625,4.0,4
15,202408070808,2018100421,1212,1066,16,8,61.6,14,53.0,1,6,NaN,NaN,16,4.0625,4.0,4

In [20]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070808,0,0,1400,2,0,3,8,8,73875108,4,84,840,8,80,8,80,7,70,84080,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401400,-1,44,79,2.9

In [21]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
12,202408070808,13,12.9,5,0.198895,0.192308,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-1.048139,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.705144
3,202408070808,1,26.7,11,0.220957,0.215328,-0.631881,-0.199711,1.116512,-0.231396,2,1,NaN,-0.258199,-0.829515,-0.744000,1.097334,NaN,-0.636581,-0.912451,NaN,NaN,0.958966,0.928625,NaN,NaN,179.759387,166.380816,162.600107,156.461779,1.195461,0.406155,86.384651
2,202408070808,2,23.4,10,0.220957,0.249084,-2.312935,-1.682392,0.837128,-0.103670,2,1,NaN,-1.169489,-0.829515,-1.048139,1.097334,NaN,-1.736976,-2.221232,NaN,NaN,0.705585,0.610254,NaN,NaN,172.518723,158.638512,141.490050,143.357313,0.183144,-0.872064,86.024057
5,202408070808,9,45.9,13,0.209524,0.186131,-0.497957,0.233640,0.877749,-0.049298,3,1,NaN,-0.258199,-0.829515,-0.744000,-0.875401,NaN,-1.036370,-0.793744,NaN,NaN,-0.582530,-0.591262,NaN,NaN,164.988196,167.000340,158.399619,152.380571,-0.869698,0.508436,85.754650
1,202408070808,11,82.9,16,0.212687,0.192453,-0.133373,0.424091,1.872438,0.083708,4,1,NaN,-1.169489,-0.829515,-1.048139,-0.776764,NaN,-0.597132,-0.061235,NaN,NaN,-0.589695,-0.669636,NaN,NaN,182.062745,177.125016,168.949915,165.059464,1.517493,2.179974,85.654033
4,202408070808,10,35.1,12,0.209524,0.223048,0.180032,0.272964,2.090005,0.053989,3,1,NaN,-0.258199,-0.829515,0.046761,-0.875401,NaN,-0.742341,-0.619331,NaN,NaN,-0.650234,-0.633689,NaN,NaN,173.323920,165.241675,151.867080,153.061779,0.295718,0.218088,85.624756
10,202408070808,14,19.4,9,0.198895,0.207373,0.688031,0.753090,2.517362,0.422724,2,1,NaN,-0.258199,-0.829515,-0.744000,1.097334,NaN,1.063972,1.820749,NaN,NaN,1.350543,1.593497,NaN,NaN,170.783377,172.778180,156.729458,152.946912,-0.059475,1.462331,85.498823
9,202408070808,6,17.5,7,0.186475,0.230769,-1.779462,-2.807080,1.087677,0.203410,3,1,NaN,-0.258199,1.111119,0.375232,-0.875401,NaN,-1.130360,-0.908930,NaN,NaN,-0.560888,-0.563242,NaN,NaN,181.666791,167.947820,155.541144,164.706876,1.462135,0.664860,85.482552
14,202408070808,16,61.6,14,0.196330,0.182927,0.708567,0.577114,2.420773,0.235856,4,1,NaN,-0.258199,0.663280,1.141662,-0.776764,NaN,0.193397,-0.007103,NaN,NaN,-0.753523,-0.681487,NaN,NaN,162.650630,157.408434,146.802346,149.078257,-1.196513,-1.075144,85.462511
11,202408070808,12,63.3,15,0.212687,0.204000,0.262353,0.350423,1.636412,0.405770,3,1,NaN,-1.169489,1.608717,0.740198,-0.875401,NaN,-0.391914,0.180733,NaN,NaN,-0.730925,-0.828311,NaN,NaN,169.488088,160.259669,167.563866,154.906876,-0.240569,-0.604418,85.433870
8,202408070808,3,17.7,8,0.214894,0.186813,0.936249,0.690463,1.949365,-0.229572,3,1,NaN,-0.258199,0.663280,0.655039,-0.875401,NaN,0.190975,0.140639,NaN,NaN,-0.865144,-0.818558,NaN,NaN,165.686684,157.796232,148.037738,152.233001,-0.772043,-1.011121,85.326294
7,202408070808,8,9.6,4,0.190196,0.172794,0.179087,-0.130893,2.098380,0.606510,2,1,NaN,0.653091,-0.829515,-1.048139,1.097334,NaN,0.362917,0.268759,NaN,NaN,1.189115,1.215963,NaN,NaN,169.999005,163.532365,162.491286,157.245192,-0.169138,-0.064111,85.300849
0,202408070808,4,14.6,6,0.214894,0.244526,-0.085461,-0.178522,1.755726,0.551754,2,1,NaN,2.475672,-0.138406,0.391452,1.097334,NaN,1.701023,0.379433,NaN,NaN,1.497233,1.242886,NaN,NaN,159.634899,154.216004,135.680672,144.875371,-1.618142,-1.602200,85.241535
13,202408070808,7,5.1,2,0.190196,0.208029,0.788706,0.272964,3.201411,0.875120,3,1,NaN,0.653091,1.202345,1.739802,-0.875401,NaN,1.322026,1.347622,NaN,NaN,-1.125585,-1.112166,NaN,NaN,175.323190,163.685390,155.295401,148.859503,0.575236,-0.038847,85.150890
15,202408070808,15,5.8,3,0.196330,0.172589,1.466459,1.101858,2.533729,0.552013,2,1,NaN,-0.030376,-0.829515,-0.439861,1.097334,NaN,0.442266,0.571543,NaN,NaN,1.207386,1.289618,NaN,NaN,177.521320,165.764055,153.678625,149.545192,0.882557,0.304331,85.144515
6,202408070808,5,3.3,1,0.186475,0.168498,0.231587,0.321992,2.799418,0.310500,3,1,NaN,1.564382,1.525784,1.774271,-0.875401,NaN,0.995098,0.814548,NaN,NaN,-1.050305,-0.982491,NaN,NaN,162.724654,161.035883,146.606675,153.378257,-1.186164,-0.476269,84.953540

In [22]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
3,202408070808,1,26.7,11,0.220957,0.215328,-0.631881,-0.199711,1.116512,-0.231396,2,1,NaN,-0.258199,-0.829515,-0.744000,1.097334,NaN,-0.636581,-0.912451,NaN,NaN,0.958966,0.928625,NaN,NaN,179.759387,166.380816,162.600107,156.461779,1.195461,0.406155,87.376590
12,202408070808,13,12.9,5,0.198895,0.192308,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-1.048139,1.097334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.226571
2,202408070808,2,23.4,10,0.220957,0.249084,-2.312935,-1.682392,0.837128,-0.103670,2,1,NaN,-1.169489,-0.829515,-1.048139,1.097334,NaN,-1.736976,-2.221232,NaN,NaN,0.705585,0.610254,NaN,NaN,172.518723,158.638512,141.490050,143.357313,0.183144,-0.872064,86.970075
5,202408070808,9,45.9,13,0.209524,0.186131,-0.497957,0.233640,0.877749,-0.049298,3,1,NaN,-0.258199,-0.829515,-0.744000,-0.875401,NaN,-1.036370,-0.793744,NaN,NaN,-0.582530,-0.591262,NaN,NaN,164.988196,167.000340,158.399619,152.380571,-0.869698,0.508436,86.790883
4,202408070808,10,35.1,12,0.209524,0.223048,0.180032,0.272964,2.090005,0.053989,3,1,NaN,-0.258199,-0.829515,0.046761,-0.875401,NaN,-0.742341,-0.619331,NaN,NaN,-0.650234,-0.633689,NaN,NaN,173.323920,165.241675,151.867080,153.061779,0.295718,0.218088,86.624613
14,202408070808,16,61.6,14,0.196330,0.182927,0.708567,0.577114,2.420773,0.235856,4,1,NaN,-0.258199,0.663280,1.141662,-0.776764,NaN,0.193397,-0.007103,NaN,NaN,-0.753523,-0.681487,NaN,NaN,162.650630,157.408434,146.802346,149.078257,-1.196513,-1.075144,86.547686
11,202408070808,12,63.3,15,0.212687,0.204000,0.262353,0.350423,1.636412,0.405770,3,1,NaN,-1.169489,1.608717,0.740198,-0.875401,NaN,-0.391914,0.180733,NaN,NaN,-0.730925,-0.828311,NaN,NaN,169.488088,160.259669,167.563866,154.906876,-0.240569,-0.604418,86.491107
8,202408070808,3,17.7,8,0.214894,0.186813,0.936249,0.690463,1.949365,-0.229572,3,1,NaN,-0.258199,0.663280,0.655039,-0.875401,NaN,0.190975,0.140639,NaN,NaN,-0.865144,-0.818558,NaN,NaN,165.686684,157.796232,148.037738,152.233001,-0.772043,-1.011121,86.431786
1,202408070808,11,82.9,16,0.212687,0.192453,-0.133373,0.424091,1.872438,0.083708,4,1,NaN,-1.169489,-0.829515,-1.048139,-0.776764,NaN,-0.597132,-0.061235,NaN,NaN,-0.589695,-0.669636,NaN,NaN,182.062745,177.125016,168.949915,165.059464,1.517493,2.179974,86.381527
10,202408070808,14,19.4,9,0.198895,0.207373,0.688031,0.753090,2.517362,0.422724,2,1,NaN,-0.258199,-0.829515,-0.744000,1.097334,NaN,1.063972,1.820749,NaN,NaN,1.350543,1.593497,NaN,NaN,170.783377,172.778180,156.729458,152.946912,-0.059475,1.462331,86.206379
7,202408070808,8,9.6,4,0.190196,0.172794,0.179087,-0.130893,2.098380,0.606510,2,1,NaN,0.653091,-0.829515,-1.048139,1.097334,NaN,0.362917,0.268759,NaN,NaN,1.189115,1.215963,NaN,NaN,169.999005,163.532365,162.491286,157.245192,-0.169138,-0.064111,86.141598
9,202408070808,6,17.5,7,0.186475,0.230769,-1.779462,-2.807080,1.087677,0.203410,3,1,NaN,-0.258199,1.111119,0.375232,-0.875401,NaN,-1.130360,-0.908930,NaN,NaN,-0.560888,-0.563242,NaN,NaN,181.666791,167.947820,155.541144,164.706876,1.462135,0.664860,86.107599
0,202408070808,4,14.6,6,0.214894,0.244526,-0.085461,-0.178522,1.755726,0.551754,2,1,NaN,2.475672,-0.138406,0.391452,1.097334,NaN,1.701023,0.379433,NaN,NaN,1.497233,1.242886,NaN,NaN,159.634899,154.216004,135.680672,144.875371,-1.618142,-1.602200,86.078950
15,202408070808,15,5.8,3,0.196330,0.172589,1.466459,1.101858,2.533729,0.552013,2,1,NaN,-0.030376,-0.829515,-0.439861,1.097334,NaN,0.442266,0.571543,NaN,NaN,1.207386,1.289618,NaN,NaN,177.521320,165.764055,153.678625,149.545192,0.882557,0.304331,85.880847
6,202408070808,5,3.3,1,0.186475,0.168498,0.231587,0.321992,2.799418,0.310500,3,1,NaN,1.564382,1.525784,1.774271,-0.875401,NaN,0.995098,0.814548,NaN,NaN,-1.050305,-0.982491,NaN,NaN,162.724654,161.035883,146.606675,153.378257,-1.186164,-0.476269,85.692581
13,202408070808,7,5.1,2,0.190196,0.208029,0.788706,0.272964,3.201411,0.875120,3,1,NaN,0.653091,1.202345,1.739802,-0.875401,NaN,1.322026,1.347622,NaN,NaN,-1.125585,-1.112166,NaN,NaN,175.323190,163.685390,155.295401,148.859503,0.575236,-0.038847,85.461754

### 12/22 第9回目レース

In [23]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070809",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [24]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070809,2020101537,1197,1157,1,1,29.0,11,58.0,0,4,NaN,NaN,16,4.25,4.0,4
1,202408070809,2020100771,1099,1198,2,1,8.0,5,58.0,2,4,NaN,NaN,16,4.25,4.0,4
2,202408070809,2020103463,1171,399,3,2,7.6,3,58.0,0,4,NaN,NaN,16,4.25,4.0,4
3,202408070809,2017103184,1091,1041,4,2,14.6,6,58.0,2,7,NaN,NaN,16,4.25,4.0,4
4,202408070809,2020102724,1144,1160,5,3,25.2,9,58.0,0,4,NaN,NaN,16,4.25,4.0,4
5,202408070809,2021101554,1212,1039,6,3,49.7,15,57.0,0,3,NaN,NaN,16,4.25,4.0,4
6,202408070809,2021104992,1185,1123,7,4,29.6,12,57.0,2,3,NaN,NaN,16,4.25,4.0,4
7,202408070809,2020106399,1213,1166,8,4,22.2,8,58.0,0,4,NaN,NaN,16,4.25,4.0,4
8,202408070809,2020100665,1174,1110,9,5,7.9,4,58.0,0,4,NaN,NaN,16,4.25,4.0,4
9,202408070809,2018100390,1208,1072,10,5,17.5,7,58.0,0,6,NaN,NaN,16,4.25,4.0,4
10,202408070809,2018100961,1114,431,11,6,47.7,14,58.0,0,6,NaN,NaN,16,4.25,4.0,4
11,202408070809,2021106612,5212,1160,12,6,6.1,2,57.0,0,3,NaN,NaN,16,4.25,4.0,4
12,202408070809,2021105272,1075,1127,13,7,3.1,1,57.0,0,3,NaN,NaN,16,4.25,4.0,4
13,202408070809,2020104215,1176,1107,14,7,28.2,10,58.0,2,4,NaN,NaN,16,4.25,4.0,4
14,202408070809,2019102694,1015,1032,15,8,141.1,16,58.0,2,5,NaN,NaN,16,4.25,4.0,4
15,202408070809,2020110151,1180,1098,16,8,32.3,13,58.0,0,4,NaN,NaN,16,4.25,4.0,4

In [25]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070809,0,0,1800,2,0,3,8,9,73875109,4,84,840,9,90,8,80,7,70,84080,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401800,-1,44,79,2.9

In [26]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
13,202408070809,15,141.1,16,0.212471,0.207373,-1.857384,-1.242487,0.486474,-0.248237,4,1,NaN,-0.843692,-0.945510,-0.710726,-1.181660,NaN,-2.063147,-2.216563,NaN,NaN,-0.838237,-0.668930,NaN,NaN,140.397994,148.131862,123.947339,142.475371,-2.309869,-1.786685,115.854302
11,202408070809,7,29.6,12,0.238482,0.252273,0.225967,-0.851356,1.648640,0.055705,2,1,NaN,0.804450,-0.268130,-0.466888,0.749656,NaN,-0.215734,-0.645876,NaN,NaN,0.574074,0.412004,NaN,NaN,173.115843,162.488631,164.441604,153.976987,0.516899,-0.204968,115.076358
15,202408070809,1,29.0,11,0.238487,0.243243,-1.668584,-1.539665,0.623181,0.614861,2,1,NaN,-0.843692,-0.945510,-0.710726,0.749656,NaN,-1.092214,-1.050626,NaN,NaN,0.354954,0.286129,NaN,NaN,166.822730,160.803683,166.822730,160.803683,-0.026816,-0.390602,114.998500
5,202408070809,3,7.6,3,0.232170,0.197309,-0.322813,-0.271490,2.584421,0.394272,2,1,NaN,NaN,1.267266,1.548837,0.749656,NaN,0.641211,0.893708,NaN,NaN,0.788309,0.890807,NaN,NaN,161.344703,171.236176,161.344703,171.236176,-0.500108,0.758769,114.945738
4,202408070809,14,28.2,10,0.216825,0.166008,1.028999,1.352127,2.581337,0.071905,3,1,NaN,-0.843692,-0.268130,-0.223051,-1.283309,NaN,0.668242,0.294258,NaN,NaN,-1.583494,-1.485725,NaN,NaN,167.189916,156.093297,148.102580,154.539644,0.004908,-0.909556,114.936818
1,202408070809,16,32.3,13,0.212471,0.164634,-0.748483,-0.865929,1.084385,0.147924,3,1,NaN,-0.184435,1.493059,0.167090,-1.283309,NaN,-0.575083,-0.618709,NaN,NaN,-1.272664,-1.201797,NaN,NaN,174.975284,166.844266,156.002580,151.739644,0.677551,0.274902,114.440501
9,202408070809,11,47.7,14,0.215517,0.192412,-0.296172,-0.304639,0.686592,-0.098533,4,1,NaN,-0.843692,-0.945510,-0.710726,-1.181660,NaN,-1.249129,-0.950436,NaN,NaN,-1.021391,-1.023314,NaN,NaN,165.722730,159.703683,119.577656,147.429508,-0.121854,-0.511792,114.394057
8,202408070809,2,8.0,5,0.238487,0.262443,0.224947,0.024701,2.786449,1.306667,2,1,NaN,1.134079,-0.268130,-0.223051,0.749656,NaN,0.775960,0.353884,NaN,NaN,0.821996,0.722924,NaN,NaN,171.655174,154.080571,171.655174,154.080571,0.390699,-1.131302,114.347079
14,202408070809,8,22.2,8,0.238482,0.243182,-0.052776,0.616103,2.941809,-0.236136,2,1,NaN,-0.019621,0.409251,-0.223051,0.749656,NaN,0.371930,-0.043362,NaN,NaN,0.720989,0.599383,NaN,NaN,142.820835,153.576987,142.820835,153.576987,-2.100539,-1.186783,114.243990
3,202408070809,5,25.2,9,0.216954,0.240363,-0.914557,-0.791637,1.238032,0.070145,3,1,NaN,0.804450,-0.945510,-0.710726,-1.283309,NaN,-1.224245,-0.739543,NaN,NaN,-1.110374,-1.164218,NaN,NaN,178.173978,178.263463,178.173978,178.263463,0.953913,1.532981,114.162836
6,202408070809,10,17.5,7,0.220102,0.180693,0.461133,0.658100,1.814813,0.043245,2,1,NaN,-0.184435,-0.945510,-0.710726,0.749656,NaN,0.451850,0.922573,NaN,NaN,0.740969,0.899784,NaN,NaN,177.149333,176.929332,163.771308,172.288763,0.865385,1.385996,113.968074
0,202408070809,6,49.7,15,0.216954,0.239278,0.235278,0.196384,1.233701,-0.213106,2,1,NaN,NaN,-0.945510,-0.548168,0.749656,NaN,0.335097,-0.160586,NaN,NaN,0.711781,0.562927,NaN,NaN,176.262867,175.463463,150.525674,140.951071,0.788796,1.224498,113.813901
12,202408070809,4,14.6,6,0.232170,0.269841,0.333736,0.228769,1.170493,-0.295303,3,1,NaN,-0.843692,1.267266,0.085811,-1.283309,NaN,0.296621,0.814003,NaN,NaN,-1.490589,-1.647364,NaN,NaN,164.393048,164.596223,156.011370,159.703683,-0.236736,0.027230,113.772644
7,202408070809,9,7.9,4,0.220102,0.240566,0.439795,0.189372,2.150123,0.155417,2,1,NaN,-0.843692,-0.064916,-0.076748,0.749656,NaN,0.139851,0.308983,NaN,NaN,0.662970,0.708960,NaN,NaN,171.843432,167.914716,156.033841,158.903683,0.406964,0.392836,113.714032
2,202408070809,12,6.1,2,0.215517,0.175439,0.679380,0.146434,3.095425,0.673542,2,1,NaN,2.452593,1.944646,0.492207,0.749656,NaN,1.782615,1.249650,NaN,NaN,1.073659,1.001503,NaN,NaN,161.564323,159.932875,151.441184,143.751071,-0.481133,-0.486541,113.488345
10,202408070809,13,3.1,1,0.216825,0.197324,2.231533,2.455213,2.628466,0.878399,2,1,NaN,0.255070,0.160878,3.020642,0.749656,NaN,0.956175,1.588642,NaN,NaN,0.867050,1.106928,NaN,NaN,180.697467,173.525750,159.928626,147.795192,1.171938,1.011016,113.186063

In [27]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
4,202408070809,14,28.2,10,0.216825,0.166008,1.028999,1.352127,2.581337,0.071905,3,1,NaN,-0.843692,-0.268130,-0.223051,-1.283309,NaN,0.668242,0.294258,NaN,NaN,-1.583494,-1.485725,NaN,NaN,167.189916,156.093297,148.102580,154.539644,0.004908,-0.909556,118.374563
11,202408070809,7,29.6,12,0.238482,0.252273,0.225967,-0.851356,1.648640,0.055705,2,1,NaN,0.804450,-0.268130,-0.466888,0.749656,NaN,-0.215734,-0.645876,NaN,NaN,0.574074,0.412004,NaN,NaN,173.115843,162.488631,164.441604,153.976987,0.516899,-0.204968,115.710818
14,202408070809,8,22.2,8,0.238482,0.243182,-0.052776,0.616103,2.941809,-0.236136,2,1,NaN,-0.019621,0.409251,-0.223051,0.749656,NaN,0.371930,-0.043362,NaN,NaN,0.720989,0.599383,NaN,NaN,142.820835,153.576987,142.820835,153.576987,-2.100539,-1.186783,115.648272
15,202408070809,1,29.0,11,0.238487,0.243243,-1.668584,-1.539665,0.623181,0.614861,2,1,NaN,-0.843692,-0.945510,-0.710726,0.749656,NaN,-1.092214,-1.050626,NaN,NaN,0.354954,0.286129,NaN,NaN,166.822730,160.803683,166.822730,160.803683,-0.026816,-0.390602,115.500991
9,202408070809,11,47.7,14,0.215517,0.192412,-0.296172,-0.304639,0.686592,-0.098533,4,1,NaN,-0.843692,-0.945510,-0.710726,-1.181660,NaN,-1.249129,-0.950436,NaN,NaN,-1.021391,-1.023314,NaN,NaN,165.722730,159.703683,119.577656,147.429508,-0.121854,-0.511792,115.153787
3,202408070809,5,25.2,9,0.216954,0.240363,-0.914557,-0.791637,1.238032,0.070145,3,1,NaN,0.804450,-0.945510,-0.710726,-1.283309,NaN,-1.224245,-0.739543,NaN,NaN,-1.110374,-1.164218,NaN,NaN,178.173978,178.263463,178.173978,178.263463,0.953913,1.532981,115.117372
13,202408070809,15,141.1,16,0.212471,0.207373,-1.857384,-1.242487,0.486474,-0.248237,4,1,NaN,-0.843692,-0.945510,-0.710726,-1.181660,NaN,-2.063147,-2.216563,NaN,NaN,-0.838237,-0.668930,NaN,NaN,140.397994,148.131862,123.947339,142.475371,-2.309869,-1.786685,115.088722
1,202408070809,16,32.3,13,0.212471,0.164634,-0.748483,-0.865929,1.084385,0.147924,3,1,NaN,-0.184435,1.493059,0.167090,-1.283309,NaN,-0.575083,-0.618709,NaN,NaN,-1.272664,-1.201797,NaN,NaN,174.975284,166.844266,156.002580,151.739644,0.677551,0.274902,114.878889
8,202408070809,2,8.0,5,0.238487,0.262443,0.224947,0.024701,2.786449,1.306667,2,1,NaN,1.134079,-0.268130,-0.223051,0.749656,NaN,0.775960,0.353884,NaN,NaN,0.821996,0.722924,NaN,NaN,171.655174,154.080571,171.655174,154.080571,0.390699,-1.131302,114.860206
5,202408070809,3,7.6,3,0.232170,0.197309,-0.322813,-0.271490,2.584421,0.394272,2,1,NaN,NaN,1.267266,1.548837,0.749656,NaN,0.641211,0.893708,NaN,NaN,0.788309,0.890807,NaN,NaN,161.344703,171.236176,161.344703,171.236176,-0.500108,0.758769,114.852564
6,202408070809,10,17.5,7,0.220102,0.180693,0.461133,0.658100,1.814813,0.043245,2,1,NaN,-0.184435,-0.945510,-0.710726,0.749656,NaN,0.451850,0.922573,NaN,NaN,0.740969,0.899784,NaN,NaN,177.149333,176.929332,163.771308,172.288763,0.865385,1.385996,114.564497
7,202408070809,9,7.9,4,0.220102,0.240566,0.439795,0.189372,2.150123,0.155417,2,1,NaN,-0.843692,-0.064916,-0.076748,0.749656,NaN,0.139851,0.308983,NaN,NaN,0.662970,0.708960,NaN,NaN,171.843432,167.914716,156.033841,158.903683,0.406964,0.392836,114.381446
12,202408070809,4,14.6,6,0.232170,0.269841,0.333736,0.228769,1.170493,-0.295303,3,1,NaN,-0.843692,1.267266,0.085811,-1.283309,NaN,0.296621,0.814003,NaN,NaN,-1.490589,-1.647364,NaN,NaN,164.393048,164.596223,156.011370,159.703683,-0.236736,0.027230,114.245434
0,202408070809,6,49.7,15,0.216954,0.239278,0.235278,0.196384,1.233701,-0.213106,2,1,NaN,NaN,-0.945510,-0.548168,0.749656,NaN,0.335097,-0.160586,NaN,NaN,0.711781,0.562927,NaN,NaN,176.262867,175.463463,150.525674,140.951071,0.788796,1.224498,114.224365
2,202408070809,12,6.1,2,0.215517,0.175439,0.679380,0.146434,3.095425,0.673542,2,1,NaN,2.452593,1.944646,0.492207,0.749656,NaN,1.782615,1.249650,NaN,NaN,1.073659,1.001503,NaN,NaN,161.564323,159.932875,151.441184,143.751071,-0.481133,-0.486541,114.039801
10,202408070809,13,3.1,1,0.216825,0.197324,2.231533,2.455213,2.628466,0.878399,2,1,NaN,0.255070,0.160878,3.020642,0.749656,NaN,0.956175,1.588642,NaN,NaN,0.867050,1.106928,NaN,NaN,180.697467,173.525750,159.928626,147.795192,1.171938,1.011016,113.462032

### 12/22 第11回目レース

In [29]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202408070811",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [30]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202408070811,2020106756,1184,1108,1,1,11.6,4,57.0,0,4,NaN,NaN,16,4.25,4.0,4
1,202408070811,2021100768,5212,1039,2,1,13.1,7,54.0,1,3,NaN,NaN,16,4.25,4.0,4
2,202408070811,2019105859,1093,1161,3,2,7.0,2,57.0,0,5,NaN,NaN,16,4.25,4.0,4
3,202408070811,2020101292,1171,1087,4,2,16.6,8,57.0,0,4,NaN,NaN,16,4.25,4.0,4
4,202408070811,2020100168,1142,1142,5,3,18.4,9,57.0,0,4,NaN,NaN,16,4.25,4.0,4
5,202408070811,2020103892,1197,1124,6,3,37.8,13,55.0,1,4,NaN,NaN,16,4.25,4.0,4
6,202408070811,2020105622,1102,1138,7,4,7.2,3,57.0,0,4,NaN,NaN,16,4.25,4.0,4
7,202408070811,2021104991,1091,1170,8,4,2.8,1,56.0,0,3,NaN,NaN,16,4.25,4.0,4
8,202408070811,2019101894,1174,1120,9,5,42.1,14,57.0,2,5,NaN,NaN,16,4.25,4.0,4
9,202408070811,2019102576,1181,1129,10,5,88.4,16,57.0,0,5,NaN,NaN,16,4.25,4.0,4
10,202408070811,2020106006,1144,1128,11,6,12.7,6,57.0,0,4,NaN,NaN,16,4.25,4.0,4
11,202408070811,2020104429,1182,1157,12,6,11.8,5,55.0,1,4,NaN,NaN,16,4.25,4.0,4
12,202408070811,2019104841,1128,1203,13,7,43.4,15,56.0,1,5,NaN,NaN,16,4.25,4.0,4
13,202408070811,2019110105,1180,427,14,7,35.1,12,59.0,0,5,NaN,NaN,16,4.25,4.0,4
14,202408070811,2019106293,1216,1110,15,8,29.6,10,57.0,0,5,NaN,NaN,16,4.25,4.0,4
15,202408070811,2020101633,1208,1120,16,8,31.1,11,55.0,1,4,NaN,NaN,16,4.25,4.0,4

In [31]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202408070811,0,0,1200,2,0,5,8,11,73875111,4,84,840,11,110,8,80,7,70,84080,2,8420,-1,-1,-1,-1,-1,-1,NaN,8401200,-1,44,89,3.9

In [32]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
4,202408070811,10,88.4,16,0.206827,0.244094,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-1.416236,0.749788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.306375
5,202408070811,14,35.1,12,0.217899,0.188679,NaN,NaN,NaN,2.112085,2,1,NaN,1.632993,-1.035615,0.651518,0.749788,NaN,-0.169602,-0.053680,NaN,NaN,0.631552,0.686106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.988672
14,202408070811,9,42.1,14,0.206827,0.226562,-1.383303,-1.312309,2.522484,0.500320,3,1,NaN,-0.816497,0.615130,0.835319,-1.266449,NaN,-1.130024,-1.078577,NaN,NaN,-1.120618,-1.101136,NaN,NaN,176.942310,172.779953,169.931461,170.329500,-1.048136,0.542175,72.692941
8,202408070811,16,31.1,11,0.209393,0.204819,-1.685883,-2.838947,3.129170,0.469285,2,1,NaN,0.408248,-0.193398,-0.592964,0.749788,NaN,-0.424778,-0.879289,NaN,NaN,0.579053,0.530848,NaN,NaN,185.585628,168.941616,177.235294,166.110128,0.344885,-0.433261,72.661438
6,202408070811,2,13.1,7,0.204225,0.209302,-0.484217,0.152622,3.842792,1.388956,2,1,NaN,1.020621,-0.249546,-0.688693,0.749788,NaN,0.779472,0.461621,NaN,NaN,0.826813,0.783009,NaN,NaN,178.945524,160.077576,169.133746,151.661779,-0.725283,-2.685878,72.531053
3,202408070811,13,43.4,15,0.217899,0.158590,-0.944592,0.229521,2.915105,1.035016,2,1,NaN,-1.428869,-1.035615,-1.416236,0.749788,NaN,-0.481149,-0.690255,NaN,NaN,0.567455,0.566396,NaN,NaN,190.360745,171.924847,190.360745,171.924847,1.114477,0.324868,72.221127
12,202408070811,15,29.6,10,0.209393,0.184615,-0.250633,-0.328382,3.952546,1.235542,3,1,NaN,-0.816497,1.073671,0.022257,-1.266449,NaN,0.250039,0.853163,NaN,NaN,-1.404550,-1.464405,NaN,NaN,183.120088,174.513287,178.068059,172.529500,-0.052480,0.982667,72.182511
0,202408070811,12,11.8,5,0.186508,0.232365,0.143293,0.448400,3.871493,2.102083,2,1,NaN,-0.204124,-0.155966,-0.816332,0.749788,NaN,1.631775,1.938802,NaN,NaN,1.002165,1.060797,NaN,NaN,183.425303,171.642756,178.028387,169.900000,-0.003289,0.253180,72.175310
15,202408070811,5,18.4,9,0.206383,0.193798,0.908539,0.322505,2.223422,0.570771,3,1,NaN,-0.204124,-1.035615,-0.233021,-1.266449,NaN,-1.344051,-1.378162,NaN,NaN,-1.076585,-1.044799,NaN,NaN,187.651035,172.307382,176.446025,168.465255,0.677761,0.422081,72.052419
2,202408070811,6,37.8,13,0.206383,0.178295,-0.801325,-0.109503,3.955042,0.809867,3,1,NaN,-0.204124,-1.035615,-0.880152,-1.266449,NaN,-0.732724,-0.522458,NaN,NaN,-1.202358,-1.205716,NaN,NaN,172.621438,171.181504,170.898128,161.029241,-1.744519,0.135962,71.967262
7,202408070811,8,2.8,1,0.182195,0.192913,0.897321,0.724347,4.248875,1.267500,2,1,NaN,1.632993,2.074973,1.088044,0.749788,NaN,1.790787,0.984902,NaN,NaN,1.034879,0.881414,NaN,NaN,178.389784,164.092586,165.468092,151.478257,-0.814851,-1.665544,71.942881
13,202408070811,4,16.6,8,0.200441,0.214008,-0.060373,0.136537,3.135468,1.201806,2,1,NaN,0.408248,0.901484,1.436499,0.749788,NaN,0.783712,0.751727,NaN,NaN,0.827686,0.837564,NaN,NaN,190.810847,172.374949,171.779359,168.010128,1.187019,0.439252,71.855696
11,202408070811,7,7.2,3,0.182195,0.189189,0.724448,0.415489,3.110432,0.728970,2,1,NaN,-1.428869,1.073671,0.334973,0.749788,NaN,0.750828,1.034201,NaN,NaN,0.820920,0.890685,NaN,NaN,187.838523,172.958181,182.727411,172.524847,0.707978,0.587468,71.778935
9,202408070811,11,12.7,6,0.186508,0.184739,0.424797,0.268417,4.190723,1.448635,2,1,NaN,-0.816497,-0.577075,-0.529144,0.749788,NaN,0.287311,0.385396,NaN,NaN,0.725557,0.768675,NaN,NaN,192.662095,170.726398,176.598128,170.329500,1.485380,0.020306,71.611998
10,202408070811,1,11.6,4,0.204225,0.210117,1.925903,1.211023,1.354860,-0.248798,4,1,NaN,-0.204124,-1.035615,0.243073,-1.165637,NaN,-1.274682,-1.307060,NaN,NaN,-1.006358,-0.979560,NaN,NaN,175.360507,171.976447,164.290452,168.400000,-1.303071,0.337981,71.606953
1,202408070811,3,7.0,2,0.200441,0.208494,0.586024,0.680278,3.563275,1.211174,3,1,NaN,1.020621,0.615130,1.961096,-1.266449,NaN,-0.716916,-0.500331,NaN,NaN,-1.205610,-1.209877,NaN,NaN,184.526144,173.553445,176.550817,168.465255,0.174130,0.738743,71.599975

In [33]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
4,202408070811,10,88.4,16,0.206827,0.244094,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-1.416236,0.749788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.641763
5,202408070811,14,35.1,12,0.217899,0.188679,NaN,NaN,NaN,2.112085,2,1,NaN,1.632993,-1.035615,0.651518,0.749788,NaN,-0.169602,-0.053680,NaN,NaN,0.631552,0.686106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.981215
6,202408070811,2,13.1,7,0.204225,0.209302,-0.484217,0.152622,3.842792,1.388956,2,1,NaN,1.020621,-0.249546,-0.688693,0.749788,NaN,0.779472,0.461621,NaN,NaN,0.826813,0.783009,NaN,NaN,178.945524,160.077576,169.133746,151.661779,-0.725283,-2.685878,73.308445
8,202408070811,16,31.1,11,0.209393,0.204819,-1.685883,-2.838947,3.129170,0.469285,2,1,NaN,0.408248,-0.193398,-0.592964,0.749788,NaN,-0.424778,-0.879289,NaN,NaN,0.579053,0.530848,NaN,NaN,185.585628,168.941616,177.235294,166.110128,0.344885,-0.433261,72.985631
14,202408070811,9,42.1,14,0.206827,0.226562,-1.383303,-1.312309,2.522484,0.500320,3,1,NaN,-0.816497,0.615130,0.835319,-1.266449,NaN,-1.130024,-1.078577,NaN,NaN,-1.120618,-1.101136,NaN,NaN,176.942310,172.779953,169.931461,170.329500,-1.048136,0.542175,72.789964
15,202408070811,5,18.4,9,0.206383,0.193798,0.908539,0.322505,2.223422,0.570771,3,1,NaN,-0.204124,-1.035615,-0.233021,-1.266449,NaN,-1.344051,-1.378162,NaN,NaN,-1.076585,-1.044799,NaN,NaN,187.651035,172.307382,176.446025,168.465255,0.677761,0.422081,72.684794
12,202408070811,15,29.6,10,0.209393,0.184615,-0.250633,-0.328382,3.952546,1.235542,3,1,NaN,-0.816497,1.073671,0.022257,-1.266449,NaN,0.250039,0.853163,NaN,NaN,-1.404550,-1.464405,NaN,NaN,183.120088,174.513287,178.068059,172.529500,-0.052480,0.982667,72.570598
3,202408070811,13,43.4,15,0.217899,0.158590,-0.944592,0.229521,2.915105,1.035016,2,1,NaN,-1.428869,-1.035615,-1.416236,0.749788,NaN,-0.481149,-0.690255,NaN,NaN,0.567455,0.566396,NaN,NaN,190.360745,171.924847,190.360745,171.924847,1.114477,0.324868,72.524871
2,202408070811,6,37.8,13,0.206383,0.178295,-0.801325,-0.109503,3.955042,0.809867,3,1,NaN,-0.204124,-1.035615,-0.880152,-1.266449,NaN,-0.732724,-0.522458,NaN,NaN,-1.202358,-1.205716,NaN,NaN,172.621438,171.181504,170.898128,161.029241,-1.744519,0.135962,72.484386
7,202408070811,8,2.8,1,0.182195,0.192913,0.897321,0.724347,4.248875,1.267500,2,1,NaN,1.632993,2.074973,1.088044,0.749788,NaN,1.790787,0.984902,NaN,NaN,1.034879,0.881414,NaN,NaN,178.389784,164.092586,165.468092,151.478257,-0.814851,-1.665544,72.445353
0,202408070811,12,11.8,5,0.186508,0.232365,0.143293,0.448400,3.871493,2.102083,2,1,NaN,-0.204124,-0.155966,-0.816332,0.749788,NaN,1.631775,1.938802,NaN,NaN,1.002165,1.060797,NaN,NaN,183.425303,171.642756,178.028387,169.900000,-0.003289,0.253180,72.434951
10,202408070811,1,11.6,4,0.204225,0.210117,1.925903,1.211023,1.354860,-0.248798,4,1,NaN,-0.204124,-1.035615,0.243073,-1.165637,NaN,-1.274682,-1.307060,NaN,NaN,-1.006358,-0.979560,NaN,NaN,175.360507,171.976447,164.290452,168.400000,-1.303071,0.337981,72.193481
9,202408070811,11,12.7,6,0.186508,0.184739,0.424797,0.268417,4.190723,1.448635,2,1,NaN,-0.816497,-0.577075,-0.529144,0.749788,NaN,0.287311,0.385396,NaN,NaN,0.725557,0.768675,NaN,NaN,192.662095,170.726398,176.598128,170.329500,1.485380,0.020306,72.186714
13,202408070811,4,16.6,8,0.200441,0.214008,-0.060373,0.136537,3.135468,1.201806,2,1,NaN,0.408248,0.901484,1.436499,0.749788,NaN,0.783712,0.751727,NaN,NaN,0.827686,0.837564,NaN,NaN,190.810847,172.374949,171.779359,168.010128,1.187019,0.439252,72.146276
1,202408070811,3,7.0,2,0.200441,0.208494,0.586024,0.680278,3.563275,1.211174,3,1,NaN,1.020621,0.615130,1.961096,-1.266449,NaN,-0.716916,-0.500331,NaN,NaN,-1.205610,-1.209877,NaN,NaN,184.526144,173.553445,176.550817,168.465255,0.174130,0.738743,72.062009
11,202408070811,7,7.2,3,0.182195,0.189189,0.724448,0.415489,3.110432,0.728970,2,1,NaN,-1.428869,1.073671,0.334973,0.749788,NaN,0.750828,1.034201,NaN,NaN,0.820920,0.890685,NaN,NaN,187.838523,172.958181,182.727411,172.524847,0.707978,0.587468,71.968059