In [1]:
import create_population
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction


import re
import pandas as pd

import create_population
import html5lib

from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki


from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

In [15]:
%autoreload

In [3]:
population = create_population.create(from_="2023-01-01", to_="2023-12-31")

In [4]:
population

            race_id       date    horse_id
0      202306010101 2023-01-05  2020103575
1      202306010101 2023-01-05  2020107073
2      202306010101 2023-01-05  2020102562
3      202306010101 2023-01-05  2020106345
4      202306010101 2023-01-05  2020100039
...             ...        ...         ...
46207  202309050912 2023-12-28  2017104873
46208  202309050912 2023-12-28  2019100653
46209  202309050912 2023-12-28  2017106240
46210  202309050912 2023-12-28  2018103205
46211  202309050912 2023-12-28  2017102603

[46212 rows x 3 columns]

In [9]:

import json
from pathlib import Path

import pandas as pd
import numpy as np
import ast
COMMON_DATA_DIR = Path("..", "..", "common", "data")
RAWDF_DIR = COMMON_DATA_DIR / "rawdf"
MAPPING_DIR = COMMON_DATA_DIR / "mapping"
POPULATION_DIR = Path("..", "data", "00_population")
OUTPUT_DIR = Path("..", "data", "01_preprocessed")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# カテゴリ変数を数値に変換するためのマッピング
with open(MAPPING_DIR / "sex.json", "r") as f:
    sex_mapping = json.load(f)
with open(MAPPING_DIR / "race_type.json", "r") as f:
    race_type_mapping = json.load(f)
with open(MAPPING_DIR / "around.json", "r") as f:
    around_mapping = json.load(f)
with open(MAPPING_DIR / "weather.json", "r") as f:
    weather_mapping = json.load(f)
with open(MAPPING_DIR / "ground_state.json", "r") as f:
    ground_state_mapping = json.load(f)
with open(MAPPING_DIR / "race_class.json", "r") as f:
    race_class_mapping = json.load(f)
with open(MAPPING_DIR / "place.json", "r") as f:
    place_mapping = json.load(f)

population_dir = POPULATION_DIR
populaton_filename = "population.csv"
input_dir= RAWDF_DIR
output_dir = OUTPUT_DIR
input_filename = "horse_results.csv"
output_filename = "horse_results.csv"
race_type_mapping = race_type_mapping
weather_mapping = weather_mapping
ground_state_mapping= ground_state_mapping
race_class_mapping = race_class_mapping
place_mapping= place_mapping

In [13]:
population = pd.read_csv(population_dir / populaton_filename, sep="\t")
# df = pd.read_csv(input_dir / input_filename, sep="\t").query(
#     "horse_id in @population['horse_id']"
# )
population_horse_ids = population['horse_id'].tolist()

# クエリでリストを直接使用
df = pd.read_csv(input_dir / input_filename, sep="\t").query(
    "horse_id in @population_horse_ids"
)


df["rank"] = pd.to_numeric(df["着順"], errors="coerce")
df.dropna(subset=["rank"], inplace=True)
df["date"] = pd.to_datetime(df["日付"])
df["weather"] = df["天気"].map(weather_mapping)
df["race_type"] = df["距離"].str[0].map(race_type_mapping)
df["course_len"] = df["距離"].str.extract(r"(\d+)").astype(int)
df["ground_state"] = df["馬場"].map(ground_state_mapping)
df["rank_diff"] = df["着差"].map(lambda x: 0 if x < 0 else x)
df["prize"] = df["賞金"].fillna(0)
df["umaban"] = df["馬番"].astype(int)

df["wakuban"] = df["枠番"].fillna(0).astype(int)


df["nobori"] = df["上り"].astype(float)

regex_race_class = "|".join(race_class_mapping)
df["race_class"] = (
    df["レース名"].str.extract(rf"({regex_race_class})")[0].map(race_class_mapping)
)
df["time"] = pd.to_datetime(df["タイム"], format="%M:%S.%f", errors="coerce")
df["time"] = (
    df["time"].dt.minute * 60
    + df["time"].dt.second
    + df["time"].dt.microsecond / 1000000
)
df["win"] = (df["rank"] == 1).astype(int)
df["rentai"] = (df["rank"] <= 2).astype(int)
df["show"] = (df["rank"] <= 3).astype(int)
df["place"] = df["開催"].str.extract(r"(\D+)")[0].map(place_mapping)
df.dropna(subset=["place"], inplace=True)    
df.rename(columns={"頭数": "n_horses"}, inplace=True)

pase_cols = df['ペース'].str.split('-', expand=True)
pase_cols.columns = [f'pase_{i+1}' for i in range(pase_cols.shape[1])]

# データ型変換と型確認
pase_cols = pase_cols.apply(pd.to_numeric, errors='coerce').astype('float64')

# 元のデータフレームと結合
df = pd.concat([df, pase_cols], axis=1)

# NoneをNaNに置き換え
# df = df.where(pd.notnull(df), np.nan)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["weather"] = df["weather"].astype(int)   
# コーナー通過順を分割して列を作成
corner_cols = df['通過'].str.split('-', expand=True)
corner_cols.columns = [f'corner_{i+1}' for i in range(corner_cols.shape[1])]
# オブジェクト型のデータを整数型に変換する
corner_cols = corner_cols.apply(pd.to_numeric, errors='coerce').astype('Int64')  
# nullable int型を指定
# 元のデータフレームと結合
df = pd.concat([df, corner_cols], axis=1)

# NoneをNaNに置き換え
df = df.where(pd.notnull(df), np.nan)

# rank / n_horses の特徴量を作成（欠損値を含む行はNaNに設定）
df["rank_per_horse"] = df["rank"].where(df["rank"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)

# corner_1 / n_horses の特徴量を作成（欠損値を含む行はNaNに設定）
df["corner_1_per_horse"] = df["corner_1"].where(df["corner_1"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)

df["corner_2_per_horse"] = df["corner_2"].where(df["corner_2"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)
df["corner_3_per_horse"] = df["corner_3"].where(df["corner_3"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)
df["corner_4_per_horse"] = df["corner_4"].where(df["corner_4"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)
df["time_courselen"] = df["time"] / df["course_len"]


# 月を抽出して開催シーズンを判定
def determine_season(month):
    if 6 <= month <= 8:
        return "2" #"夏開催"
    elif month == 12 or 1 <= month <= 2:
        return "4" #"冬開催"
    elif 3 <= month <= 5:
        return "1" #"春開催"
    elif 9 <= month <= 11:
        return "3" #"秋開催"    


df["race_type"] = df["race_type"].astype(str)

df["season"] = df["date"].dt.month.map(determine_season)

# 開催地とシーズンを組み合わせた新しいカテゴリを作成
df["place_season"] = df["place"].astype(str) + df["season"]
#芝/ダートを紐付け、ダ0芝1障2
df["place_season_type"] = df["place_season"] + df["race_type"]



# 開催_季節_開催コンディション_レースタイプを表示
df["place_season_condition_type"] = df["place_season"] + df["race_type"]


# コース別の馬場レベルを対応させる
"""
オール野芝 ▶︎最も軽い芝で、速い時計が出やすい
軽い芝 ▶︎時計面では野芝に劣るものの、こちらも速い時計が出やすい
オーバーシード ▶︎ケースバイケース
重い芝 ▶︎馬場が重く、時計もかかりやすい
非常に重い芝 ▶︎JRA10場の中で最も重く、時計もかかりやすい

オール野芝5	 '10111','10211',   小倉(夏)	'6311',中山(秋)	 '9311',   阪神(秋)	 '4111',  '4211',  '4311', '4411', 
新潟	 '7311',   中京(秋)		
軽い芝4	 '5111', '5211',  '5311',  '5411', 
 東京	 '8111',  '8211', '8311',   京都	'4121','4221','4321', '4421',  新潟	'10121','10221','小倉(夏)	 '6321', ' 中山(秋)	'9321', 阪神(秋)	'7321', 中京(秋)
オーバーシード3	'5121','5221','5321','5421',  東京	'8121','8221', '8321',京都	 '9111',  '9211', '9411', 阪神	 '3111', '3211',  '3311', '3411', 
福島	'7111',  '7211',  '7411', 中京	'6111',  '6211',  '6411',  中山	'10311','10411'小倉(冬)
重い芝2	'9121','9221','9421',阪神	'6121','6221','6421',中山	'7121','7221','7421',中京	'3121', '3221','3321', '3421',  福島	'8411', '8421'京都(冬)	 '10321', '10421'小倉(冬)	
非常に重い芝1	 '2111', '2121', '2211', '2221', '2311', '2321', '2411', '2421',  
函館	'1111', '1121', '1211', '1221', '1311', '1321', '1411', '1421',  札幌					

令和版ダートコースの馬場レベル表
軽いダート-1	 '5110', '5120', '5210', '5220', '5310', '5320', '5410', '5420',東京	 '8110', '8120', '8210', '8220', '8310', '8320', '8410', '8420', 京都				
重いダート-2	'1110', '1120', '1210', '1220', '1310', '1320', '1410', '1420', 札幌	'2110', '2120', '2210', '2220', '2310', '2320', '2410', '2420',函館	   '10110', '10120', '10210', '10220', '10310', '10320', '10410', '10420'小倉	'3110', '3120', '3210', '3220', '3310', '3320', '3410', '3420',福島	'4110', '4120', '4210', '4220', '4310', '4320', '4410', '4420',新潟	 '9110', '9120', '9210', '9220', '9310', '9320', '9410', '9420', 阪神
非常に重いダート-3	'7110', '7120', '7210', '7220', '7310', '7320', '7410', '7420', 中京	'6110', '6120', '6210', '6220', '6310', '6320', '6410', '6420', 中山				
障害レースはその他0
"""


conversion_map = {
    '1011': 5, '1021': 5, '631': 5, '931': 5, '411': 5, '421': 5, '431': 5, '441': 5, '731': 5,
    
    '511': 4, '521': 4, '531': 4, '541': 4, '811': 4, '821': 4, '831': 4, 
    '631': 4, 
    
    '911': 3, '921': 3, '941': 3,
    '311': 3, '321': 3, '331': 3, '341': 3, '711': 3, '721': 3, '741': 3, '611': 3, '621': 3, '641': 3,
    '1031': 3, '1041': 3,
    
    '611': 2, '621': 2, '641': 2, 
    '841': 2, '841': 2, 
    
    '211': 1, '221': 1, '231': 1, '241': 1, 
    '111': 1, '121': 1, '131': 1, '141': 1,
    
    '510': -1, '520': -1, '530': -1, '540': -1,
    '810': -1, '820': -1, '830': -1, '840': -1,
    '110': -2, '120': -2, '130': -2, '140': -2,
    '210': -2, '220': -2, '230': -2, '240': -2,
    '1010': -2, '1020': -2, '1030': -2, '1040': -2,
    '310': -2, '320': -2, '330': -2, '340': -2,
    '410': -2, '420': -2, '430': -2, '440': -2,
    '910': -2, '920': -2, '930': -2, '940': -2,
    '710': -3, '720': -3, '730': -3, '740': -3,
    '610': -3, '620': -3, '630': -3, '640': -3
}

df['place_season_condition_type_categori'] = df['place_season_condition_type'].map(conversion_map).fillna(-10000).astype(int)
df['place_season_condition_type_categori'] = df['place_season_condition_type_categori'].replace(-10000, np.nan)




df = df.where(pd.notnull(df), np.nan)
# 使用する列を選択
df = df[
    [
        "horse_id",
        "rank_per_horse",
        "date",
        "rank",
        "prize",
        "rank_diff",
        "umaban",
        "wakuban",
        "weather",
        "race_type",
        "course_len",
        "ground_state",
        "race_class",
        "n_horses",
        "time",
        "time_courselen",
        "nobori",
        "win",
        "rentai",
        "show",
        "place",
        
        "corner_1_per_horse",
        "corner_2_per_horse",
        "corner_3_per_horse",
        "corner_4_per_horse",
        'place_season_condition_type_categori',
    ] + list(corner_cols.columns) + list(pase_cols.columns)
]

In [14]:
df

,horse_id,rank_per_horse,date,rank,prize,rank_diff,umaban,wakuban,weather,race_type,...,corner_2_per_horse,corner_3_per_horse,corner_4_per_horse,place_season_condition_type_categori,corner_1,corner_2,corner_3,corner_4,pase_1,pase_2
65518,2011106610,1.000000,2023-12-10,8.0,0.0,3.9,1,1,1,1,...,1.0,1.0,0.875,3.0,8,8,8,7,38.2,33.7
65519,2011106610,1.000000,2023-11-11,8.0,0.0,1.6,7,7,2,1,...,0.75,<NA>,<NA>,4.0,6,6,<NA>,<NA>,35.9,34.9
65520,2011106610,1.000000,2023-10-29,9.0,0.0,2.3,2,2,1,1,...,0.777778,<NA>,<NA>,4.0,7,7,<NA>,<NA>,36.5,33.4
65521,2011106610,1.000000,2023-10-07,11.0,0.0,1.8,10,8,1,1,...,0.909091,<NA>,<NA>,4.0,10,10,<NA>,<NA>,36.0,33.5
65522,2011106610,0.900000,2023-09-18,9.0,0.0,2.7,3,3,1,1,...,0.9,<NA>,<NA>,5.0,9,9,<NA>,<NA>,34.7,33.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077785,2021102427,0.571429,2024-04-06,8.0,0.0,2.3,12,7,2,0,...,0.642857,0.428571,0.5,-3.0,8,9,6,7,39.1,38.0
1077786,2021102427,0.928571,2023-12-28,13.0,0.0,2.5,7,5,1,1,...,0.642857,<NA>,<NA>,3.0,9,9,<NA>,<NA>,36.0,34.1
1077795,2021103807,1.000000,2024-02-24,11.0,0.0,3.4,1,1,2,0,...,0.090909,0.090909,0.181818,-2.0,1,1,1,2,36.8,39.7
1077796,2021103807,0.785714,2024-01-13,11.0,0.0,2.1,2,2,1,0,...,0.857143,0.642857,0.571429,-1.0,14,12,9,8,35.8,39.8
1077797,2021103807,1.000000,2023-12-28,14.0,0.0,3.1,13,8,1,1,...,0.214286,<NA>,<NA>,3.0,3,3,<NA>,<NA>,36.0,34.1