In [12]:
import create_population
import create_population3
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction
from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lgbm_rank_kaiki_cross import Trainer_lightgbm_rank_kaiki_cv
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross

import pandas as pd


import condition_prediction


from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki

from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
%autoreload

In [14]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [15]:
population = create_population.create(from_="2016-01-01", to_="2024-11-30")

In [16]:
# 当日出走馬の過去成績テーブルの前処理_そのままで使えない未加工のデータを加工する
horse_results_preprocessed = preprocessing.process_horse_results(
    input_filename="horse_results_prediction.csv",
    output_filename="horse_results_prediction.csv"
)
horse_results_preprocessed

# 当日出走馬の血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds(
    input_filename="peds_prediction.csv",
    output_filename="peds_prediction.csv"
)
peds_preprocessed

pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()
pfc.agg_horse_n_races()
pfc.agg_horse_n_races_relative()
pfc.agg_horse_n_races_df

# レース結果テーブルの前処理
results_preprocessed = condition_prediction.process_results()
# レース情報テーブルの前処理
race_info_preprocessed = condition_prediction.process_race_info()
create_race_grade_preprocessed = condition_prediction.create_race_grade()

agg_horse_n_races_relative:   0%|          | 0/4 [00:00<?, ?it/s]

###　12/22 第1回目レース

In [17]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050801",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [18]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050801,2022102499,1085,1187,1,1,95.3,13,55.0,1,2,NaN,NaN,16,2.0,2.0,2
1,202406050801,2022102542,1077,1108,2,1,55.3,8,55.0,1,2,NaN,NaN,16,2.0,2.0,2
2,202406050801,2022100627,1163,1153,3,2,4.7,3,55.0,1,2,NaN,NaN,16,2.0,2.0,2
3,202406050801,2022100325,1169,1064,4,2,81.3,11,56.0,0,2,NaN,NaN,16,2.0,2.0,2
4,202406050801,2022102442,1214,1094,5,3,158.3,15,52.0,1,2,NaN,NaN,16,2.0,2.0,2
5,202406050801,2022106686,5473,1086,6,3,3.3,2,55.0,1,2,NaN,NaN,16,2.0,2.0,2
6,202406050801,2022100399,1032,1152,7,4,40.0,7,55.0,1,2,NaN,NaN,16,2.0,2.0,2
7,202406050801,2022101137,1183,1023,8,4,82.2,12,54.0,0,2,NaN,NaN,16,2.0,2.0,2
8,202406050801,2022100958,1207,1008,9,5,170.6,16,52.0,1,2,NaN,NaN,16,2.0,2.0,2
9,202406050801,2022102811,1134,1202,10,5,21.1,4,55.0,1,2,NaN,NaN,16,2.0,2.0,2
10,202406050801,2022106654,1157,1076,11,6,25.0,5,55.0,1,2,NaN,NaN,16,2.0,2.0,2
11,202406050801,2022102695,1162,1106,12,6,56.7,10,56.0,0,2,NaN,NaN,16,2.0,2.0,2
12,202406050801,2022107292,422,1080,13,7,56.5,9,56.0,0,2,NaN,NaN,16,2.0,2.0,2
13,202406050801,2022106594,5386,1103,14,7,28.4,6,55.0,1,2,NaN,NaN,16,2.0,2.0,2
14,202406050801,2022110128,5366,1070,15,8,2.0,1,56.0,0,2,NaN,NaN,16,2.0,2.0,2
15,202406050801,2022103591,1203,1131,16,8,100.6,14,52.0,1,2,NaN,NaN,16,2.0,2.0,2

In [19]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050801,0,0,1200,1,0,1,6,1,73875101,4,64,640,1,10,8,80,5,50,64080,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401200,-1,24,60,1.0

In [20]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
0,202406050801,16,100.6,14,0.208644,0.189895,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.043271
13,202406050801,9,170.6,16,0.189940,0.183036,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.790800
7,202406050801,8,82.2,12,0.176471,0.206538,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.548200
1,202406050801,2,55.3,8,0.174194,0.158209,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.474993
9,202406050801,10,21.1,4,0.189940,0.203593,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.459391
11,202406050801,13,56.5,9,0.205970,0.198157,-0.992719,-0.688014,0.967021,-0.333200,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.820485,-0.826658,NaN,NaN,-1.173333,-1.107447,NaN,NaN,158.102819,143.834191,158.102819,143.834191,1.931622,1.484775,76.421096
3,202406050801,3,4.7,3,0.179209,0.174107,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.062929
8,202406050801,14,28.4,6,0.205970,0.218553,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.768536
12,202406050801,1,95.3,13,0.174194,0.188623,-0.988402,-0.684005,0.269565,-0.447645,2,3,NaN,NaN,-0.479421,-0.429264,0.465130,NaN,-0.786069,-0.934942,NaN,NaN,0.078429,-0.067149,NaN,NaN,125.217942,136.084508,125.217942,136.084508,-1.079920,-1.731086,75.257809
4,202406050801,5,158.3,15,0.192982,0.177083,0.143172,0.014572,0.785849,-0.373113,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.719784,-0.652525,NaN,NaN,-1.220426,-1.198277,NaN,NaN,140.277292,139.885351,140.277292,139.885351,0.299190,-0.153862,74.971567
15,202406050801,11,25.0,5,0.211510,0.181682,-0.964909,-1.076568,0.609559,-0.513051,2,3,NaN,NaN,-0.479421,-0.429264,0.465130,NaN,-0.490735,-0.519799,NaN,NaN,0.216542,0.149395,NaN,NaN,130.133466,141.703113,125.338306,138.611033,-0.629765,0.600448,74.867346
6,202406050801,7,40.0,7,0.176471,0.154762,0.140337,-0.155613,0.669365,-0.341150,2,3,NaN,NaN,-0.479421,0.688606,0.465130,NaN,-0.362568,-0.251504,NaN,NaN,0.276480,0.289340,NaN,NaN,127.824240,138.839939,122.869485,135.745687,-0.841240,-0.587674,74.743021
10,202406050801,4,81.3,11,0.179209,0.194362,-0.099670,0.141349,NaN,1.475000,2,3,NaN,-1.154701,-0.479421,-0.429264,0.465130,NaN,0.626884,0.875276,NaN,NaN,0.739198,0.877082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.631717
14,202406050801,12,56.7,10,0.211510,0.239394,-0.333006,-0.771225,0.941063,-0.537862,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.592617,-0.526867,NaN,NaN,-1.279896,-1.263821,NaN,NaN,136.653896,140.822612,121.871639,137.811033,-0.032635,0.235070,74.589621
5,202406050801,6,3.3,2,0.192982,0.209199,1.268873,1.412299,0.704762,-0.646667,2,3,NaN,0.577350,2.294373,2.158398,0.465130,NaN,1.320034,0.863870,NaN,NaN,1.063350,0.871132,NaN,NaN,131.836230,138.733666,131.836230,138.733666,-0.473828,-0.631774,73.530604
2,202406050801,15,2.0,1,0.208644,0.207792,1.826325,1.807205,1.330288,0.322348,2,3,NaN,0.577350,1.061575,2.733434,0.465130,NaN,1.825340,1.973149,NaN,NaN,1.299656,1.449745,NaN,NaN,146.036139,142.145687,146.036139,142.145687,0.826576,0.784102,72.797389

In [21]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
0,202406050801,16,100.6,14,0.208644,0.189895,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.147743
13,202406050801,9,170.6,16,0.189940,0.183036,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.927273
9,202406050801,10,21.1,4,0.189940,0.203593,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.566204
7,202406050801,8,82.2,12,0.176471,0.206538,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.247660
1,202406050801,2,55.3,8,0.174194,0.158209,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.200811
11,202406050801,13,56.5,9,0.205970,0.198157,-0.992719,-0.688014,0.967021,-0.333200,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.820485,-0.826658,NaN,NaN,-1.173333,-1.107447,NaN,NaN,158.102819,143.834191,158.102819,143.834191,1.931622,1.484775,75.985524
3,202406050801,3,4.7,3,0.179209,0.174107,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.844083
8,202406050801,14,28.4,6,0.205970,0.218553,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.429264,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.765294
6,202406050801,7,40.0,7,0.176471,0.154762,0.140337,-0.155613,0.669365,-0.341150,2,3,NaN,NaN,-0.479421,0.688606,0.465130,NaN,-0.362568,-0.251504,NaN,NaN,0.276480,0.289340,NaN,NaN,127.824240,138.839939,122.869485,135.745687,-0.841240,-0.587674,75.255039
4,202406050801,5,158.3,15,0.192982,0.177083,0.143172,0.014572,0.785849,-0.373113,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.719784,-0.652525,NaN,NaN,-1.220426,-1.198277,NaN,NaN,140.277292,139.885351,140.277292,139.885351,0.299190,-0.153862,75.163531
12,202406050801,1,95.3,13,0.174194,0.188623,-0.988402,-0.684005,0.269565,-0.447645,2,3,NaN,NaN,-0.479421,-0.429264,0.465130,NaN,-0.786069,-0.934942,NaN,NaN,0.078429,-0.067149,NaN,NaN,125.217942,136.084508,125.217942,136.084508,-1.079920,-1.731086,75.135868
10,202406050801,4,81.3,11,0.179209,0.194362,-0.099670,0.141349,NaN,1.475000,2,3,NaN,-1.154701,-0.479421,-0.429264,0.465130,NaN,0.626884,0.875276,NaN,NaN,0.739198,0.877082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.064837
15,202406050801,11,25.0,5,0.211510,0.181682,-0.964909,-1.076568,0.609559,-0.513051,2,3,NaN,NaN,-0.479421,-0.429264,0.465130,NaN,-0.490735,-0.519799,NaN,NaN,0.216542,0.149395,NaN,NaN,130.133466,141.703113,125.338306,138.611033,-0.629765,0.600448,74.982684
14,202406050801,12,56.7,10,0.211510,0.239394,-0.333006,-0.771225,0.941063,-0.537862,3,3,NaN,NaN,-0.479421,-0.429264,-2.015564,NaN,-0.592617,-0.526867,NaN,NaN,-1.279896,-1.263821,NaN,NaN,136.653896,140.822612,121.871639,137.811033,-0.032635,0.235070,74.606930
5,202406050801,6,3.3,2,0.192982,0.209199,1.268873,1.412299,0.704762,-0.646667,2,3,NaN,0.577350,2.294373,2.158398,0.465130,NaN,1.320034,0.863870,NaN,NaN,1.063350,0.871132,NaN,NaN,131.836230,138.733666,131.836230,138.733666,-0.473828,-0.631774,73.757870
2,202406050801,15,2.0,1,0.208644,0.207792,1.826325,1.807205,1.330288,0.322348,2,3,NaN,0.577350,1.061575,2.733434,0.465130,NaN,1.825340,1.973149,NaN,NaN,1.299656,1.449745,NaN,NaN,146.036139,142.145687,146.036139,142.145687,0.826576,0.784102,73.130137

###　12/22 第2回目レース

In [22]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050802",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [23]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050802,2022103493,1140,1068,1,1,8.7,5,56.0,0,2,NaN,NaN,16,2.0,2.0,2
1,202406050802,2022104251,1143,1131,2,1,164.3,16,56.0,0,2,NaN,NaN,16,2.0,2.0,2
2,202406050802,2022104203,5386,1118,3,2,6.7,2,56.0,0,2,NaN,NaN,16,2.0,2.0,2
3,202406050802,2022102965,1163,1116,4,2,2.8,1,56.0,0,2,NaN,NaN,16,2.0,2.0,2
4,202406050802,2022105252,1157,1059,5,3,26.1,9,56.0,0,2,NaN,NaN,16,2.0,2.0,2
5,202406050802,2022107074,1158,1116,6,3,82.4,15,56.0,0,2,NaN,NaN,16,2.0,2.0,2
6,202406050802,2022100224,1138,1051,7,4,68.1,14,56.0,0,2,NaN,NaN,16,2.0,2.0,2
7,202406050802,2022100360,1043,1195,8,4,23.9,8,56.0,0,2,NaN,NaN,16,2.0,2.0,2
8,202406050802,2022102378,5626,1020,9,5,7.3,4,56.0,0,2,NaN,NaN,16,2.0,2.0,2
9,202406050802,2022104613,1170,1127,10,5,11.1,6,56.0,0,2,NaN,NaN,16,2.0,2.0,2
10,202406050802,2022105340,1077,1108,11,6,28.2,10,56.0,0,2,NaN,NaN,16,2.0,2.0,2
11,202406050802,2022104313,5366,1187,12,6,7.1,3,56.0,0,2,NaN,NaN,16,2.0,2.0,2
12,202406050802,2022104177,1162,1169,13,7,38.6,11,56.0,0,2,NaN,NaN,16,2.0,2.0,2
13,202406050802,2022106465,1009,1074,14,7,55.4,12,56.0,0,2,NaN,NaN,16,2.0,2.0,2
14,202406050802,2022105883,689,1190,15,8,58.7,13,56.0,0,2,NaN,NaN,16,2.0,2.0,2
15,202406050802,2022101140,1179,1088,16,8,17.5,7,56.0,0,2,NaN,NaN,16,2.0,2.0,2

In [24]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050802,0,0,1800,1,0,1,6,2,73875102,4,64,640,2,20,8,80,5,50,64080,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401800,-1,24,60,1.0

In [25]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
15,202406050802,6,82.4,15,0.178354,0.171662,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.539947
6,202406050802,14,55.4,12,0.242279,0.216123,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.382783
5,202406050802,7,68.1,14,0.184862,0.174863,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.194160
0,202406050802,11,28.2,10,0.207064,0.221751,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.116580
3,202406050802,8,23.9,8,0.184862,0.223881,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.869684
9,202406050802,2,164.3,16,0.182594,0.200272,-1.431336,-1.098301,0.484840,-0.117620,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-1.194886,-1.154099,NaN,NaN,-0.881034,-0.854740,NaN,NaN,129.965600,143.035300,118.002574,139.275407,-0.378931,0.973142,120.815756
12,202406050802,1,8.7,5,0.182594,0.180707,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.624155
8,202406050802,5,26.1,9,0.178354,0.195387,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.523703
14,202406050802,10,11.1,6,0.219168,0.229282,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.375845
2,202406050802,3,6.7,2,0.196187,0.203274,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.315132
4,202406050802,13,38.6,11,0.242279,0.228707,-0.440088,0.115158,0.434615,-0.232726,2,3,NaN,NaN,-0.800552,-0.459656,0.465130,NaN,-0.623605,-0.613844,NaN,NaN,0.254383,0.195021,NaN,NaN,160.128626,139.995192,160.128626,139.995192,1.559013,-0.464184,120.217699
1,202406050802,16,17.5,7,0.211853,0.193622,-0.333194,0.185372,0.779797,-0.113063,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-0.845444,-0.983861,NaN,NaN,-1.013415,-0.927021,NaN,NaN,117.338306,138.611033,117.338306,138.611033,-1.190222,-1.118597,119.527027
13,202406050802,15,58.7,13,0.211853,0.197343,-0.478962,-1.461950,0.802765,-0.190982,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-0.377371,-0.200209,NaN,NaN,-1.190738,-1.259750,NaN,NaN,134.926813,141.763637,120.093862,137.811033,-0.060178,0.371916,119.171605
10,202406050802,9,7.3,4,0.219168,0.193460,0.317323,0.201859,0.599797,-0.309936,2,3,NaN,NaN,1.122808,1.749965,0.465130,NaN,0.986556,0.804709,NaN,NaN,0.932146,0.864244,NaN,NaN,118.373284,139.739850,108.217942,135.084508,-1.123726,-0.584906,117.905499
7,202406050802,12,7.1,3,0.207064,0.222059,0.674750,0.554238,0.722991,-0.157083,2,3,NaN,NaN,0.956592,2.475593,0.465130,NaN,0.679608,0.667345,NaN,NaN,0.802943,0.799441,NaN,NaN,147.062196,144.335029,147.062196,144.335029,0.719508,1.587638,117.622677
11,202406050802,4,2.8,1,0.196187,0.211460,1.691507,1.503624,0.338347,-0.341304,2,3,NaN,NaN,1.122808,1.749965,0.465130,NaN,1.375144,1.479959,NaN,NaN,1.095714,1.182804,NaN,NaN,143.249364,139.358913,143.249364,139.358913,0.474537,-0.765009,117.092946

In [26]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
6,202406050802,14,55.4,12,0.242279,0.216123,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.178301
15,202406050802,6,82.4,15,0.178354,0.171662,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.176643
9,202406050802,2,164.3,16,0.182594,0.200272,-1.431336,-1.098301,0.484840,-0.117620,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-1.194886,-1.154099,NaN,NaN,-0.881034,-0.854740,NaN,NaN,129.965600,143.035300,118.002574,139.275407,-0.378931,0.973142,120.172135
4,202406050802,13,38.6,11,0.242279,0.228707,-0.440088,0.115158,0.434615,-0.232726,2,3,NaN,NaN,-0.800552,-0.459656,0.465130,NaN,-0.623605,-0.613844,NaN,NaN,0.254383,0.195021,NaN,NaN,160.128626,139.995192,160.128626,139.995192,1.559013,-0.464184,119.772964
5,202406050802,7,68.1,14,0.184862,0.174863,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.433664
0,202406050802,11,28.2,10,0.207064,0.221751,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.308974
1,202406050802,16,17.5,7,0.211853,0.193622,-0.333194,0.185372,0.779797,-0.113063,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-0.845444,-0.983861,NaN,NaN,-1.013415,-0.927021,NaN,NaN,117.338306,138.611033,117.338306,138.611033,-1.190222,-1.118597,118.894527
13,202406050802,15,58.7,13,0.211853,0.197343,-0.478962,-1.461950,0.802765,-0.190982,4,3,NaN,NaN,-0.800552,-0.459656,-2.015564,NaN,-0.377371,-0.200209,NaN,NaN,-1.190738,-1.259750,NaN,NaN,134.926813,141.763637,120.093862,137.811033,-0.060178,0.371916,118.783866
8,202406050802,5,26.1,9,0.178354,0.195387,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.732087
12,202406050802,1,8.7,5,0.182594,0.180707,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.701718
14,202406050802,10,11.1,6,0.219168,0.229282,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.349080
3,202406050802,8,23.9,8,0.184862,0.223881,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.297544
2,202406050802,3,6.7,2,0.196187,0.203274,NaN,NaN,NaN,NaN,2,3,NaN,NaN,NaN,-0.459656,0.465130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.213040
10,202406050802,9,7.3,4,0.219168,0.193460,0.317323,0.201859,0.599797,-0.309936,2,3,NaN,NaN,1.122808,1.749965,0.465130,NaN,0.986556,0.804709,NaN,NaN,0.932146,0.864244,NaN,NaN,118.373284,139.739850,108.217942,135.084508,-1.123726,-0.584906,117.618157
7,202406050802,12,7.1,3,0.207064,0.222059,0.674750,0.554238,0.722991,-0.157083,2,3,NaN,NaN,0.956592,2.475593,0.465130,NaN,0.679608,0.667345,NaN,NaN,0.802943,0.799441,NaN,NaN,147.062196,144.335029,147.062196,144.335029,0.719508,1.587638,117.032632
11,202406050802,4,2.8,1,0.196187,0.211460,1.691507,1.503624,0.338347,-0.341304,2,3,NaN,NaN,1.122808,1.749965,0.465130,NaN,1.375144,1.479959,NaN,NaN,1.095714,1.182804,NaN,NaN,143.249364,139.358913,143.249364,139.358913,0.474537,-0.765009,116.432358

### 12/22 第7回目レース

In [27]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050807",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [28]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050807,2021106583,1085,1152,1,1,55.5,12,57.0,0,3,NaN,NaN,16,3.5,3.0,3
1,202406050807,2018101497,5625,1134,2,1,45.3,11,56.0,1,6,NaN,NaN,16,3.5,3.0,3
2,202406050807,2021103017,1143,1093,3,2,60.5,13,57.0,0,3,NaN,NaN,16,3.5,3.0,3
3,202406050807,2021104314,1088,1191,4,2,4.7,3,57.0,0,3,NaN,NaN,16,3.5,3.0,3
4,202406050807,2021106845,1209,1147,5,3,35.1,9,54.0,2,3,NaN,NaN,16,3.5,3.0,3
5,202406050807,2021104762,5339,1126,6,3,2.9,1,57.0,2,3,NaN,NaN,16,3.5,3.0,3
6,202406050807,2021105575,5626,1175,7,4,19.3,6,57.0,0,3,NaN,NaN,16,3.5,3.0,3
7,202406050807,2021105182,5473,1059,8,4,8.1,4,57.0,0,3,NaN,NaN,16,3.5,3.0,3
8,202406050807,2021104754,1117,1189,9,5,44.7,10,55.0,1,3,NaN,NaN,16,3.5,3.0,3
9,202406050807,2021100329,1140,1125,10,5,4.0,2,57.0,0,3,NaN,NaN,16,3.5,3.0,3
10,202406050807,2021101928,5366,1070,11,6,11.6,5,57.0,2,3,NaN,NaN,16,3.5,3.0,3
11,202406050807,2019101403,1192,1202,12,6,120.2,14,55.0,1,5,NaN,NaN,16,3.5,3.0,3
12,202406050807,2020105510,1162,1131,13,7,125.2,15,58.0,0,4,NaN,NaN,16,3.5,3.0,3
13,202406050807,2021101201,1170,1141,14,7,29.1,8,57.0,0,3,NaN,NaN,16,3.5,3.0,3
14,202406050807,2019106972,1207,1077,15,8,125.2,16,55.0,2,5,NaN,NaN,16,3.5,3.0,3
15,202406050807,2021105890,1179,399,16,8,28.8,7,57.0,0,3,NaN,NaN,16,3.5,3.0,3

In [29]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050807,0,0,1800,1,0,2,6,7,73875107,4,64,640,7,70,8,80,5,50,64080,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401800,-1,34,70,2.0

In [30]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
3,202406050807,7,19.3,6,0.184862,0.174863,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.770404,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.921207
13,202406050807,16,28.8,7,0.211853,0.193622,-2.934919,-2.923735,1.276346,-0.186007,2,2,NaN,0.889910,-0.295084,0.732462,0.652495,NaN,0.218225,-0.674159,NaN,NaN,0.655134,0.442399,NaN,NaN,141.455513,148.025160,129.532402,142.805129,-1.749336,-0.817019,117.364243
8,202406050807,12,120.2,14,0.207064,0.222059,-0.930038,-1.098686,0.550000,-0.064226,2,2,NaN,-0.616092,-0.663940,-0.491060,0.652495,NaN,-0.705012,-0.853126,NaN,NaN,0.403720,0.395383,NaN,NaN,154.328626,142.195192,154.328626,142.195192,-0.517257,-2.048491,116.832536
0,202406050807,13,125.2,15,0.242279,0.228707,-0.381614,-0.257968,1.136523,0.020772,2,2,NaN,0.889910,-0.663940,-0.351389,0.652495,NaN,-1.242929,-1.372019,NaN,NaN,0.257236,0.259064,NaN,NaN,159.402916,156.972010,142.970107,150.909607,-0.031600,1.072836,116.452878
14,202406050807,15,125.2,16,0.211853,0.197343,-0.119561,0.452286,0.899437,-0.001357,3,2,NaN,-0.616092,-0.663940,-0.770404,-1.478100,NaN,-1.250996,-1.100200,NaN,NaN,-1.145914,-1.153569,NaN,NaN,158.883063,152.861089,153.187501,152.445192,-0.081354,0.204481,116.341072
6,202406050807,2,45.3,11,0.182594,0.200272,0.592951,0.511514,1.369804,0.151824,4,2,NaN,-0.616092,-0.663940,-0.770404,-1.371571,NaN,-0.893019,-0.637734,NaN,NaN,-1.154189,-1.183675,NaN,NaN,170.745801,156.871003,127.999589,149.891062,1.054022,1.051501,116.256849
11,202406050807,1,55.5,12,0.182594,0.180707,0.340301,0.708205,1.192857,-0.194048,2,2,NaN,-0.616092,-0.663940,-0.770404,0.652495,NaN,0.037667,0.332907,NaN,NaN,0.605965,0.706967,NaN,NaN,171.157421,155.096815,171.157421,155.096815,1.093418,0.676736,116.218705
1,202406050807,3,60.5,13,0.196187,0.203274,0.143467,0.525719,1.640841,0.011464,3,2,NaN,NaN,-0.295084,-0.491060,-1.478100,NaN,-0.454543,-0.514743,NaN,NaN,-1.362802,-1.307375,NaN,NaN,169.520106,157.146946,133.041184,144.005129,0.936712,1.109788,116.195839
10,202406050807,9,44.7,10,0.219168,0.193460,0.156797,-0.317684,0.913376,-0.035741,2,2,NaN,0.136909,-0.663940,-0.770404,0.652495,NaN,-0.965958,-1.003273,NaN,NaN,0.332660,0.355937,NaN,NaN,165.216341,150.946274,153.012977,148.745192,0.524800,-0.199988,116.139421
15,202406050807,14,29.1,8,0.242279,0.216123,-0.282944,-0.353451,1.042308,-0.279487,2,2,NaN,-0.616092,-0.663940,-0.770404,0.652495,NaN,0.400883,0.075065,NaN,NaN,0.704875,0.639229,NaN,NaN,170.846310,153.896815,170.846310,153.896815,1.063642,0.423259,116.138800
5,202406050807,11,11.6,5,0.207064,0.221751,0.152428,-0.153053,1.945307,0.306646,2,2,NaN,NaN,0.442627,0.067626,0.652495,NaN,0.170961,0.510369,NaN,NaN,0.642264,0.753588,NaN,NaN,166.986711,157.012941,151.090754,153.696815,0.694242,1.081482,115.391372
7,202406050807,8,8.1,4,0.184862,0.223881,1.087624,1.022045,2.147302,-0.213418,2,2,NaN,NaN,0.995910,0.765983,0.652495,NaN,0.625757,1.783133,NaN,NaN,0.766113,1.087957,NaN,NaN,164.290754,154.896815,149.999068,144.605129,0.436213,0.634490,115.362188
2,202406050807,5,35.1,9,0.178354,0.195387,-0.124915,0.334316,0.941958,-0.137500,4,2,NaN,-0.616092,-0.663940,-0.770404,-1.371571,NaN,-0.336305,0.103450,NaN,NaN,-1.290632,-1.358921,NaN,NaN,138.779609,147.065400,132.387501,146.009607,-2.005446,-1.019751,115.318795
9,202406050807,10,4.0,2,0.219168,0.229282,0.746096,0.071305,2.454489,0.178333,3,2,NaN,-0.616092,2.655760,1.743684,-1.478100,NaN,0.580520,0.596786,NaN,NaN,-1.644669,-1.599387,NaN,NaN,154.071063,149.641058,139.421290,143.405129,-0.541908,-0.475691,115.276036
4,202406050807,4,4.7,3,0.196187,0.211460,1.402602,1.202880,2.504242,0.131410,2,2,NaN,NaN,1.364766,2.050961,0.652495,NaN,1.684750,1.784346,NaN,NaN,1.054495,1.088276,NaN,NaN,161.347823,150.596274,125.665735,141.605129,0.154547,-0.273919,114.910898
12,202406050807,6,2.9,1,0.178354,0.171662,0.151725,0.276306,1.767847,0.118687,2,2,NaN,2.395912,0.442627,1.365618,0.652495,NaN,2.129998,0.969197,NaN,NaN,1.175744,0.874127,NaN,NaN,148.964092,145.171915,138.273307,144.345687,-1.030694,-1.419714,114.867486

In [31]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
13,202406050807,16,28.8,7,0.211853,0.193622,-2.934919,-2.923735,1.276346,-0.186007,2,2,NaN,0.889910,-0.295084,0.732462,0.652495,NaN,0.218225,-0.674159,NaN,NaN,0.655134,0.442399,NaN,NaN,141.455513,148.025160,129.532402,142.805129,-1.749336,-0.817019,117.938216
3,202406050807,7,19.3,6,0.184862,0.174863,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,-0.770404,0.652495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.180465
8,202406050807,12,120.2,14,0.207064,0.222059,-0.930038,-1.098686,0.550000,-0.064226,2,2,NaN,-0.616092,-0.663940,-0.491060,0.652495,NaN,-0.705012,-0.853126,NaN,NaN,0.403720,0.395383,NaN,NaN,154.328626,142.195192,154.328626,142.195192,-0.517257,-2.048491,117.124127
6,202406050807,2,45.3,11,0.182594,0.200272,0.592951,0.511514,1.369804,0.151824,4,2,NaN,-0.616092,-0.663940,-0.770404,-1.371571,NaN,-0.893019,-0.637734,NaN,NaN,-1.154189,-1.183675,NaN,NaN,170.745801,156.871003,127.999589,149.891062,1.054022,1.051501,116.774698
14,202406050807,15,125.2,16,0.211853,0.197343,-0.119561,0.452286,0.899437,-0.001357,3,2,NaN,-0.616092,-0.663940,-0.770404,-1.478100,NaN,-1.250996,-1.100200,NaN,NaN,-1.145914,-1.153569,NaN,NaN,158.883063,152.861089,153.187501,152.445192,-0.081354,0.204481,116.713004
0,202406050807,13,125.2,15,0.242279,0.228707,-0.381614,-0.257968,1.136523,0.020772,2,2,NaN,0.889910,-0.663940,-0.351389,0.652495,NaN,-1.242929,-1.372019,NaN,NaN,0.257236,0.259064,NaN,NaN,159.402916,156.972010,142.970107,150.909607,-0.031600,1.072836,116.280182
2,202406050807,5,35.1,9,0.178354,0.195387,-0.124915,0.334316,0.941958,-0.137500,4,2,NaN,-0.616092,-0.663940,-0.770404,-1.371571,NaN,-0.336305,0.103450,NaN,NaN,-1.290632,-1.358921,NaN,NaN,138.779609,147.065400,132.387501,146.009607,-2.005446,-1.019751,116.140290
15,202406050807,14,29.1,8,0.242279,0.216123,-0.282944,-0.353451,1.042308,-0.279487,2,2,NaN,-0.616092,-0.663940,-0.770404,0.652495,NaN,0.400883,0.075065,NaN,NaN,0.704875,0.639229,NaN,NaN,170.846310,153.896815,170.846310,153.896815,1.063642,0.423259,116.116172
11,202406050807,1,55.5,12,0.182594,0.180707,0.340301,0.708205,1.192857,-0.194048,2,2,NaN,-0.616092,-0.663940,-0.770404,0.652495,NaN,0.037667,0.332907,NaN,NaN,0.605965,0.706967,NaN,NaN,171.157421,155.096815,171.157421,155.096815,1.093418,0.676736,116.109560
1,202406050807,3,60.5,13,0.196187,0.203274,0.143467,0.525719,1.640841,0.011464,3,2,NaN,NaN,-0.295084,-0.491060,-1.478100,NaN,-0.454543,-0.514743,NaN,NaN,-1.362802,-1.307375,NaN,NaN,169.520106,157.146946,133.041184,144.005129,0.936712,1.109788,115.844646
10,202406050807,9,44.7,10,0.219168,0.193460,0.156797,-0.317684,0.913376,-0.035741,2,2,NaN,0.136909,-0.663940,-0.770404,0.652495,NaN,-0.965958,-1.003273,NaN,NaN,0.332660,0.355937,NaN,NaN,165.216341,150.946274,153.012977,148.745192,0.524800,-0.199988,115.807545
5,202406050807,11,11.6,5,0.207064,0.221751,0.152428,-0.153053,1.945307,0.306646,2,2,NaN,NaN,0.442627,0.067626,0.652495,NaN,0.170961,0.510369,NaN,NaN,0.642264,0.753588,NaN,NaN,166.986711,157.012941,151.090754,153.696815,0.694242,1.081482,115.712797
7,202406050807,8,8.1,4,0.184862,0.223881,1.087624,1.022045,2.147302,-0.213418,2,2,NaN,NaN,0.995910,0.765983,0.652495,NaN,0.625757,1.783133,NaN,NaN,0.766113,1.087957,NaN,NaN,164.290754,154.896815,149.999068,144.605129,0.436213,0.634490,115.520988
12,202406050807,6,2.9,1,0.178354,0.171662,0.151725,0.276306,1.767847,0.118687,2,2,NaN,2.395912,0.442627,1.365618,0.652495,NaN,2.129998,0.969197,NaN,NaN,1.175744,0.874127,NaN,NaN,148.964092,145.171915,138.273307,144.345687,-1.030694,-1.419714,115.259366
9,202406050807,10,4.0,2,0.219168,0.229282,0.746096,0.071305,2.454489,0.178333,3,2,NaN,-0.616092,2.655760,1.743684,-1.478100,NaN,0.580520,0.596786,NaN,NaN,-1.644669,-1.599387,NaN,NaN,154.071063,149.641058,139.421290,143.405129,-0.541908,-0.475691,115.144089
4,202406050807,4,4.7,3,0.196187,0.211460,1.402602,1.202880,2.504242,0.131410,2,2,NaN,NaN,1.364766,2.050961,0.652495,NaN,1.684750,1.784346,NaN,NaN,1.054495,1.088276,NaN,NaN,161.347823,150.596274,125.665735,141.605129,0.154547,-0.273919,115.140090

### 12/22 第8回目レース

In [32]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050808",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [33]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050808,2019104952,1169,1064,1,1,24.1,8,56.0,1,5,NaN,NaN,16,4.125,4.0,4
1,202406050808,2020103575,1043,399,2,1,46.5,12,58.0,0,4,NaN,NaN,16,4.125,4.0,4
2,202406050808,2021101121,1126,1193,3,2,5.0,2,55.0,1,3,NaN,NaN,16,4.125,4.0,4
3,202406050808,2021100161,5626,1149,4,2,32.4,9,57.0,0,3,NaN,NaN,16,4.125,4.0,4
4,202406050808,2021106307,1092,1026,5,3,18.4,6,57.0,0,3,NaN,NaN,16,4.125,4.0,4
5,202406050808,2019105064,5625,1165,6,3,42.1,11,56.0,1,5,NaN,NaN,16,4.125,4.0,4
6,202406050808,2021105965,5386,1162,7,4,7.7,5,57.0,2,3,NaN,NaN,16,4.125,4.0,4
7,202406050808,2020102562,1117,1179,8,4,60.1,14,56.0,1,4,NaN,NaN,16,4.125,4.0,4
8,202406050808,2019100593,1161,1156,9,5,85.9,15,56.0,1,5,NaN,NaN,16,4.125,4.0,4
9,202406050808,2019100937,1032,1109,10,5,35.1,10,58.0,0,5,NaN,NaN,16,4.125,4.0,4
10,202406050808,2020101567,5366,1070,11,6,6.5,4,58.0,0,4,NaN,NaN,16,4.125,4.0,4
11,202406050808,2019106704,5339,1191,12,6,3.3,1,56.0,1,5,NaN,NaN,16,4.125,4.0,4
12,202406050808,2019103815,422,1024,13,7,90.5,16,56.0,1,5,NaN,NaN,16,4.125,4.0,4
13,202406050808,2019100871,1112,1084,14,7,22.0,7,58.0,0,5,NaN,NaN,16,4.125,4.0,4
14,202406050808,2021100338,1077,1179,15,8,55.3,13,55.0,1,3,NaN,NaN,16,4.125,4.0,4
15,202406050808,2020100363,1140,1047,16,8,5.8,3,58.0,0,4,NaN,NaN,16,4.125,4.0,4

In [34]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050808,0,0,1200,1,0,5,6,8,73875108,4,64,640,8,80,8,80,5,50,64080,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401200,-1,44,89,3.9

In [35]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
6,202406050808,15,55.3,13,0.208644,0.207792,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.796669,0.853428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.028558
9,202406050808,9,85.9,15,0.189940,0.183036,NaN,NaN,NaN,-0.439063,3,1,NaN,-1.312063,-0.810818,-0.796669,-1.139980,NaN,-1.078194,-0.305116,NaN,NaN,-0.936697,-0.968757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.288045
7,202406050808,10,35.1,10,0.189940,0.203593,-1.393966,-0.160778,1.676316,0.479795,3,1,NaN,0.201856,0.281057,0.457020,-1.139980,NaN,0.442312,0.593411,NaN,NaN,-1.227709,-1.140592,NaN,NaN,182.642726,159.040765,182.642726,159.040765,1.185837,-0.451453,72.839446
4,202406050808,13,90.5,16,0.205970,0.198157,0.095267,0.299677,2.080287,0.164861,2,1,NaN,0.201856,-0.507519,-0.408129,0.853428,NaN,0.858978,-0.001872,NaN,NaN,0.991216,0.931440,NaN,NaN,157.748297,154.113665,148.892772,150.240765,-1.133963,-1.101387,72.742633
15,202406050808,1,24.1,8,0.174194,0.188623,0.160181,-0.062573,2.561163,0.245631,2,1,NaN,-1.312063,-0.315430,-0.479362,0.853428,NaN,-0.024143,0.714971,NaN,NaN,0.822195,1.068530,NaN,NaN,174.555410,168.869814,169.498128,166.510128,0.432216,0.845097,72.697514
3,202406050808,2,46.5,12,0.174194,0.158209,-1.489218,-2.550584,2.897444,0.491566,3,1,NaN,-0.555104,-0.810818,-0.097297,-1.139980,NaN,-1.254361,-0.395383,NaN,NaN,-0.902981,-0.951495,NaN,NaN,183.551226,178.803643,143.129458,155.346912,1.270496,2.155468,72.695533
14,202406050808,4,32.4,9,0.179209,0.194362,-0.047156,0.519082,1.459545,0.967803,2,1,NaN,0.580336,-0.507519,-0.472886,0.853428,NaN,0.089844,-0.377438,NaN,NaN,0.844011,0.859617,NaN,NaN,188.294931,160.525700,170.228860,146.446314,1.712540,-0.255575,72.692382
12,202406050808,5,18.4,6,0.192982,0.177083,0.328672,-0.239489,2.277312,0.344167,2,1,NaN,1.715775,-0.305320,-0.343372,0.853428,NaN,1.409113,0.121518,NaN,NaN,1.096507,0.955038,NaN,NaN,163.986570,155.759579,141.228860,137.446314,-0.552646,-0.884274,72.686391
10,202406050808,14,22.0,7,0.205970,0.218553,-0.155710,0.406405,1.733061,0.072255,4,1,NaN,-1.312063,0.608619,0.112515,-1.040310,NaN,-0.162451,0.254681,NaN,NaN,-1.005631,-0.968582,NaN,NaN,166.286275,166.393910,162.600107,162.461473,-0.338347,0.518500,72.525776
8,202406050808,6,42.1,11,0.192982,0.209199,-0.464435,-0.425218,0.690703,-0.215404,3,1,NaN,0.958815,-0.810818,-0.602399,-1.139980,NaN,-1.802621,-1.784998,NaN,NaN,-0.798049,-0.685745,NaN,NaN,162.557953,163.757853,156.491286,156.045192,-0.685773,0.170778,72.386660
13,202406050808,8,60.1,14,0.176471,0.206538,-1.300907,-1.368591,0.907997,-0.109602,2,1,NaN,-0.555104,-0.810818,-0.602399,0.853428,NaN,-1.641008,-1.881344,NaN,NaN,0.512741,0.572010,NaN,NaN,165.557130,169.086934,149.792772,153.045192,-0.406293,0.873737,72.331189
2,202406050808,11,6.5,4,0.211510,0.181682,0.038279,0.107835,2.859975,0.493542,2,1,NaN,0.201856,-0.507519,-0.213859,0.853428,NaN,0.448112,-0.048367,NaN,NaN,0.912580,0.922549,NaN,NaN,182.720297,163.785003,162.676059,157.033001,1.193065,0.174359,72.133774
11,202406050808,3,5.0,2,0.179209,0.174107,1.272666,1.006211,1.857143,0.495556,2,1,NaN,0.580336,-0.204221,-0.116724,0.853428,NaN,1.148888,0.362339,NaN,NaN,1.046702,1.001092,NaN,NaN,167.317080,150.511779,144.836230,139.733666,-0.242291,-1.576512,72.059384
1,202406050808,16,5.8,3,0.208644,0.189895,2.100306,1.454218,2.611499,0.497507,4,1,NaN,-1.312063,2.028056,1.021699,-1.040310,NaN,0.479033,1.585714,NaN,NaN,-1.116128,-1.197674,NaN,NaN,170.231202,166.629241,164.497868,166.229241,0.029263,0.549543,71.736946
5,202406050808,7,7.7,5,0.176471,0.154762,0.001989,0.209918,1.325282,-0.012523,2,1,NaN,0.958815,0.281057,0.032216,0.853428,NaN,0.426767,-0.562821,NaN,NaN,0.908495,0.824165,NaN,NaN,156.652099,153.302256,135.828626,143.945687,-1.236113,-1.208420,71.730556
0,202406050808,12,3.3,1,0.211510,0.239394,0.854032,0.803886,2.579728,0.188829,4,1,NaN,0.958815,2.392014,3.306316,-1.040310,NaN,0.659733,1.724705,NaN,NaN,-1.147253,-1.221596,NaN,NaN,156.739271,163.904631,149.121818,155.155152,-1.227990,0.190139,71.592405

In [36]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
6,202406050808,15,55.3,13,0.208644,0.207792,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.796669,0.853428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.966975
9,202406050808,9,85.9,15,0.189940,0.183036,NaN,NaN,NaN,-0.439063,3,1,NaN,-1.312063,-0.810818,-0.796669,-1.139980,NaN,-1.078194,-0.305116,NaN,NaN,-0.936697,-0.968757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.895425
3,202406050808,2,46.5,12,0.174194,0.158209,-1.489218,-2.550584,2.897444,0.491566,3,1,NaN,-0.555104,-0.810818,-0.097297,-1.139980,NaN,-1.254361,-0.395383,NaN,NaN,-0.902981,-0.951495,NaN,NaN,183.551226,178.803643,143.129458,155.346912,1.270496,2.155468,73.313731
4,202406050808,13,90.5,16,0.205970,0.198157,0.095267,0.299677,2.080287,0.164861,2,1,NaN,0.201856,-0.507519,-0.408129,0.853428,NaN,0.858978,-0.001872,NaN,NaN,0.991216,0.931440,NaN,NaN,157.748297,154.113665,148.892772,150.240765,-1.133963,-1.101387,73.273589
7,202406050808,10,35.1,10,0.189940,0.203593,-1.393966,-0.160778,1.676316,0.479795,3,1,NaN,0.201856,0.281057,0.457020,-1.139980,NaN,0.442312,0.593411,NaN,NaN,-1.227709,-1.140592,NaN,NaN,182.642726,159.040765,182.642726,159.040765,1.185837,-0.451453,73.153570
14,202406050808,4,32.4,9,0.179209,0.194362,-0.047156,0.519082,1.459545,0.967803,2,1,NaN,0.580336,-0.507519,-0.472886,0.853428,NaN,0.089844,-0.377438,NaN,NaN,0.844011,0.859617,NaN,NaN,188.294931,160.525700,170.228860,146.446314,1.712540,-0.255575,73.078624
10,202406050808,14,22.0,7,0.205970,0.218553,-0.155710,0.406405,1.733061,0.072255,4,1,NaN,-1.312063,0.608619,0.112515,-1.040310,NaN,-0.162451,0.254681,NaN,NaN,-1.005631,-0.968582,NaN,NaN,166.286275,166.393910,162.600107,162.461473,-0.338347,0.518500,73.030828
13,202406050808,8,60.1,14,0.176471,0.206538,-1.300907,-1.368591,0.907997,-0.109602,2,1,NaN,-0.555104,-0.810818,-0.602399,0.853428,NaN,-1.641008,-1.881344,NaN,NaN,0.512741,0.572010,NaN,NaN,165.557130,169.086934,149.792772,153.045192,-0.406293,0.873737,72.965405
8,202406050808,6,42.1,11,0.192982,0.209199,-0.464435,-0.425218,0.690703,-0.215404,3,1,NaN,0.958815,-0.810818,-0.602399,-1.139980,NaN,-1.802621,-1.784998,NaN,NaN,-0.798049,-0.685745,NaN,NaN,162.557953,163.757853,156.491286,156.045192,-0.685773,0.170778,72.912331
2,202406050808,11,6.5,4,0.211510,0.181682,0.038279,0.107835,2.859975,0.493542,2,1,NaN,0.201856,-0.507519,-0.213859,0.853428,NaN,0.448112,-0.048367,NaN,NaN,0.912580,0.922549,NaN,NaN,182.720297,163.785003,162.676059,157.033001,1.193065,0.174359,72.836659
12,202406050808,5,18.4,6,0.192982,0.177083,0.328672,-0.239489,2.277312,0.344167,2,1,NaN,1.715775,-0.305320,-0.343372,0.853428,NaN,1.409113,0.121518,NaN,NaN,1.096507,0.955038,NaN,NaN,163.986570,155.759579,141.228860,137.446314,-0.552646,-0.884274,72.828344
15,202406050808,1,24.1,8,0.174194,0.188623,0.160181,-0.062573,2.561163,0.245631,2,1,NaN,-1.312063,-0.315430,-0.479362,0.853428,NaN,-0.024143,0.714971,NaN,NaN,0.822195,1.068530,NaN,NaN,174.555410,168.869814,169.498128,166.510128,0.432216,0.845097,72.788619
11,202406050808,3,5.0,2,0.179209,0.174107,1.272666,1.006211,1.857143,0.495556,2,1,NaN,0.580336,-0.204221,-0.116724,0.853428,NaN,1.148888,0.362339,NaN,NaN,1.046702,1.001092,NaN,NaN,167.317080,150.511779,144.836230,139.733666,-0.242291,-1.576512,72.630610
5,202406050808,7,7.7,5,0.176471,0.154762,0.001989,0.209918,1.325282,-0.012523,2,1,NaN,0.958815,0.281057,0.032216,0.853428,NaN,0.426767,-0.562821,NaN,NaN,0.908495,0.824165,NaN,NaN,156.652099,153.302256,135.828626,143.945687,-1.236113,-1.208420,72.558992
1,202406050808,16,5.8,3,0.208644,0.189895,2.100306,1.454218,2.611499,0.497507,4,1,NaN,-1.312063,2.028056,1.021699,-1.040310,NaN,0.479033,1.585714,NaN,NaN,-1.116128,-1.197674,NaN,NaN,170.231202,166.629241,164.497868,166.229241,0.029263,0.549543,72.097297
0,202406050808,12,3.3,1,0.211510,0.239394,0.854032,0.803886,2.579728,0.188829,4,1,NaN,0.958815,2.392014,3.306316,-1.040310,NaN,0.659733,1.724705,NaN,NaN,-1.147253,-1.221596,NaN,NaN,156.739271,163.904631,149.121818,155.155152,-1.227990,0.190139,71.812458

### 12/22 第12回目レース

In [37]:
# 特徴量の更新
features = pfc.create_features(
    race_id="202406050812",  # 予測するレースidを指定
    date_content_a = "2024年12月22日", #"%Y年%m月%d日"形式で該当レース当日の日付を入れてください    
    skip_agg_horse=True  # 事前に集計した場合はスキップできる
)

fetching shutuba page html...
fetching shutuba page html...comp
0    2023
Name: date_year, dtype: int32
running cross_features()...comp
running agg_interval()...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:641: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["place_course_category"] = df["place_course_category"].fillna(-1).astype(int)
/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[['goal_range', 'curve', 'goal_slope']] = df[['goal_range', 'curve', 'goal_slope']].fillna(-1).astype(int)

running cross_features_2()...comp

agg_cross_encoded:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_3()...comp

agg_cross_zizoku_syunpatu:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_4()...comp
running cross_features_5()...comp
running cross_features_6()...comp

pace_category_win_1:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_2:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_3:   0%|          | 0/4 [00:00<?, ?it/s]

pace_category_win_4:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_7()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_8()...comp

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_9()...comp

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_10()...comp

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_11()...comp

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_12()...comp

agg_pace_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_curve_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_goal_slope_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

agg_stamina_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_13()...comp

agg_raceclass_rankdiff_per_score:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_14()...comp

speed_index:   0%|          | 0/4 [00:00<?, ?it/s]

running cross_features_15()...comp

agg_horse_per_course_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_ground_state_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_grade:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_type:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place_len:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_race_place:   0%|          | 0/4 [00:00<?, ?it/s]

agg_horse_per_weather:   0%|          | 0/4 [00:00<?, ?it/s]

running agg_jockey()...
running agg_trainer()...
running agg_sire()...
running agg_bms()...
running agg_bms()...comp
merging all features...
merging all features...comp

/Users/iniad/Documents/kenkyu_4/dirt/src/feature_engineering_prediction.py:6373: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  features["goal_range_100"] = features["goal_range_100"].fillna(-1)

In [38]:
pfc.results

,race_id,horse_id,jockey_id,trainer_id,umaban,wakuban,tansho_odds,popularity,impost,sex,age,weight,weight_diff,n_horses,mean_age,median_age,mean_age_kirisute
0,202406050812,2019102521,732,1028,1,1,24.2,9,58.0,0,5,NaN,NaN,16,4.5,5.0,4
1,202406050812,2019105058,1179,1068,2,1,6.6,3,58.0,2,5,NaN,NaN,16,4.5,5.0,4
2,202406050812,2019103562,1077,1028,3,2,34.4,11,58.0,0,5,NaN,NaN,16,4.5,5.0,4
3,202406050812,2019102753,1032,1033,4,2,37.9,12,56.0,1,5,NaN,NaN,16,4.5,5.0,4
4,202406050812,2019101185,5626,1192,5,3,28.5,10,58.0,0,5,NaN,NaN,16,4.5,5.0,4
5,202406050812,2018106560,422,1062,6,3,43.6,14,58.0,0,6,NaN,NaN,16,4.5,5.0,4
6,202406050812,2019105032,1157,1167,7,4,46.3,15,58.0,0,5,NaN,NaN,16,4.5,5.0,4
7,202406050812,2020104228,5366,1176,8,4,5.8,2,58.0,0,4,NaN,NaN,16,4.5,5.0,4
8,202406050812,2020102238,1138,1104,9,5,103.8,16,58.0,0,4,NaN,NaN,16,4.5,5.0,4
9,202406050812,2020110136,1126,427,10,5,8.2,4,58.0,0,4,NaN,NaN,16,4.5,5.0,4
10,202406050812,2019104561,5386,1103,11,6,21.2,7,58.0,0,5,NaN,NaN,16,4.5,5.0,4
11,202406050812,2021101535,1122,1086,12,6,22.0,8,55.0,1,3,NaN,NaN,16,4.5,5.0,4
12,202406050812,2021101737,1096,1142,13,7,17.1,6,57.0,0,3,NaN,NaN,16,4.5,5.0,4
13,202406050812,2020105250,5625,1094,14,7,42.6,13,58.0,0,4,NaN,NaN,16,4.5,5.0,4
14,202406050812,2021110136,1163,1071,15,8,2.6,1,57.0,0,3,NaN,NaN,16,4.5,5.0,4
15,202406050812,2018103641,1117,1043,16,8,14.3,5,58.0,0,6,NaN,NaN,16,4.5,5.0,4

In [39]:
pfc.race_info

,race_id,race_type,around,course_len,weather,ground_state,race_class,place,race_day_count,race_date_day_count,season,place_season,place_season_type,kaisai_race,kaisai_race_type,day,day_type,kaisai_count,kaisai_count_type,place_season_day_type,day_condition,place_season_condition_type,place_season_condition_type_categori,place_course_category,place_course_tough,goal_range,curve,goal_slope,goal_range_100,place_season_type_course_len,lap_type,age_season,race_grade,race_grade_scaled
0,202406050812,0,0,1200,1,0,4,6,12,73875112,4,64,640,12,120,8,80,5,50,64080,2,6420,-3,-1,-1,-1,-1,-1,NaN,6401200,-1,44,85,3.5

In [40]:
# オッズ除外モデルでの予測、time、ホールドアウト
prediction.predict(
    features,
    model_filename="model_lightgbm_time_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
2,202406050812,13,17.1,6,0.205970,0.198157,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.593264,0.749788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758718
6,202406050812,9,103.8,16,0.189940,0.183036,-1.861669,-0.789936,0.844048,-0.055029,4,1,NaN,-0.83666,-0.584497,-0.593264,-1.165637,NaN,-1.468711,-1.387207,NaN,NaN,-0.742596,-0.652182,NaN,NaN,170.156990,173.500000,170.156990,173.500000,-1.073741,1.040239,73.231121
15,202406050812,16,14.3,5,0.208644,0.189895,0.568205,0.718570,NaN,1.701389,2,1,NaN,-0.83666,-0.584497,-0.027052,0.749788,NaN,-0.059866,-0.105030,NaN,NaN,0.713074,0.735606,NaN,NaN,NaN,NaN,175.201961,167.600000,NaN,NaN,72.492899
10,202406050812,14,42.6,13,0.205970,0.218553,-0.849386,-1.842587,1.556795,-0.136218,2,1,NaN,0.83666,-0.584497,0.023278,0.749788,NaN,-0.915002,-1.104235,NaN,NaN,0.487802,0.441870,NaN,NaN,165.035294,170.100000,154.768627,168.500000,-1.812311,0.287555,72.377311
8,202406050812,3,34.4,11,0.179209,0.174107,-0.363775,-0.882811,1.200000,0.038542,3,1,NaN,0.83666,-0.584497,-0.593264,-1.266449,NaN,-0.806212,-0.593934,NaN,NaN,-0.986163,-0.942916,NaN,NaN,182.415880,173.300000,182.415880,171.000000,0.694042,0.995963,72.285446
3,202406050812,4,37.9,12,0.179209,0.194362,-0.697938,-0.690358,2.375563,0.173712,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,-0.341065,-0.433604,NaN,NaN,0.638996,0.639015,NaN,NaN,175.593277,167.133333,164.638634,164.500000,-0.289806,-0.369199,72.247876
7,202406050812,1,24.2,9,0.174194,0.188623,-1.992054,-1.285937,NaN,-0.038803,2,1,NaN,-0.83666,-0.584497,-0.027052,0.749788,NaN,-1.012377,-1.218016,NaN,NaN,0.462150,0.408422,NaN,NaN,182.292312,168.366667,179.117382,166.200000,0.676223,-0.096166,72.174437
13,202406050812,6,43.6,14,0.192982,0.209199,0.221403,0.388274,1.293354,-0.177105,3,1,NaN,-0.83666,-0.584497,-0.593264,-1.266449,NaN,-0.571613,-0.319811,NaN,NaN,-1.047964,-1.023500,NaN,NaN,179.928276,170.766667,161.406227,166.700000,0.335319,0.435140,72.046039
11,202406050812,7,46.3,15,0.176471,0.154762,-0.116478,-0.687318,0.929032,0.252957,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,-1.244904,-1.489717,NaN,NaN,0.400894,0.328551,NaN,NaN,181.182723,166.900000,178.951825,166.900000,0.516216,-0.420853,71.896005
5,202406050812,5,28.5,10,0.192982,0.177083,0.256476,0.371546,3.077077,0.658333,3,1,NaN,0.00000,0.234695,-0.102547,-1.266449,NaN,0.614849,0.759752,NaN,NaN,-1.360519,-1.340858,NaN,NaN,173.320177,170.162661,168.898128,167.329241,-0.617596,0.301427,71.878981
9,202406050812,11,21.2,7,0.211510,0.181682,0.341169,0.175276,4.030839,1.568325,3,1,NaN,1.67332,3.120774,3.488495,-1.266449,NaN,0.660572,1.031634,NaN,NaN,-1.372564,-1.420783,NaN,NaN,183.255410,173.569814,132.107567,139.645687,0.815106,1.055694,71.803366
14,202406050812,12,22.0,8,0.211510,0.239394,0.441018,-0.043604,1.453030,0.588250,2,1,NaN,0.83666,0.234695,0.274927,0.749788,NaN,0.809417,0.741023,NaN,NaN,0.942073,0.984319,NaN,NaN,185.821947,163.469684,171.009167,148.833001,1.185211,-1.180248,71.745985
1,202406050812,10,8.2,4,0.189940,0.203593,0.960379,1.635996,2.577061,0.818944,2,1,NaN,0.83666,0.444745,0.023278,0.749788,NaN,0.814080,0.916798,NaN,NaN,0.943301,1.035992,NaN,NaN,186.479789,172.313209,175.564795,170.710128,1.280075,0.777510,71.701413
12,202406050812,2,6.6,3,0.174194,0.158209,1.272864,0.787911,NaN,-0.226275,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,1.063914,1.242844,NaN,NaN,1.009116,1.131839,NaN,NaN,169.000107,160.861473,169.000107,160.861473,-1.240569,-1.757648,71.685318
0,202406050812,15,2.6,1,0.208644,0.207792,1.273602,1.358285,3.833390,0.782167,2,1,NaN,1.67332,0.864843,0.526577,0.749788,NaN,1.953691,1.023390,NaN,NaN,1.243514,1.067327,NaN,NaN,170.130330,160.438076,160.362791,146.148665,-1.077586,-1.851378,71.564476
4,202406050812,8,5.8,2,0.176471,0.206538,0.546182,0.786696,3.260276,1.127563,3,1,NaN,-0.83666,0.360725,-0.027052,-1.266449,NaN,0.503229,0.936114,NaN,NaN,-1.331114,-1.392703,NaN,NaN,181.829024,172.333333,178.168627,171.000000,0.609415,0.781965,71.516862

In [41]:
# オッズ除外モデルでの予測、time、クロスバリデーション
prediction.predict(
    features,
    model_filename="model_lightgbm_time_cv_full_odds_removed.pkl",
    config_filepath="config_lightgbm_kaiki_odds_removed.yaml"
)

,race_id,umaban,tansho_odds,popularity,mean_fukusho_rate_wakuban,mean_fukusho_rate_umaban,distance_place_type_ground_state_encoded_time_diff_mean_3races_cross_encoded_relative,distance_place_type_ground_state_encoded_time_diff_min_3races_cross_encoded_relative,syunpatu_mean_3races_encoded,zizoku_mean_3races_encoded,dominant_position_category,pace_category,ground_state_level,rentai_for_pace_category_n5_relative,score_pace_potision_mean_3races_per_score_raw_relative,mean_5races_sum_relative,tenkai_combined_standardized,tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_plus_tenkai_all_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_combined_standardized,race_grade_rank_diff_sum_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,race_grade_rank_diff_multi_mean_3races_grade_rankdiff_score_px_tenkai_all_combined_standardized,speed_index_mean_3races,nobori_index_mean_3races,speed_index_min_5races,nobori_index_min_5races,speed_index_mean_3races_relative,nobori_index_mean_3races_relative,pred
2,202406050812,13,17.1,6,0.205970,0.198157,NaN,NaN,NaN,NaN,2,1,NaN,NaN,NaN,-0.593264,0.749788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.809553
10,202406050812,14,42.6,13,0.205970,0.218553,-0.849386,-1.842587,1.556795,-0.136218,2,1,NaN,0.83666,-0.584497,0.023278,0.749788,NaN,-0.915002,-1.104235,NaN,NaN,0.487802,0.441870,NaN,NaN,165.035294,170.100000,154.768627,168.500000,-1.812311,0.287555,73.216110
6,202406050812,9,103.8,16,0.189940,0.183036,-1.861669,-0.789936,0.844048,-0.055029,4,1,NaN,-0.83666,-0.584497,-0.593264,-1.165637,NaN,-1.468711,-1.387207,NaN,NaN,-0.742596,-0.652182,NaN,NaN,170.156990,173.500000,170.156990,173.500000,-1.073741,1.040239,73.164002
8,202406050812,3,34.4,11,0.179209,0.174107,-0.363775,-0.882811,1.200000,0.038542,3,1,NaN,0.83666,-0.584497,-0.593264,-1.266449,NaN,-0.806212,-0.593934,NaN,NaN,-0.986163,-0.942916,NaN,NaN,182.415880,173.300000,182.415880,171.000000,0.694042,0.995963,73.115630
15,202406050812,16,14.3,5,0.208644,0.189895,0.568205,0.718570,NaN,1.701389,2,1,NaN,-0.83666,-0.584497,-0.027052,0.749788,NaN,-0.059866,-0.105030,NaN,NaN,0.713074,0.735606,NaN,NaN,NaN,NaN,175.201961,167.600000,NaN,NaN,72.775775
7,202406050812,1,24.2,9,0.174194,0.188623,-1.992054,-1.285937,NaN,-0.038803,2,1,NaN,-0.83666,-0.584497,-0.027052,0.749788,NaN,-1.012377,-1.218016,NaN,NaN,0.462150,0.408422,NaN,NaN,182.292312,168.366667,179.117382,166.200000,0.676223,-0.096166,72.756253
3,202406050812,4,37.9,12,0.179209,0.194362,-0.697938,-0.690358,2.375563,0.173712,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,-0.341065,-0.433604,NaN,NaN,0.638996,0.639015,NaN,NaN,175.593277,167.133333,164.638634,164.500000,-0.289806,-0.369199,72.753887
11,202406050812,7,46.3,15,0.176471,0.154762,-0.116478,-0.687318,0.929032,0.252957,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,-1.244904,-1.489717,NaN,NaN,0.400894,0.328551,NaN,NaN,181.182723,166.900000,178.951825,166.900000,0.516216,-0.420853,72.538792
13,202406050812,6,43.6,14,0.192982,0.209199,0.221403,0.388274,1.293354,-0.177105,3,1,NaN,-0.83666,-0.584497,-0.593264,-1.266449,NaN,-0.571613,-0.319811,NaN,NaN,-1.047964,-1.023500,NaN,NaN,179.928276,170.766667,161.406227,166.700000,0.335319,0.435140,72.470376
12,202406050812,2,6.6,3,0.174194,0.158209,1.272864,0.787911,NaN,-0.226275,2,1,NaN,-0.83666,-0.584497,-0.593264,0.749788,NaN,1.063914,1.242844,NaN,NaN,1.009116,1.131839,NaN,NaN,169.000107,160.861473,169.000107,160.861473,-1.240569,-1.757648,72.445228
5,202406050812,5,28.5,10,0.192982,0.177083,0.256476,0.371546,3.077077,0.658333,3,1,NaN,0.00000,0.234695,-0.102547,-1.266449,NaN,0.614849,0.759752,NaN,NaN,-1.360519,-1.340858,NaN,NaN,173.320177,170.162661,168.898128,167.329241,-0.617596,0.301427,72.416375
9,202406050812,11,21.2,7,0.211510,0.181682,0.341169,0.175276,4.030839,1.568325,3,1,NaN,1.67332,3.120774,3.488495,-1.266449,NaN,0.660572,1.031634,NaN,NaN,-1.372564,-1.420783,NaN,NaN,183.255410,173.569814,132.107567,139.645687,0.815106,1.055694,72.396363
14,202406050812,12,22.0,8,0.211510,0.239394,0.441018,-0.043604,1.453030,0.588250,2,1,NaN,0.83666,0.234695,0.274927,0.749788,NaN,0.809417,0.741023,NaN,NaN,0.942073,0.984319,NaN,NaN,185.821947,163.469684,171.009167,148.833001,1.185211,-1.180248,72.346164
1,202406050812,10,8.2,4,0.189940,0.203593,0.960379,1.635996,2.577061,0.818944,2,1,NaN,0.83666,0.444745,0.023278,0.749788,NaN,0.814080,0.916798,NaN,NaN,0.943301,1.035992,NaN,NaN,186.479789,172.313209,175.564795,170.710128,1.280075,0.777510,72.315250
0,202406050812,15,2.6,1,0.208644,0.207792,1.273602,1.358285,3.833390,0.782167,2,1,NaN,1.67332,0.864843,0.526577,0.749788,NaN,1.953691,1.023390,NaN,NaN,1.243514,1.067327,NaN,NaN,170.130330,160.438076,160.362791,146.148665,-1.077586,-1.851378,72.314114
4,202406050812,8,5.8,2,0.176471,0.206538,0.546182,0.786696,3.260276,1.127563,3,1,NaN,-0.83666,0.360725,-0.027052,-1.266449,NaN,0.503229,0.936114,NaN,NaN,-1.331114,-1.392703,NaN,NaN,181.829024,172.333333,178.168627,171.000000,0.609415,0.781965,71.768902