In [1]:
import create_population
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction

import pandas as pd


import html5lib

from train_lightgbm_rank_niti import Trainer_lightgbm_rank_niti
from train_lightgbm_time import Trainer_lightgbm_time
from train_lightgbm_rank_kaiki import Trainer_lightgbm_rank_kaiki


from evaluation_lightgbm_rank_niti import Evaluator_lightgbm_rank_niti
from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki
from evaluation_lightgbm_rank_kaiki import Evaluator_lightgbm_rank_kaiki
from evaluation_pop import Evaluator_pop

%load_ext autoreload

In [2]:
%autoreload

In [2]:
population = create_population.create(from_="2023-01-01", to_="2023-12-31")

In [13]:
population

            race_id        date    horse_id
0      202306010101  2023-01-05  2020103575
1      202306010101  2023-01-05  2020107073
2      202306010101  2023-01-05  2020102562
3      202306010101  2023-01-05  2020106345
4      202306010101  2023-01-05  2020100039
...             ...         ...         ...
42828  202309050912  2023-12-28  2017104873
42829  202309050912  2023-12-28  2019100653
42830  202309050912  2023-12-28  2017106240
42831  202309050912  2023-12-28  2018103205
42832  202309050912  2023-12-28  2017102603

[42833 rows x 3 columns]

In [4]:
population = create_population.create(from_="2020-01-01", to_="2023-12-31")

In [3]:
import json
from pathlib import Path

import pandas as pd
import numpy as np
import ast
COMMON_DATA_DIR = Path("..", "..", "common", "data")
RAWDF_DIR = COMMON_DATA_DIR / "rawdf"
MAPPING_DIR = COMMON_DATA_DIR / "mapping"
POPULATION_DIR = Path("..", "data", "00_population")
OUTPUT_DIR = Path("..", "data", "01_preprocessed")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# カテゴリ変数を数値に変換するためのマッピング
with open(MAPPING_DIR / "sex.json", "r") as f:
    sex_mapping = json.load(f)
with open(MAPPING_DIR / "race_type.json", "r") as f:
    race_type_mapping = json.load(f)
with open(MAPPING_DIR / "around.json", "r") as f:
    around_mapping = json.load(f)
with open(MAPPING_DIR / "weather.json", "r") as f:
    weather_mapping = json.load(f)
with open(MAPPING_DIR / "ground_state.json", "r") as f:
    ground_state_mapping = json.load(f)
with open(MAPPING_DIR / "race_class.json", "r") as f:
    race_class_mapping = json.load(f)
with open(MAPPING_DIR / "place.json", "r") as f:
    place_mapping = json.load(f)

In [9]:
#race_infoをいじる
population_dir = POPULATION_DIR
populaton_filename = "population.csv"
input_dir = RAWDF_DIR
output_dir = OUTPUT_DIR
input_filename = "race_info.csv"
output_filename = "race_info.csv"
race_type_mapping = race_type_mapping
around_mapping = around_mapping
weather_mapping = weather_mapping
ground_state_mapping = ground_state_mapping
race_class_mapping = race_class_mapping

In [13]:
population = pd.read_csv(population_dir / populaton_filename, sep="\t")
population_race_ids = population['race_id'].tolist()

# クエリでリストを直接使用
df = pd.read_csv(input_dir / input_filename, sep="\t").query(
    "race_id in @population_race_ids"
)

# df = pd.read_csv(input_dir / input_filename, sep="\t").query(
#     "race_id in @population['race_id']"
# )

# evalで文字列型の列をリスト型に変換し、一時的な列を作成
df["tmp"] = df["info1"].map(lambda x: eval(x)[0])

# info1 列からコースの長さを取り出して tmp 列を作成
df["tmp2"] = df["info1"].map(lambda x: ast.literal_eval(x))

# tmp 列から距離の部分を抽出
df["course_len_1"] = df["tmp2"].map(lambda x: x[0]).str.extract(r"(\d+)")
df["course_len_2"] = df["tmp2"].map(lambda x: x[1]).str.extract(r"(\d+)")
df["combined_course_len"] = df["course_len_1"].fillna(df["course_len_2"])


# ダートor芝or障害
df["race_type"] = df["tmp"].str[0].map(race_type_mapping)
# 右or左or直線
df["around"] = df["tmp"].str[1].map(around_mapping)
df["course_len"] = df["course_len_1"].fillna(df["course_len_2"])
# df["course_len"] = df["tmp"].str.extract(r"(\d+)")
# df["course_len"] = df["tmp"].str.extract(r"(\d+)(?=m)")

df["weather"] = df["info1"].str.extract(r"天候:(\w+)")[0].map(weather_mapping)
df["ground_state"] = (
    df["info1"].str.extract(r"(芝|ダート|障害):(\w+)")[1].map(ground_state_mapping)
)
df["date"] = pd.to_datetime(
    df["info2"].map(lambda x: eval(x)[0]), format="%Y年%m月%d日"
)
regex_race_class = "|".join(race_class_mapping)
df["race_class"] = (
    df["title"]
    .str.extract(rf"({regex_race_class})")
    # タイトルからレース階級情報が取れない場合はinfo2から取得
    .fillna(df["info2"].str.extract(rf"({regex_race_class})"))[0]
    .map(race_class_mapping)
)
df["place"] = df["race_id"].astype(str).str[4:6].astype(int)
df.dropna(subset=["place"], inplace=True)


# 距離タイプ
df["distance_type"] = df["race_type"].astype(str) + df["combined_course_len"].astype(str)

# 距離競馬場タイプ
df["distance_place_type"] = df["race_type"].astype(str) + df["place"].astype(str) + df["combined_course_len"].astype(str)

# 距離競馬場タイプレースランク
df["distance_place_type_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str) + df["place"].astype(str) + df["combined_course_len"].astype(str) 


# 距離競馬場タイプ枠順
df["distance_place_type_wakuban"] = df["race_type"].astype(str) + df["place"].astype(str) + df["wakuban"].astype(str) +df["combined_course_len"].astype(str) 

# 距離競馬場タイプ馬番
df["distance_place_type_umaban"] = df["race_type"].astype(str) + df["place"].astype(str) + df["umaban"].astype(str) +df["combined_course_len"].astype(str) 

# 距離競馬場タイプ枠順レースランク
df["distance_place_type_wakuban_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str)) + df["place"].astype(str) + df["wakuban"].astype(str) +df["combined_course_len"].astype(str)

# 距離競馬場タイプ馬番レースランク
df["distance_place_type_umaban_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str)) + df["place"].astype(str) + df["umaban"].astype(str) +df["combined_course_len"].astype(str)

df

,race_id,title,info1,info2,tmp,tmp2,course_len_1,course_len_2,combined_course_len,race_type,around,course_len,weather,ground_state,date,race_class,place,distance_type,distance_place_type,distance_place_type_race_class
27075,202306050101,2歳未勝利,"['ダ右1200m', '天候:晴', 'ダート:良', '発走:10:05']","['2023年12月2日', '5回中山1日目', '2歳未勝利', '指', '馬齢']",ダ右1200m,"[ダ右1200m, 天候:晴, ダート:良, 発走:10:05]",1200,NaN,1200,0,0.0,1200,1,0,2023-12-02,1,6,12000,120060,1200601
27076,202306050102,2歳未勝利,"['ダ右1800m', '天候:晴', 'ダート:良', '発走:10:35']","['2023年12月2日', '5回中山1日目', '2歳未勝利', '牝', '指', '...",ダ右1800m,"[ダ右1800m, 天候:晴, ダート:良, 発走:10:35]",1800,NaN,1800,0,0.0,1800,1,0,2023-12-02,1,6,18000,180060,1800601
27077,202306050103,2歳未勝利,"['芝右外1600m', '天候:晴', '芝:良', '発走:11:05']","['2023年12月2日', '5回中山1日目', '2歳未勝利', '指', '馬齢']",芝右外1600m,"[芝右外1600m, 天候:晴, 芝:良, 発走:11:05]",1600,NaN,1600,1,0.0,1600,1,0,2023-12-02,1,6,16001,160061,1600611
27078,202306050104,2歳未勝利,"['ダ右1800m', '天候:晴', 'ダート:良', '発走:11:35']","['2023年12月2日', '5回中山1日目', '2歳未勝利', '混', '指', '...",ダ右1800m,"[ダ右1800m, 天候:晴, ダート:良, 発走:11:35]",1800,NaN,1800,0,0.0,1800,1,0,2023-12-02,1,6,18000,180060,1800601
27079,202306050105,2歳新馬,"['芝右外1200m', '天候:晴', '芝:良', '発走:12:25']","['2023年12月2日', '5回中山1日目', '2歳新馬', '混', '指', '馬齢']",芝右外1200m,"[芝右外1200m, 天候:晴, 芝:良, 発走:12:25]",1200,NaN,1200,1,0.0,1200,1,0,2023-12-02,0,6,12001,120061,1200610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27358,202309050908,3歳以上1勝クラス,"['ダ右1400m', '天候:晴', 'ダート:良', '発走:13:40']","['2023年12月28日', '5回阪神9日目', '3歳以上1勝クラス', '混', '...",ダ右1400m,"[ダ右1400m, 天候:晴, ダート:良, 発走:13:40]",1400,NaN,1400,0,0.0,1400,1,0,2023-12-28,2,9,14000,140090,1400902
27359,202309050909,春待月賞(2勝),"['ダ右1800m', '天候:晴', 'ダート:良', '発走:14:15', '過去の春...","['2023年12月28日', '5回阪神9日目', '3歳以上2勝クラス', '混', '...",ダ右1800m,"[ダ右1800m, 天候:晴, ダート:良, 発走:14:15, 過去の春待月賞]",1800,NaN,1800,0,0.0,1800,1,0,2023-12-28,3,9,18000,180090,1800903
27360,202309050910,フォーチュンカップ(2勝),"['芝右2000m', '天候:晴', '芝:良', '発走:14:50', '過去のフォー...","['2023年12月28日', '5回阪神9日目', '3歳以上2勝クラス', '混', '...",芝右2000m,"[芝右2000m, 天候:晴, 芝:良, 発走:14:50, 過去のフォーチュンカップ]",2000,NaN,2000,1,0.0,2000,1,0,2023-12-28,3,9,20001,200091,2000913
27361,202309050911,ベテルギウスS(L),"['ダ右1800m', '天候:晴', 'ダート:良', '発走:15:30', '過去のベ...","['2023年12月28日', '5回阪神9日目', '3歳以上オープン', '国際', '...",ダ右1800m,"[ダ右1800m, 天候:晴, ダート:良, 発走:15:30, 過去のベテルギウスS]",1800,NaN,1800,0,0.0,1800,1,0,2023-12-28,5,9,18000,180090,1800905
27362,202309050912,カウントダウンS(3勝),"['芝右1200m', '天候:晴', '芝:良', '発走:16:05', '過去のカウン...","['2023年12月28日', '5回阪神9日目', '3歳以上3勝クラス', '混', '...",芝右1200m,"[芝右1200m, 天候:晴, 芝:良, 発走:16:05, 過去のカウントダウンS]",1200,NaN,1200,1,0.0,1200,1,0,2023-12-28,4,9,12001,120091,1200914

In [48]:
population_dir= POPULATION_DIR
populaton_filename = "population.csv"
input_dir = RAWDF_DIR
output_dir = OUTPUT_DIR
input_filename = "horse_results.csv"
output_filename = "horse_results.csv"
race_type_mapping = race_type_mapping
weather_mapping= weather_mapping
ground_state_mapping = ground_state_mapping
race_class_mapping = race_class_mapping
place_mapping = place_mapping

"""
未加工の馬の過去成績テーブルをinput_dirから読み込んで加工し、
output_dirに保存する関数。
"""
population = pd.read_csv(population_dir / populaton_filename, sep="\t")
# df = pd.read_csv(input_dir / input_filename, sep="\t").query(
#     "horse_id in @population['horse_id']"
# )
population_horse_ids = population['horse_id'].tolist()

# クエリでリストを直接使用
df = pd.read_csv(input_dir / input_filename, sep="\t").query(
    "horse_id in @population_horse_ids"
)

df["rank"] = pd.to_numeric(df["着順"], errors="coerce")
df.dropna(subset=["rank"], inplace=True)
df["date"] = pd.to_datetime(df["日付"])
df["weather"] = df["天気"].map(weather_mapping)
df["race_type"] = df["距離"].str[0].map(race_type_mapping)
df["course_len"] = df["距離"].str.extract(r"(\d+)").astype(int)
df["ground_state"] = df["馬場"].map(ground_state_mapping)
df["rank_diff"] = df["着差"].map(lambda x: 0 if x < 0 else x)
df["prize"] = df["賞金"].fillna(0)

df["nobori"] = df["上り"].astype(float)

regex_race_class = "|".join(race_class_mapping)
df["race_class"] = (
    df["レース名"].str.extract(rf"({regex_race_class})")[0].map(race_class_mapping)
)
df["time"] = pd.to_datetime(df["タイム"], format="%M:%S.%f", errors="coerce")
df["time"] = (
    df["time"].dt.minute * 60
    + df["time"].dt.second
    + df["time"].dt.microsecond / 1000000
)
df["win"] = (df["rank"] == 1).astype(int)
df["rentai"] = (df["rank"] <= 2).astype(int)
df["show"] = (df["rank"] <= 3).astype(int)
df["place"] = df["開催"].str.extract(r"(\D+)")[0].map(place_mapping)
df.dropna(subset=["place"], inplace=True)    
df.rename(columns={"頭数": "n_horses"}, inplace=True)

pase_cols = df['ペース'].str.split('-', expand=True)
pase_cols.columns = [f'pase_{i+1}' for i in range(pase_cols.shape[1])]

# データ型変換と型確認
pase_cols = pase_cols.apply(pd.to_numeric, errors='coerce').astype('float64')

# 元のデータフレームと結合
df = pd.concat([df, pase_cols], axis=1)

# NoneをNaNに置き換え
# df = df.where(pd.notnull(df), np.nan)
df["umaban"] = df["馬番"].astype(int)
df["wakuban"] = df["枠番"].astype(int)

# コーナー通過順を分割して列を作成
corner_cols = df['通過'].str.split('-', expand=True)
corner_cols.columns = [f'corner_{i+1}' for i in range(corner_cols.shape[1])]
# オブジェクト型のデータを整数型に変換する
corner_cols = corner_cols.apply(pd.to_numeric, errors='coerce').astype('Int64')  
# nullable int型を指定
# 元のデータフレームと結合
df = pd.concat([df, corner_cols], axis=1)

# NoneをNaNに置き換え
df = df.where(pd.notnull(df), np.nan)

df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)

print(df[["race_type", "race_class", "place", "course_len"]].dtypes)


# rank / n_horses の特徴量を作成（欠損値を含む行はNaNに設定）
df["rank_per_horse"] = df["rank"].where(df["rank"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)

# corner_1 / n_horses の特徴量を作成（欠損値を含む行はNaNに設定）
df["corner_1_per_horse"] = df["corner_1"].where(df["corner_1"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)

df["corner_2_per_horse"] = df["corner_2"].where(df["corner_2"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)
df["corner_3_per_horse"] = df["corner_3"].where(df["corner_3"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)
df["corner_4_per_horse"] = df["corner_4"].where(df["corner_4"].notna(), np.nan) / df["n_horses"].where(df["n_horses"].notna(), np.nan)




# 距離タイプ
df["distance_type"] = df["race_type"].astype(str) + df["course_len"].astype(str)

# 距離競馬場タイプ
df["distance_place_type"] = df["race_type"].astype(str) + df["place"].astype(str) + df["course_len"].astype(str)

# 距離競馬場タイプレースランク
df["distance_place_type_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str) + df["place"].astype(str) + df["course_len"].astype(str)


# 距離競馬場タイプ枠順
df["distance_place_type_wakuban"] = df["race_type"].astype(str) + df["place"].astype(str) + df["wakuban"].astype(str) + df["course_len"].astype(str)

# 距離競馬場タイプ馬番
df["distance_place_type_umaban"] = df["race_type"].astype(str) + df["place"].astype(str) + df["umaban"].astype(str) + df["course_len"].astype(str)

# 距離競馬場タイプ枠順レースランク
df["distance_place_type_wakuban_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str) + df["place"].astype(str) + df["wakuban"].astype(str) +df["course_len"].astype(str)

# 距離競馬場タイプ馬番レースランク
df["distance_place_type_umaban_race_class"] = df["race_type"].astype(str) + df["race_class"].astype(str) + df["place"].astype(str) + df["umaban"].astype(str) +df["course_len"].astype(str)


# NoneをNaNに置き換え
df = df.where(pd.notnull(df), np.nan)
# 使用する列を選択
pd.options.display.float_format = '{:.0f}'.format  # 整数表示に変更

df

race_type     int64
race_class    int64
place         int64
course_len    int64
dtype: object

,horse_id,日付,開催,天気,R,レース名,映像,n_horses,枠番,馬番,...,corner_2_per_horse,corner_3_per_horse,corner_4_per_horse,distance_type,distance_place_type,distance_place_type_race_class,distance_place_type_wakuban,distance_place_type_umaban,distance_place_type_wakuban_race_class,distance_place_type_umaban_race_class
29864,2013101904,2024/07/27,2新潟1,曇,9,新潟ジャンプS(JGIII),NaN,13,3,3,...,1,1,1,23250,243250,2243250,2433250,2433250,22433250,22433250
29865,2013101904,2024/07/13,2福島5,晴,4,障害3歳以上OP,NaN,8,6,6,...,1,1,1,23380,233380,2233380,2363380,2363380,22363380,22363380
29866,2013101904,2024/02/24,2小倉5,晴,8,春麗ジャンプS(OP),NaN,10,8,9,...,1,1,1,23390,2103390,22103390,21083390,21093390,221083390,221093390
29867,2013101904,2023/12/23,5中山7,晴,10,中山大障害(JGI),NaN,12,7,10,...,0,0,1,24100,264100,2264100,2674100,26104100,22674100,226104100
29868,2013101904,2023/11/11,3京都3,晴,8,京都ジャンプS(JGIII),NaN,12,5,6,...,0,0,0,23170,283170,2283170,2853170,2863170,22853170,22863170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077785,2021102427,2024/04/06,3中山5,曇,6,3歳未勝利,NaN,14,7,12,...,1,0,0,01800,061800,0061800,0671800,06121800,00671800,006121800
1077786,2021102427,2023/12/28,5阪神9,晴,5,2歳新馬,NaN,14,5,7,...,1,<NA>,<NA>,11800,191800,1191800,1951800,1971800,11951800,11971800
1077795,2021103807,2024/02/24,1阪神1,曇,2,3歳未勝利,NaN,11,1,1,...,0,0,0,01800,091800,0091800,0911800,0911800,00911800,00911800
1077796,2021103807,2024/01/13,1京都4,晴,2,3歳未勝利,NaN,14,2,2,...,1,1,1,01800,081800,0081800,0821800,0821800,00821800,00821800
1077797,2021103807,2023/12/28,5阪神9,晴,5,2歳新馬,NaN,14,8,13,...,0,<NA>,<NA>,11800,191800,1191800,1981800,19131800,11981800,119131800

In [ ]:
タイム/距離（割り算も入れる）

# 距離/タイプ
df["distance_type"] = df["course_len"].astype(str) + df["race_type"].astype(str)

# 距離/競馬場/タイプ
df["distance_place_type"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)

# 距離/競馬場/タイプ/レースランク
df["distance_place_type_race_class"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str)

# 距離/競馬場/タイプ/枠順
df["distance_place_type_wakuban"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str)

# 距離/競馬場/タイプ/馬番
df["distance_place_type_umaban"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str)

# 距離/競馬場/タイプ/枠順/レースランク
df["distance_place_type_wakuban_race_class"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["race_class"].astype(str)

# 距離/競馬場/タイプ/馬番/レースランク
df["distance_place_type_umaban_race_class"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["race_class"].astype(str)

# 距離/競馬場/タイプ/枠順/直線
df["distance_place_type_wakuban_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["around"].astype(str)

# 距離/競馬場/タイプ/馬番/直線
df["distance_place_type_umaban_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["around"].astype(str)

# 距離/競馬場/タイプ/枠順/馬場状態
df["distance_place_type_wakuban_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/馬番/馬場状態
df["distance_place_type_umaban_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/枠順/馬場状態/直線
df["distance_place_type_wakuban_ground_state_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)

# 距離/競馬場/タイプ/馬番/馬場状態/直線
df["distance_place_type_umaban_ground_state_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)

# 距離/タイプ/天気
df["distance_type_weather"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)

# 距離/競馬場/タイプ/天気
df["distance_place_type_weather"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)

# 距離/競馬場/タイプ/レースランク/天気
df["distance_place_type_race_class_weather"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["weather"].astype(str)

# 距離/タイプ/馬場状態
df["distance_type_ground_state"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/馬場状態
df["distance_place_type_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/レースランク/馬場状態
df["distance_place_type_race_class_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["ground_state"].astype(str)

# 距離/タイプ/性別
df["distance_type_sex"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)

# 距離/競馬場/タイプ/性別
df["distance_place_type_sex"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)

# 距離/競馬場/タイプ/レースランク/性別
df["distance_place_type_race_class_sex"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str)

# 距離/タイプ/性別/天気
df["distance_type_sex_weather"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)

# 距離/競馬場/タイプ/性別/天気
df["distance_place_type_sex_weather"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)

# 距離/競馬場/タイプ/レースランク/性別/天気
df["distance_place_type_race_class_sex_weather"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)

# 距離/タイプ/性別/馬場状態
df["distance_type_sex_ground_state"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/性別/馬場状態
df["distance_place_type_sex_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/レースランク/性別/馬場状態
df["distance_place_type_race_class_sex_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)

# 距離/タイプ/直線
df["distance_type_straight"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)

# 距離/競馬場/タイプ/直線
df["distance_place_type_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)

# 距離/競馬場/タイプ/レースランク/直線
df["distance_place_type_race_class_straight"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str)

# 距離/タイプ/直線/馬場状態
df["distance_type_straight_ground_state"] = df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/直線/馬場状態
df["distance_place_type_straight_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)

# 距離/競馬場/タイプ/レースランク/直線/馬場状態
df["distance_place_type_race_class_straight_ground_state"] = df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)

In [5]:
#相対化実験2
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows',100)

In [3]:
#まとめて実行
# レース結果テーブルの前処理
results_preprocessed = preprocessing.process_results()
# 馬の過去成績テーブルの加工
horse_results_preprocessed = preprocessing.process_horse_results()
# レース情報テーブルの前処理
race_info_preprocessed = preprocessing.process_race_info()
# 騎手リーディングテーブルの前処理
jockey_leading_preprocessed = preprocessing.process_jockey_leading()
# 調教師リーディングテーブルの前処理
trainer_leading_preprocessed = preprocessing.process_trainer_leading()
# 血統テーブルの前処理
peds_preprocessed = preprocessing.process_peds()
# 種牡馬リーディングテーブルの前処理
sire_leading_preprocessed = preprocessing.process_sire_leading()

In [22]:
#crossfuture作成
from pathlib import Path

from tqdm.notebook import tqdm
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from tqdm.notebook import tqdm
from webdriver_manager.chrome import ChromeDriverManager
from io import StringIO 
DATA_DIR = Path("..", "data")
POPULATION_DIR = DATA_DIR / "00_population"
INPUT_DIR = DATA_DIR / "01_preprocessed"
OUTPUT_DIR = DATA_DIR / "02_features"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

population_dir = POPULATION_DIR
poplation_filename = "population.csv"
input_dir = INPUT_DIR
results_filename = "results.csv"
race_info_filename = "race_info.csv"
horse_results_filename = "horse_results.csv"
jockey_leading_filename = "jockey_leading.csv"
trainer_leading_filename = "trainer_leading.csv"
peds_filename = "peds.csv"
sire_leading_filename = "sire_leading.csv"
output_dir= OUTPUT_DIR
output_filename = "features.csv"

population = pd.read_csv(population_dir / poplation_filename, sep="\t")
results = pd.read_csv(input_dir / results_filename, sep="\t")
race_info = pd.read_csv(input_dir / race_info_filename, sep="\t")
horse_results = pd.read_csv(input_dir / horse_results_filename, sep="\t")
jockey_leading = pd.read_csv(input_dir / jockey_leading_filename, sep="\t")
trainer_leading = pd.read_csv(
    input_dir / trainer_leading_filename, sep="\t"
)
peds = pd.read_csv(input_dir / peds_filename, sep="\t")
sire_leading = pd.read_csv(input_dir / sire_leading_filename, sep="\t")
output_dir = output_dir
output_filename = output_filename
agg_horse_per_group_cols_dfs = {}

baselog = (
    population.merge(
        horse_results, on="horse_id", suffixes=("", "_horse")
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.reset_option('display.precision')
pd.reset_option('display.float_format')

In [23]:
merged_df = population.copy()
df = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

# 距離/競馬場/タイプ/馬番/馬場状態/直線
df["distance_place_type_umaban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)

In [25]:
df2 = df[["distance_place_type_umaban_ground_state_straight", "target"]].dropna().astype(int)
# # 競馬場タイプ、距離、馬番、馬場状態、直線などでグループ化し、targetの平均（複勝率）を計算


# mean_fukusho_rate = df2.groupby("distance_place_type_umaban_ground_state_straight")["target"].transform("mean")

# # 計算した平均複勝率を新しい列として元のDataFrameに追加
# df["mean_fukusho_rate"] = mean_fukusho_rate
# # 結果を確認
# df[['distance_place_type_umaban_ground_state_straight', 'mean_fukusho_rate']].head(100)

df["target"] = (df["rank"] <= 3).astype(int)

# グループごとのカウントを作成
group_counts = df2.groupby("distance_place_type_umaban_ground_state_straight").size()
# 100未満のグループを除外
valid_groups = group_counts[group_counts >= 100].index
# 100以上のグループのみを使用して、平均複勝率を計算
df2_filtered = df2[df2["distance_place_type_umaban_ground_state_straight"].isin(valid_groups)]
# 平均複勝率を計算
mean_fukusho_rate = df2_filtered.groupby("distance_place_type_umaban_ground_state_straight")["target"].transform("mean")
# 計算した平均複勝率を元のDataFrameに追加
df["mean_fukusho_rate_umaban"] = mean_fukusho_rate

# # グループごとのカウントを作成
# group_counts = df2.groupby("distance_place_type_wakuban_ground_state_straight").size()
# # 100未満のグループを除外
# valid_groups = group_counts[group_counts >= 100].index
# # 100以上のグループのみを使用して、平均複勝率を計算
# df2_filtered = df2[df2["distance_place_type_wakuban_ground_state_straight"].isin(valid_groups)]
# # 平均複勝率を計算
# mean_fukusho_rate = df2_filtered.groupby("distance_place_type_wakuban_ground_state_straight")["target"].transform("mean")
# # 計算した平均複勝率を元のDataFrameに追加
# df["mean_fukusho_rate_wakuban"] = mean_fukusho_rate
# # 


# 結果を確認
df[['distance_place_type_umaban_ground_state_straight', "mean_fukusho_rate_umaban"]].head(100)

,distance_place_type_umaban_ground_state_straight,mean_fukusho_rate_umaban
235883,1800911200,NaN
235898,180091900,NaN
234253,180070920,NaN
232428,120071700,0.369369
231867,1800601400,0.492308
235494,120090120,NaN
235792,180070220,NaN
231896,180060820,NaN
235518,1200601120,NaN
235748,180090120,NaN
236057,140070710,NaN
235454,1200601620,NaN
235431,1200601220,NaN
234908,180060420,NaN
235752,180070910,NaN
235851,1200911000,NaN
231719,120060400,0.340206
235847,120091200,NaN
232817,140090400,NaN
232577,1400901300,NaN
236648,120071400,NaN
232601,140090100,0.333333
235193,120070700,0.504505
227145,200071900,NaN
235828,1200911200,NaN
235758,180090600,0.327935
235822,120091800,NaN
228755,1400701600,NaN
235800,180070400,0.419118
235780,180070200,0.370787
235959,180090500,0.302817
235712,160061500,NaN
234086,180090700,0.454936
234093,160091200,NaN
234120,160091300,NaN
234122,160091900,NaN
234201,180090300,0.414343
231943,120090600,0.209524
234241,1800701000,0.398551
232605,1400701100,NaN
230145,190070301,NaN
233328,1200611100,0.425743
236246,200071100,0.384000
234913,180060100,0.457831
236478,1800601000,0.500000
236311,200071600,NaN
234931,1800601000,0.500000
230240,140071601,NaN
236286,200071200,0.520325
234944,1800701100,0.362069
236397,1800601400,0.492308
234948,180060500,0.354067
232737,140090800,0.478261
233353,120061200,0.487395
233410,2000611400,NaN
232851,1400711100,NaN
234992,180061300,NaN
233251,1200601000,0.320000
236534,120071500,NaN
234735,1200601300,0.443750
233809,160061200,NaN
233813,160061100,NaN
234878,1200601600,NaN
234105,160091700,NaN
233389,2000711400,NaN
233264,1200601500,0.383721
233269,1800601000,0.500000
231884,1800601500,NaN
231929,120060900,0.437158
234172,200091800,NaN
234165,200091300,NaN
233298,1800601200,0.450000
230198,140070501,NaN
235739,180070600,0.324176
234059,180090500,0.302817
231835,1600711600,NaN
234047,180070400,0.419118
231264,120070700,0.504505
235769,180090400,0.383178
233502,180060900,0.401914
233516,1800601400,0.492308
230993,180070100,0.283688
233969,120070800,NaN
236526,120091400,NaN
233957,1200601100,0.219355
236112,1800901200,0.424000
236062,140090600,0.382609
230420,180070501,NaN
236043,140090200,NaN
231989,120070700,0.504505
234211,1800701100,0.362069
228197,180070401,NaN
234996,180061300,NaN
234369,180090900,0.480620
235414,1200701200,0.542056
232470,180090300,0.414343
232511,1200901300,NaN
232530,1200901100,0.285714
232553,120090200,0.301887
227237,1800901500,NaN

In [ ]:
        
        # 距離/競馬場/タイプ/馬場状態/天気
        df_old["distance_place_type_ground_state_weather"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["ground_state"].astype(str)+ df_old["weather"]).astype(int)


        df_old["target_rank"] = (df_old["rank"] <= 3).astype(int)

        # グループごとのカウントを作成
        group_counts = df2.groupby("distance_place_type_umaban_ground_state_straight").size()
        # 100未満のグループを除外
        valid_groups = group_counts[group_counts >= 100].index
        # 100以上のグループのみを使用して、平均複勝率を計算
        df2_filtered = df2[df2["distance_place_type_umaban_ground_state_straight"].isin(valid_groups)]
        # 平均複勝率を計算
        mean_fukusho_rate = df2_filtered.groupby("distance_place_type_umaban_ground_state_straight")["target_rank"].transform("mean")
        # 計算した平均複勝率を元のDataFrameに追加
        df_old["mean_fukusho_rate_umaban"] = mean_fukusho_rate
        
        # グループごとのカウントを作成
        group_counts = df2.groupby("distance_place_type_wakuban_ground_state_straight").size()
        # 100未満のグループを除外
        valid_groups = group_counts[group_counts >= 100].index
        # 100以上のグループのみを使用して、平均複勝率を計算
        df2_filtered = df2[df2["distance_place_type_wakuban_ground_state_straight"].isin(valid_groups)]
        # 平均複勝率を計算
        mean_fukusho_rate = df2_filtered.groupby("distance_place_type_wakuban_ground_state_straight")["target_rank"].transform("mean")
        # 計算した平均複勝率を元のDataFrameに追加
        df_old["mean_fukusho_rate_wakuban"] = mean_fukusho_rate

In [16]:

# mean_fukusho_rateを降順に並べ替え
df_sorted = df[['distance_place_type_umaban_ground_state_straight', 'mean_fukusho_rate']].sort_values(by='mean_fukusho_rate', ascending=False)

# 結果を確認
df_sorted.head(100)

        distance_place_type_umaban_ground_state_straight  mean_fukusho_rate
65457                                         1400901000           0.598131
60466                                         1400901000           0.598131
189566                                        1400901000           0.598131
185575                                        1400901000           0.598131
179241                                        1400901000           0.598131
77717                                         1400901000           0.598131
77870                                         1400901000           0.598131
38149                                         1400901000           0.598131
228770                                        1400901000           0.598131
52739                                         1400901000           0.598131
125134                                        1400901000           0.598131
222019                                        1400901000           0.598131
224233                                        1400901000           0.598131
181551                                        1400901000           0.598131
174261                                        1400901000           0.598131
222023                                        1400901000           0.598131
101203                                        1400901000           0.598131
187549                                        1400901000           0.598131
177920                                        1400901000           0.598131
67633                                         1400901000           0.598131
127328                                        1400901000           0.598131
35971                                         1400901000           0.598131
106490                                        1400901000           0.598131
35899                                         1400901000           0.598131
33071                                         1400901000           0.598131
77771                                         1400901000           0.598131
215162                                        1400901000           0.598131
183981                                        1400901000           0.598131
88013                                         1400901000           0.598131
77754                                         1400901000           0.598131
125055                                        1400901000           0.598131
49912                                         1400901000           0.598131
41380                                         1400901000           0.598131
200599                                        1400901000           0.598131
33122                                         1400901000           0.598131
82839                                         1400901000           0.598131
124689                                        1400901000           0.598131
200109                                        1400901000           0.598131
88651                                         1400901000           0.598131
200150                                        1400901000           0.598131
174776                                        1400901000           0.598131
184020                                        1400901000           0.598131
112620                                        1400901000           0.598131
125130                                        1400901000           0.598131
125102                                        1400901000           0.598131
97914                                         1400901000           0.598131
127224                                        1400901000           0.598131
88087                                         1400901000           0.598131
60455                                         1400901000           0.598131
231634                                        1400901000           0.598131
60481                                         1400901000           0.598131
88663                                         1400901000           0.598131
104083                                        1400901000           0.598131
193749                                        1400901000           0.598131
52460                                         1400901000           0.598131
88094                                         1400901000           0.598131
60549                                         1400901000           0.598131
109239                                        1400901000           0.598131
127241                                        1400901000           0.598131
69269                                         1400901000           0.598131
193657                                        1400901000           0.598131
52747                                         1400901000           0.598131
236045                                        1400901000           0.598131
191366                                        1400901000           0.598131
101243                                        1400901000           0.598131
124710                                        1400901000           0.598131
126960                                        1400901000           0.598131
81163                                         1400901000           0.598131
97881                                         1400901000           0.598131
179256                                        1400901000           0.598131
41363                                         1400901000           0.598131
115418                                        1400901000           0.598131
224190                                        1400901000           0.598131
189586                                        1400901000           0.598131
185619                                        1400901000           0.598131
196207                                        1400901000           0.598131
224173                                        1400901000           0.598131
226755                                        1400901000           0.598131
204274                                        1400901000           0.598131
77856                                         1400901000           0.598131
236033                                        1400901000           0.598131
35893                                         1400901000           0.598131
81192                                         1400901000           0.598131
49903                                         1400901000           0.598131
231583                                        1400901000           0.598131
36166                                         1400901000           0.598131
191134                                        1400901000           0.598131
81096                                         1400901000           0.598131
52491                                         1400901000           0.598131
221926                                        1400901000           0.598131
193711                                        1400901000           0.598131
97904                                         1400901000           0.598131
47206                                         1400901000           0.598131
35868                                         1400901000           0.598131
81130                                         1400901000           0.598131
52467                                         1400901000           0.598131
57572                                         1400901000           0.598131
104077                                        1400901000           0.598131
193745                                        1400901000           0.598131
184061                                        1400901000           0.598131

In [ ]:
# 札幌競馬場
plt.figure(figsize=(20, 5))
sns.barplot(
    df2.query("place == 1"),
    x="race_type_course_len",
    y="target",
    hue="wakuban"
)

In [ ]:
merged_df = self.population.copy()    
baselog = (
    self.population.merge(
        self.race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        self.horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

     
df = (
    baselog
    .merge(self.results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)   


# 距離/競馬場/タイプレースランク/直線/天気/馬場状態
df["distance_place_type_race_class_around_weather_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)  + df["race_class"].astype(str)+ df["around"].astype(str) + df["ground_state"].astype(str)+ df["weather"].astype(str)).astype(int)   


baselog_old = (
    self.old_population.merge(
        self.old_race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        self.old_horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

     
df_old = (
    baselog_old
    .merge(self.old_results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df_old["nobori"] = df_old["nobori"].fillna(df_old["nobori"].mean())

df_old["place"] = df_old["place"].astype(int)
df_old["race_class"] = df_old["race_class"].astype(int)
df_old["ground_state"] = df_old["ground_state"].astype(int)
df_old["around"] = df_old["around"].fillna(3).astype(int)
df_old["weather"] = df_old["weather"].astype(int)  

# 距離/競馬場/タイプレースランク/直線/天気/馬場状態
df_old["distance_place_type_race_class_around_weather_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str)  + df_old["race_class"].astype(str)+ df_old["around"].astype(str) + df_old["ground_state"].astype(str)+ df_old["weather"].astype(str)).astype(int)   

#noboriの平均
target_mean_1 = df_old.groupby("distance_place_type_race_class_around_weather_ground_state")["nobori"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_place_type_race_class_around_weather_ground_state_nobori_encoded"] = df_old["distance_place_type_race_class_around_weather_ground_state"].map(target_mean_1)

df_old = df_old[["distance_place_type_race_class_around_weather_ground_state","distance_place_type_race_class_around_weather_ground_state_nobori_encoded"]]

columns_to_merge = [("distance_place_type_race_class_around_weather_ground_state","distance_place_type_race_class_around_weather_ground_state_nobori_encoded")]

for original_col, encoded_col in columns_to_merge:
    df2_subset = df_old[[original_col, encoded_col]].drop_duplicates()  # 重複を削除
    df2_subset = df2_subset.reset_index(drop=True)  # インデックスをリセット
    df = df.merge(df2_subset, on=original_col, how='left')  # dfにマージ

In [82]:
merged_df = population.copy()      

baselog = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

     
df = (
    baselog
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)   

# 距離/競馬場/タイプレースランク/直線/天気/馬場状態
df["distance_place_type_race_class_around_weather_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)  + df["race_class"].astype(str)+ df["around"].astype(str) + df["ground_state"].astype(str)+ df["weather"].astype(str)).astype(int)   


baselog_old = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

     
df_old = (
    baselog_old
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df_old["nobori"] = df_old["nobori"].fillna(df_old["nobori"].mean())

df_old["place"] = df_old["place"].astype(int)
df_old["race_class"] = df_old["race_class"].astype(int)
df_old["ground_state"] = df_old["ground_state"].astype(int)
df_old["around"] = df_old["around"].fillna(3).astype(int)
df_old["weather"] = df_old["weather"].astype(int)  

# 距離/競馬場/タイプレースランク/直線/天気/馬場状態
df_old["distance_place_type_race_class_around_weather_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str)  + df_old["race_class"].astype(str)+ df_old["around"].astype(str) + df_old["ground_state"].astype(str)+ df_old["weather"].astype(str)).astype(int)   

#noboriの平均
target_mean_1 = df_old.groupby("distance_place_type_race_class_around_weather_ground_state")["nobori"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_place_type_race_class_around_weather_ground_state_nobori_encoded"] = df_old["distance_place_type_race_class_around_weather_ground_state"].map(target_mean_1)

#pase_1の平均
target_mean_1 = df_old.groupby("distance_place_type_race_class_around_weather_ground_state")["pase_1"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_place_type_race_class_around_weather_ground_state_pase_1_encoded"] = df_old["distance_place_type_race_class_around_weather_ground_state"].map(target_mean_1)

df_old = df_old[["distance_place_type_race_class_around_weather_ground_state","distance_place_type_race_class_around_weather_ground_state_nobori_encoded","distance_place_type_race_class_around_weather_ground_state_pase_1_encoded"]]

columns_to_merge = [("distance_place_type_race_class_around_weather_ground_state","distance_place_type_race_class_around_weather_ground_state_nobori_encoded"),
                   ("distance_place_type_race_class_around_weather_ground_state","distance_place_type_race_class_around_weather_ground_state_pase_1_encoded")]


for original_col, encoded_col in columns_to_merge:
    df2_subset = df_old[[original_col, encoded_col]].drop_duplicates()  # 重複を削除
    df2_subset = df2_subset.reset_index(drop=True)  # インデックスをリセット
    df = df.merge(df2_subset, on=original_col, how='left')  # dfにマージ
    
# # 計算結果を格納する辞書
# new_columns = {}

# # 各ターゲットエンコーディング列に対して計算
# for col in df.columns:
#     if "_nobori_encoded" in col:
#         new_columns[f"{col}_time_diff"] = df[col] - df["nobori"]
#     df = pd.concat([df, pd.DataFrame(new_columns)], axis=1)
# df[df["horse_id"] == 2019104124]
df["pase_1"]

0         35.4
1         35.4
2         37.5
3         34.1
4         38.3
          ...
121052    36.0
121053    36.0
121054    36.0
121055    36.0
121056    36.0
Name: pase_1, Length: 121057, dtype: float64

In [95]:
# 瞬発力、持続力指標の作成
"""
【タイプ】
タイプの列を作る
タイプの指標を作り、数字が上位なほどそのタイプの適性がある

ランクディフが高ければ（数値が少なければ）、そのレースランク応じてポイントがもらえる
レースランクが多ければ増える
それを以下二つ（瞬発力列と持続力列）に配分する形にする

・瞬発力
おもに一瞬の末脚、ギアチェンジが極めて強い（noboriの単純な少なさ）
コーナー順位と最終順位の差から見極める（コーナーの平均と、最終順位の差）

・持続力
おもに持続力のある末脚


＿コードの文章
使用する列は
rank_diff（着差）、race_class(レースグレード),corner_1_horse,corner_2_horse,corner_3_horse,corner_4_horse(コーナー順位/頭数,_3と_4は欠損値もある),race_id(レースのid),horse_id（出走馬のid）,nobori(のぼり3ハロン),"distance_place_type_umaban_race_class_around_weather_ground_state_nobori_encoded_time_diff"（出走レースのnoboriの平均値）,course_len(距離)
列は全て作成してあるものとする race_classのカテゴリ数値は以下のようになっており、グレードが上がるほど、数値が上がるものとする

    * 		新馬0
    * 		未勝利1
    * 		1勝クラス2
    * 		１勝クラス2
    * 		2勝クラス3
    * 		２勝クラス3
    * 		3勝クラス4
    * 		３勝クラス4
    * 		オープン5
    * 		G36
    * 		G27
    * 		G18
    * 		GIII6
    * 		GII7
    * 		GI8
    * 		重賞6
    * 		GⅢ6
    * 		GⅡ7
    * 		GⅠ8
    * 		L5
    * 		OP5
    * 		特別5
    * 		500万下2
    * 		1000万下3
    * 		1600万下4

これらの列からrank_diffとrace_classの二つを使い、当該レースの当該馬のスコアを決定する
なお、rank_diffは数が少なければ強く、race_classは数が増えるほど強いことに留意
rank_diffには0が入っていることもあるため、+1をして利用すると良い


＿条件分け
1_そのレースで、当該馬のコーナー順位/頭数の平均が0.4を超えている場合、持続力にスコアを割り振る
2_それ以外の場合、瞬発力にスコアを割り振る

1_1ただし、1_で(出走レースのnoboriの平均値 - nobori)が0.4より多い場合、瞬発力にも持続力と同じだけのスコアを割り振る
1_2持続力スコアは距離によって補正を行う、2000を基準とし、それより短いほど-に補正値、長いほど+に補正値をかける、わずかでよい


過去レースの最大値,平均を取ること
"""


# rank_diffに+1してスコア計算用の列を作成
df["adjusted_rank_diff"] = df["rank_diff"] + 1

# rank_diffとrace_classを利用した基本スコアを計算
df["base_score"] = 1 / df["adjusted_rank_diff"] * df["race_class"] *1

# コーナー順位の平均を計算
df["corner_avg_ratio"] = (
    df[["corner_1_per_horse", "corner_2_per_horse", "corner_3_per_horse", "corner_4_per_horse"]]
    .mean(axis=1)
)

# 出走レースのnoboriとの差分を計算
df["nobori_diff"] = df["distance_place_type_race_class_around_weather_ground_state_nobori_encoded"] - df["nobori"]
df["pase_diff"]  = df["distance_place_type_race_class_around_weather_ground_state_pase_1_encoded"] - df["pase_1"]

# スコア分割用の列を作成
df["syunpatu"] = 0.0
df["zizoku"] = 0.0

# 条件1: 持続力にスコアを割り振る
is_sustain_condition = df["corner_avg_ratio"] < 0.4
df.loc[is_sustain_condition, "zizoku"] = df["base_score"]

# 条件1_1: 瞬発力にもスコアを割り振る（nobori_diff > 0.3 の場合）
df.loc[is_sustain_condition & (df["nobori_diff"] > 0.3), "syunpatu"] = df["base_score"]

# 条件2: 瞬発力にスコアを割り振る（それ以外の場合）※未割り当ての場合のみ
df.loc[~is_sustain_condition & df["syunpatu"].isna(), "syunpatu"] = df["base_score"]


# 瞬発力に補正を加える
nobori_correction_factor = np.maximum(df["nobori_diff"] - 0.3, 0) * 0.4  # 補正を半分に減らす
df["syunpatu"] += nobori_correction_factor * df["base_score"]

# # pase_1列に基づく補正

# pase_correction_factor = 0.1 - (df["pase_1"] - 36) / 3.6  # pase_1が36より小さいほど補正を増やし、増えるほど補正を減らす
# df["pase_correction_factor"] = pase_correction_factor
pase_correction_factor =(df["pase_diff"]) * 1
df["pase_correction_factor"] = pase_correction_factor

# 持続力 (zizoku) に補正を加える
df["zizoku"] += pase_correction_factor *df["base_score"] *0.3 # 調整係数0.5は任意で調整可能

# 瞬発力 (syunpatu) に補正を加える
df["syunpatu"] += pase_correction_factor *df["base_score"]* 0.4  # 同様に調整係数を加えます

# 持続力スコアを距離で補正
distance_base = 2000
distance_correction_factor = 1  # 距離補正の影響を抑えるスケーリング係数
df["distance_correction"] = (df["course_len"] - distance_base) / 1000  # 分母を5000に変更し補正を小さく
df["zizoku"] += df["distance_correction"]  * distance_correction_factor

# 必要な列を表示
df[["rank_diff","adjusted_rank_diff", "corner_avg_ratio","race_class", "syunpatu", "zizoku", "nobori_diff", "distance_correction"]].head(100)

# 必要な列を選択し、race_class降順でソートして表示
df_sorted = df[["rank_diff","race_id","horse_id", "date_horse","adjusted_rank_diff", "corner_avg_ratio", "race_class", "pase_1","syunpatu", "zizoku", "nobori_diff", "distance_correction","pase_correction_factor"]].sort_values(by="zizoku", ascending=False)

pd.set_option('display.float_format', lambda x: '%.3f' % x)
# 最初の100行を表示
df_sorted.head(100)

,rank_diff,race_id,horse_id,date_horse,adjusted_rank_diff,corner_avg_ratio,race_class,pase_1,syunpatu,zizoku,nobori_diff,distance_correction,pase_correction_factor
40747,0.000,202306050710,2016103444,2022-12-24,1.000,0.136,8,110.000,0.000,10.100,0.067,2.100,0.000
67384,0.000,202306040711,2018103559,2022-06-26,1.000,0.118,8,33.900,9.783,9.469,0.329,0.200,0.529
14297,0.000,202305050812,2020103656,2023-05-21,1.000,0.333,8,35.100,9.323,9.120,0.413,0.400,0.300
57465,0.000,202309030811,2019104706,2022-09-19,1.000,0.212,7,35.400,2.380,8.985,0.167,0.200,0.850
101374,0.000,202309010908,2016102075,2021-05-15,1.000,0.182,7,104.100,0.000,8.900,0.000,1.900,0.000
86590,0.000,202307040311,2019105155,2021-12-28,1.000,0.200,8,35.900,0.960,8.720,0.000,0.000,0.300
86421,0.000,202304010411,2019105155,2021-12-28,1.000,0.200,8,35.900,0.960,8.720,0.000,0.000,0.300
8045,0.000,202310030110,2019106821,2023-07-16,1.000,0.167,5,34.300,4.886,8.665,-1.057,0.000,2.443
8174,0.000,202309040810,2019105087,2023-07-16,1.000,0.056,5,34.300,4.886,8.665,-2.457,0.000,2.443
21467,0.000,202301020411,2018100274,2023-04-02,1.000,0.062,8,35.500,0.768,8.576,0.120,0.000,0.240
21269,0.000,202305040911,2018100274,2023-04-02,1.000,0.062,8,35.500,0.738,8.554,0.138,0.000,0.231
114659,0.000,202301020411,2017101431,2020-04-26,1.000,0.255,7,35.100,2.022,8.517,-0.606,0.000,0.722
86612,0.000,202309020411,2019105155,2021-12-28,1.000,0.200,8,35.900,0.677,8.508,-0.067,0.000,0.212
101900,0.100,202308010411,2017102170,2021-05-02,1.100,0.206,8,35.800,8.921,8.473,0.867,1.200,0.000
72864,0.000,202305030211,2019103034,2022-05-08,1.000,0.361,8,34.100,1.114,8.435,-0.562,-0.400,0.348
72725,0.000,202307030811,2019103034,2022-05-08,1.000,0.361,8,34.100,1.114,8.435,-0.562,-0.400,0.348
72931,0.000,202308030611,2019103034,2022-05-08,1.000,0.361,8,34.100,1.036,8.377,-0.518,-0.400,0.324
105304,0.000,202306020211,2016104877,2021-02-28,1.000,0.286,7,34.900,15.493,8.375,2.583,-0.200,0.750
64141,0.000,202304020104,2016102442,2022-07-30,1.000,0.071,6,102.100,1.480,8.360,0.150,1.250,0.617
62209,0.000,202306020709,2019103823,2022-08-20,1.000,0.341,5,33.700,4.377,8.283,0.246,0.000,2.189
62162,0.000,202309050111,2019103823,2022-08-20,1.000,0.341,5,33.700,4.377,8.283,0.246,0.000,2.189
62303,0.000,202309040810,2019103823,2022-08-20,1.000,0.341,5,33.700,4.377,8.283,0.246,0.000,2.189
52568,0.100,202309011211,2019105346,2022-10-23,1.100,0.333,8,34.900,0.000,8.273,0.033,1.000,0.000
11665,0.000,202305050108,2016100569,2023-06-17,1.000,0.125,5,104.100,2.810,8.217,0.038,1.110,1.405
43520,0.000,202305050108,2017100997,2022-12-10,1.000,0.143,5,104.100,2.810,8.217,0.138,1.110,1.405
111630,0.000,202307010511,2017105613,2020-09-20,1.000,0.111,7,35.700,8.750,8.155,0.375,0.000,0.550
102170,0.200,202307010111,2016106232,2021-04-25,1.200,0.267,7,33.300,3.567,8.109,-0.478,-0.400,1.529
102260,0.200,202307030811,2016106232,2021-04-25,1.200,0.267,7,33.300,3.567,8.109,-0.478,-0.400,1.529
102163,0.200,202307010111,2014105589,2021-04-25,1.200,0.333,7,33.300,3.567,8.109,-0.378,-0.400,1.529
102214,0.200,202305010411,2016106232,2021-04-25,1.200,0.267,7,33.300,3.567,8.109,-0.478,-0.400,1.529
101375,0.000,202305020711,2017105072,2021-05-15,1.000,0.118,7,34.300,9.887,8.080,0.531,-0.600,0.800
86789,0.100,202306050811,2017102170,2021-12-26,1.100,0.344,8,29.800,9.338,8.035,0.890,0.500,0.120
101501,0.000,202305030211,2018105355,2021-05-09,1.000,0.361,8,33.700,9.516,8.029,0.595,-0.400,0.179
101552,0.000,202305020811,2018105355,2021-05-09,1.000,0.361,8,33.700,9.516,8.029,0.595,-0.400,0.179
39601,0.000,202306030811,2020106402,2022-12-28,1.000,0.056,8,36.100,9.421,8.028,0.733,0.000,0.012
39370,0.000,202301020411,2020106402,2022-12-28,1.000,0.056,8,36.100,9.421,8.028,0.733,0.000,0.012
39645,0.000,202306020411,2020106402,2022-12-28,1.000,0.056,8,36.100,9.421,8.028,0.733,0.000,0.012
104173,0.000,202309011211,2017102170,2021-03-21,1.000,0.288,7,37.300,9.296,8.000,1.120,1.000,0.000
76629,0.000,202309020411,2017105376,2022-04-03,1.000,0.297,8,34.600,8.503,8.000,0.457,0.000,0.000
76604,0.000,202307020211,2017105376,2022-04-03,1.000,0.297,8,34.600,8.107,8.000,0.333,0.000,0.000
45239,0.000,202301020411,2018104662,2022-12-03,1.000,0.250,6,34.800,2.640,7.980,0.254,0.000,1.100
45843,0.000,202309030111,2018104662,2022-12-03,1.000,0.250,6,34.800,2.640,7.980,0.254,0.000,1.100
108687,0.000,202305020811,2018105233,2020-12-13,1.000,0.250,8,34.900,0.364,7.873,0.086,-0.400,0.114
108583,0.000,202305030211,2018105233,2020-12-13,1.000,0.250,8,34.900,0.364,7.873,0.086,-0.400,0.114
67699,0.000,202305050108,2015104582,2022-06-25,1.000,0.083,6,105.000,0.960,7.830,0.060,1.110,0.400
67774,0.000,202309050304,2015104582,2022-06-25,1.000,0.083,6,105.000,0.960,7.830,0.060,1.110,0.400
74401,0.100,202306030311,2017104719,2022-04-24,1.100,0.233,7,34.600,2.473,7.818,-0.514,-0.400,0.971
47483,0.000,202305030708,2014109137,2022-11-19,1.000,0.089,5,104.000,2.271,7.814,0.036,1.110,1.136
88838,0.000,202307040211,2017101010,2021-12-05,1.000,0.344,8,36.500,9.493,7.800,0.767,-0.200,0.000
44565,0.000,202307040211,2019104678,2022-12-04,1.000,0.125,8,37.000,8.160,7.800,0.350,-0.200,0.000
102914,0.000,202305030211,2018105233,2021-04-11,1.000,0.167,8,34.100,11.112,7.704,1.229,-0.400,0.043
41581,0.000,202305020611,2020101533,2022-12-18,1.000,0.176,8,34.100,0.139,7.704,-0.771,-0.400,0.043
41525,0.000,202305030211,2020101533,2022-12-18,1.000,0.176,8,34.100,0.139,7.704,-0.771,-0.400,0.043
103064,0.000,202305020811,2018105233,2021-04-11,1.000,0.167,8,34.100,11.112,7.704,1.229,-0.400,0.043
94132,0.000,202306040711,2017101431,2021-09-26,1.000,0.156,7,36.100,0.665,7.699,0.212,0.200,0.237
13484,0.000,202305050211,2017105379,2023-05-28,1.000,0.056,7,29.700,0.187,7.640,0.067,0.500,0.067
25811,0.000,202306030811,2020103532,2023-03-05,1.000,0.300,7,35.900,8.098,7.630,0.392,0.000,0.300
58284,0.000,202307010511,2019104074,2022-09-18,1.000,0.286,7,35.700,8.680,7.603,0.613,0.000,0.287
79034,0.000,202305040911,2018100274,2022-03-13,1.000,0.077,7,35.700,0.803,7.603,0.213,0.000,0.287
15103,0.000,202305030211,2018105233,2023-05-14,1.000,0.125,8,34.200,0.000,7.600,0.027,-0.400,0.000
79175,0.000,202301020411,2018100274,2022-03-13,1.000,0.077,7,35.700,8.237,7.577,0.467,0.000,0.275
78947,0.000,202309020411,2018100274,2022-03-13,1.000,0.077,7,35.700,8.237,7.577,0.467,0.000,0.275
102240,0.300,202308010211,2016103730,2021-04-25,1.300,0.333,7,33.300,3.389,7.526,-0.344,-0.400,1.573
102237,0.300,202309020211,2016103730,2021-04-25,1.300,0.333,7,33.300,3.389,7.526,-0.344,-0.400,1.573
22725,0.000,202306050811,2018103559,2023-03-25,1.000,0.104,7,30.600,7.373,7.500,0.433,0.500,0.000
77618,0.000,202306050811,2018103559,2022-03-26,1.000,0.067,7,31.500,0.000,7.500,-0.060,0.500,0.000
103805,0.000,202306050811,2017101431,2021-03-27,1.000,0.183,7,31.000,0.000,7.500,0.000,0.500,0.000
77723,0.000,202306030111,2018103559,2022-03-26,1.000,0.067,7,31.500,0.000,7.500,-0.060,0.500,0.000
92577,0.100,202305030708,2016102442,2021-10-17,1.100,0.083,7,106.000,0.000,7.474,0.150,1.110,0.000
92584,0.100,202305040509,2016102442,2021-10-17,1.100,0.083,7,106.000,0.000,7.474,0.150,1.110,0.000
41170,0.000,202306030511,2020101533,2022-12-18,1.000,0.176,8,34.100,-0.175,7.469,-0.291,-0.400,-0.055
61461,0.000,202310030504,2015110032,2022-08-27,1.000,0.250,6,104.000,0.080,7.450,0.033,1.390,0.033
78465,0.100,202309011211,2017105477,2022-03-20,1.100,0.192,7,37.600,6.523,7.435,0.325,1.000,0.038
24526,0.000,202304030610,2020102660,2023-03-12,1.000,0.278,7,33.200,1.344,7.408,-0.213,-0.600,0.480
49359,0.200,202306030111,2017104936,2022-11-06,1.200,0.347,7,29.500,7.431,7.383,0.385,0.500,0.600
49357,0.200,202306050811,2017104936,2022-11-06,1.200,0.347,7,29.500,7.431,7.383,0.385,0.500,0.600
49500,0.200,202306030111,2016104632,2022-11-06,1.200,0.222,7,29.500,1.400,7.383,0.085,0.500,0.600
54136,0.200,202301010411,2016110115,2022-10-15,1.200,0.356,7,34.400,8.536,7.369,0.467,-0.200,0.992
54094,0.200,202306020511,2016110115,2022-10-15,1.200,0.356,7,34.400,8.536,7.369,0.467,-0.200,0.992
77157,0.000,202307011011,2015101028,2022-03-27,1.000,0.167,8,33.400,0.171,7.328,-0.360,-0.800,0.053
77173,0.000,202307020611,2015101028,2022-03-27,1.000,0.167,8,33.400,0.171,7.328,-0.360,-0.800,0.053
79435,0.300,202309010908,2016102056,2022-03-12,1.300,0.364,7,106.000,0.000,7.285,0.000,1.900,0.000
83469,0.100,202310020305,2016102156,2022-01-29,1.100,0.286,5,104.100,1.795,7.282,0.087,1.390,0.987
82101,0.100,202310030504,2016104844,2022-02-12,1.100,0.146,5,104.100,1.795,7.282,0.188,1.390,0.987
118550,0.000,202306030211,2016103957,2019-08-04,1.000,0.317,6,34.600,9.780,7.280,1.053,-0.200,0.822
96275,0.000,202310030504,2015110032,2021-08-28,1.000,0.125,6,104.100,-0.160,7.270,-0.067,1.390,-0.067
86375,0.200,202305040911,2019105346,2021-12-28,1.200,0.333,8,35.900,0.800,7.267,0.100,0.000,0.300
69026,0.000,202306030211,2016105713,2022-06-12,1.000,0.217,5,35.700,9.502,7.256,0.913,-0.200,1.638
114101,0.200,202308020311,2017101415,2020-05-24,1.200,0.292,8,35.400,0.240,7.247,0.220,0.400,0.090
6302,0.000,202305050809,2020103132,2023-08-12,1.000,0.267,5,35.000,8.764,7.241,0.688,0.000,1.494
68963,0.000,202307010811,2016105713,2022-06-12,1.000,0.217,5,35.700,8.637,7.220,0.505,-0.200,1.614
74081,0.000,202308020311,2019100109,2022-04-30,1.000,0.385,7,35.500,8.344,7.211,0.870,0.400,-0.090
66579,0.000,202305040211,2019105366,2022-07-03,1.000,0.346,6,34.900,1.880,7.210,-0.050,-0.200,0.783
47824,0.100,202305040509,2016103444,2022-11-19,1.100,0.125,5,104.000,2.065,7.204,0.036,1.110,1.136
81665,0.000,202307010611,2015101654,2022-02-13,1.000,0.077,7,36.000,0.000,7.200,-0.350,0.200,0.000
16473,0.000,202304030410,2020105633,2023-05-06,1.000,0.083,7,37.700,0.000,7.200,0.100,0.200,0.000
34013,0.000,202306040711,2018102348,2023-01-22,1.000,0.268,7,36.300,8.316,7.200,0.770,0.200,0.000
106838,0.000,202306010811,2017105525,2021-01-24,1.000,0.324,7,38.000,0.000,7.200,-0.025,0.200,0.000
81932,0.000,202309010211,2015101654,2022-02-13,1.000,0.077,7,36.000,0.000,7.200,-0.227,0.200,0.000
16734,0.000,202304030311,2020103413,2023-05-06,1.000,0.208,7,37.700,7.280,7.200,0.400,0.200,0.000

In [6]:
merged_df = population.copy()        
df = (
    merged_df
    .merge(results[["race_id", "horse_id", "wakuban", "umaban", "sex"]], on=["race_id", "horse_id"])
    .merge(race_info[["race_id", "place","race_class","around","weather","ground_state","course_len","race_type"]], on="race_id")
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)   


# 距離/タイプ
df["distance_type"] = (df["course_len"].astype(str) + df["race_type"].astype(str)).astype(int)

# 距離/競馬場/タイプ
df["distance_place_type"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク
df["distance_place_type_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順
df["distance_place_type_wakuban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番
df["distance_place_type_umaban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/レースランク
df["distance_place_type_wakuban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/レースランク
df["distance_place_type_umaban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/直線
df["distance_place_type_wakuban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/直線
df["distance_place_type_umaban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態
df["distance_place_type_wakuban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態
df["distance_place_type_umaban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態/直線
df["distance_place_type_wakuban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態/直線
df["distance_place_type_umaban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/天気
df["distance_type_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/天気
df["distance_place_type_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/天気
df["distance_place_type_race_class_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/馬場状態
df["distance_type_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬場状態
df["distance_place_type_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/馬場状態
df["distance_place_type_race_class_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/性別
df["distance_type_sex"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別
df["distance_place_type_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別
df["distance_place_type_race_class_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/タイプ/性別/天気
df["distance_type_sex_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/天気
df["distance_place_type_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/天気
df["distance_place_type_race_class_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/性別/馬場状態
df["distance_type_sex_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/馬場状態
df["distance_place_type_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/馬場状態
df["distance_place_type_race_class_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/直線
df["distance_type_straight"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線
df["distance_place_type_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線
df["distance_place_type_race_class_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/直線/馬場状態
df["distance_type_straight_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線/馬場状態
df["distance_place_type_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線/馬場状態
df["distance_place_type_race_class_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)

df

,race_id,date,horse_id,wakuban,umaban,sex,place,race_class,around,weather,...,distance_place_type_race_class_sex_weather,distance_type_sex_ground_state,distance_place_type_sex_ground_state,distance_place_type_race_class_sex_ground_state,distance_type_straight,distance_place_type_straight,distance_place_type_race_class_straight,distance_type_straight_ground_state,distance_place_type_straight_ground_state,distance_place_type_race_class_straight_ground_state
0,202306050101,2023-12-02,2021104145,8,15,0,6,1,0,1,...,120060101,1200000,12006000,120060100,120000,1200600,12006010,1200000,12006000,120060100
1,202306050101,2023-12-02,2021107141,6,12,1,6,1,0,1,...,120060111,1200010,12006010,120060110,120000,1200600,12006010,1200000,12006000,120060100
2,202306050101,2023-12-02,2021104079,5,10,0,6,1,0,1,...,120060101,1200000,12006000,120060100,120000,1200600,12006010,1200000,12006000,120060100
3,202306050101,2023-12-02,2021102752,2,4,0,6,1,0,1,...,120060101,1200000,12006000,120060100,120000,1200600,12006010,1200000,12006000,120060100
4,202306050101,2023-12-02,2021103638,3,5,0,6,1,0,1,...,120060101,1200000,12006000,120060100,120000,1200600,12006010,1200000,12006000,120060100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4031,202309050912,2023-12-28,2017104873,6,11,0,9,4,0,1,...,120091401,1200100,12009100,120091400,120010,1200910,12009140,1200100,12009100,120091400
4032,202309050912,2023-12-28,2019100653,8,15,1,9,4,0,1,...,120091411,1200110,12009110,120091410,120010,1200910,12009140,1200100,12009100,120091400
4033,202309050912,2023-12-28,2017106240,4,7,0,9,4,0,1,...,120091401,1200100,12009100,120091400,120010,1200910,12009140,1200100,12009100,120091400
4034,202309050912,2023-12-28,2018103205,8,16,0,9,4,0,1,...,120091401,1200100,12009100,120091400,120010,1200910,12009140,1200100,12009100,120091400
4035,202309050912,2023-12-28,2017102603,7,14,0,9,4,0,1,...,120091401,1200100,12009100,120091400,120010,1200910,12009140,1200100,12009100,120091400

In [85]:
merged_df = merged_df.merge(
    df[[
        "race_id", "horse_id", "date", "distance_type", "distance_place_type", 
        "distance_place_type_race_class", "distance_place_type_wakuban", "distance_place_type_umaban", 
        "distance_place_type_wakuban_race_class", "distance_place_type_umaban_race_class", 
        "distance_place_type_wakuban_straight", "distance_place_type_umaban_straight", 
        "distance_place_type_wakuban_ground_state", "distance_place_type_umaban_ground_state", 
        "distance_place_type_wakuban_ground_state_straight", "distance_place_type_umaban_ground_state_straight", 
        "distance_type_weather", "distance_place_type_weather", "distance_place_type_race_class_weather", 
        "distance_type_ground_state", "distance_place_type_ground_state", "distance_place_type_race_class_ground_state", 
        "distance_type_sex", "distance_place_type_sex", "distance_place_type_race_class_sex", 
        "distance_type_sex_weather", "distance_place_type_sex_weather", "distance_place_type_race_class_sex_weather", 
        "distance_type_sex_ground_state", "distance_place_type_sex_ground_state", 
        "distance_place_type_race_class_sex_ground_state", "distance_type_straight", 
        "distance_place_type_straight", "distance_place_type_race_class_straight", 
        "distance_type_straight_ground_state", "distance_place_type_straight_ground_state", 
        "distance_place_type_race_class_straight_ground_state"
    ]],
    on=["race_id", "date", "horse_id"],
    how="left"
)
merged_df

,race_id,date,horse_id,distance_type,distance_place_type,distance_place_type_race_class,distance_place_type_wakuban,distance_place_type_umaban,distance_place_type_wakuban_race_class,distance_place_type_umaban_race_class,distance_place_type_wakuban_straight,distance_place_type_umaban_straight,distance_place_type_wakuban_ground_state,distance_place_type_umaban_ground_state,distance_place_type_wakuban_ground_state_straight,distance_place_type_umaban_ground_state_straight,distance_type_weather,distance_place_type_weather,distance_place_type_race_class_weather,distance_type_ground_state,distance_place_type_ground_state,distance_place_type_race_class_ground_state,distance_type_sex,distance_place_type_sex,distance_place_type_race_class_sex,distance_type_sex_weather,distance_place_type_sex_weather,distance_place_type_race_class_sex_weather,distance_type_sex_ground_state,distance_place_type_sex_ground_state,distance_place_type_race_class_sex_ground_state,distance_type_straight,distance_place_type_straight,distance_place_type_race_class_straight,distance_type_straight_ground_state,distance_place_type_straight_ground_state,distance_place_type_race_class_straight_ground_state
0,202306010101,2023-01-05,2020103575,14000.0,140070.0,1400700.0,1400707.0,14007014.0,14007070.0,140070140.0,14007070.0,140070140.0,14007073.0,140070143.0,140070730.0,1.400701e+09,140000.0,1400700.0,14007000.0,140003.0,1400703.0,14007003.0,140000.0,1400700.0,14007000.0,1400000.0,14007000.0,140070000.0,1400003.0,14007003.0,140070003.0,140000.0,1400700.0,14007000.0,1400003.0,14007003.0,140070003.0
1,202306010101,2023-01-05,2020103575,12000.0,120040.0,1200400.0,1200407.0,12004014.0,12004070.0,120040140.0,12004070.0,120040140.0,12004070.0,120040140.0,120040700.0,1.200401e+09,120002.0,1200402.0,12004002.0,120000.0,1200400.0,12004000.0,120000.0,1200400.0,12004000.0,1200002.0,12004002.0,120040002.0,1200000.0,12004000.0,120040000.0,120000.0,1200400.0,12004000.0,1200000.0,12004000.0,120040000.0
2,202306010101,2023-01-05,2020103575,12000.0,120040.0,1200400.0,1200407.0,12004014.0,12004070.0,120040140.0,12004070.0,120040140.0,12004070.0,120040140.0,120040700.0,1.200401e+09,120001.0,1200401.0,12004001.0,120000.0,1200400.0,12004000.0,120000.0,1200400.0,12004000.0,1200001.0,12004001.0,120040001.0,1200000.0,12004000.0,120040000.0,120000.0,1200400.0,12004000.0,1200000.0,12004000.0,120040000.0
3,202306010101,2023-01-05,2020103575,12000.0,120040.0,1200400.0,1200407.0,12004014.0,12004070.0,120040140.0,12004070.0,120040140.0,12004070.0,120040140.0,120040700.0,1.200401e+09,120001.0,1200401.0,12004001.0,120000.0,1200400.0,12004000.0,120000.0,1200400.0,12004000.0,1200001.0,12004001.0,120040001.0,1200000.0,12004000.0,120040000.0,120000.0,1200400.0,12004000.0,1200000.0,12004000.0,120040000.0
4,202306010101,2023-01-05,2020103575,12000.0,120090.0,1200900.0,1200907.0,12009014.0,12009070.0,120090140.0,12009070.0,120090140.0,12009073.0,120090143.0,120090730.0,1.200901e+09,120000.0,1200900.0,12009000.0,120003.0,1200903.0,12009003.0,120000.0,1200900.0,12009000.0,1200000.0,12009000.0,120090000.0,1200003.0,12009003.0,120090003.0,120000.0,1200900.0,12009000.0,1200003.0,12009003.0,120090003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
706005,202309050912,2023-12-28,2017102603,12000.0,120080.0,1200800.0,1200807.0,12008014.0,12008070.0,120080140.0,12008070.0,120080140.0,12008071.0,120080141.0,120080710.0,1.200801e+09,120002.0,1200802.0,12008002.0,120001.0,1200801.0,12008001.0,120000.0,1200800.0,12008000.0,1200002.0,12008002.0,120080002.0,1200001.0,12008001.0,120080001.0,120000.0,1200800.0,12008000.0,1200001.0,12008001.0,120080001.0
706006,202309050912,2023-12-28,2017102603,12000.0,120080.0,1200800.0,1200807.0,12008014.0,12008070.0,120080140.0,12008070.0,120080140.0,12008072.0,120080142.0,120080720.0,1.200801e+09,120001.0,1200801.0,12008001.0,120002.0,1200802.0,12008002.0,120000.0,1200800.0,12008000.0,1200001.0,12008001.0,120080001.0,1200002.0,12008002.0,120080002.0,120000.0,1200800.0,12008000.0,1200002.0,12008002.0,120080002.0
706007,202309050912,2023-12-28,2017102603,14001.0,140071.0,1400711.0,1400717.0,14007114.0,14007171.0,140071141.0,14007170.0,140071140.0,14007170.0,140071140.0,140071700.0,1.400711e+09,140011.0,1400711.0,14007111.0,140010.0,1400710.0,14007110.0,140010.0,1400710.0,14007110.0,1400101.0,14007101.0,140071101.0,1400100.0,14007100.0,140071100.0,140010.0,1400710.0,14007110.0,1400100.0,14007100.0,140071100.0
706008,202309050912,2023-12-28,2017102603,16001.0,160091.0,1600911.0,1600917.0,16009114.0,16009171.0,160091141.0,16009170.0,160091140.0,16009170.0,160091140.0,160091700.0,1.600911e+09,160011.0,1600911.0,16009111.0,160010.0,1600910.0,16009110.0,160010.0,1600910.0,16009110.0,1600101.0,16009101.0,160091101.0,1600100.0,16009100.0,160091100.0,160010.0,1600910.0,16009110.0,1600100.0,16009100.0,160091100.0
706009,202309050912,2023-12-28,2017102603,16001.0,160081.0,1600811.0,1600817.0,16008114.0,16008171.0,160081141.0,16008170.0,160081140.0,16008170.0,160081140.0,160081700.0,1.600811e+09,160011.0,1600811.0,16008111.0,160010.0,1600810.0,16008110.0,160010.0,1600810.0,16008110.0,1600101.0,16008101.0,160081101.0,1600100.0,16008100.0,160081100.0,160010.0,1600810.0,16008110.0,1600100.0,16008100.0,160081100.0

In [17]:
fc = FeatureCreator()

In [25]:
#race_typeの型が不一致、バグ修正
fc.baselog = (
            fc.population.merge(
                fc.horse_results, on="horse_id", suffixes=("", "_horse")
            )
            .query("date_horse < date")
            .sort_values("date_horse", ascending=False)
        )

merged_df = population.copy()
grouped_df = fc.baselog.groupby(["race_id", "horse_id"])

print(merged_df["race_id"].dtype)
print(grouped_df["race_id"].dtype)

int64
race_id       horse_id
202306050101  2021102675    int64
              2021102750    int64
              2021102752    int64
              2021102925    int64
              2021103111    int64
                            ...
202309050912  2019105139    int64
              2019106102    int64
              2020100105    int64
              2020100815    int64
              2020101792    int64
Name: race_id, Length: 3522, dtype: object

In [15]:
#crossのバグ修正
merged_df = fc.population.copy()        
df = (
    fc.results[["race_id", "horse_id", "wakuban", "umaban", "sex"]]
    .merge(fc.race_info[["race_id", "race_type", "around"]], on="race_id")
    .merge(merged_df[["race_id", "horse_id", "date"]], on=["race_id", "horse_id"], how="left")
)


# wakuban と race_type の交互作用特徴量
df["wakuban_race_type"] = df["race_type"].map({0: 1, 1: -1, 2: 0}).fillna(0) * df["wakuban"]
df["wakuban_around"] = df["around"].map({2: 1}).fillna(0) * df["wakuban"]
df["umaban_race_type"] = df["race_type"].map({0: 1, 1: -1, 2: 0}).fillna(0) * df["umaban"]
df["umaban_around"] = df["around"].map({2: 1}).fillna(0) * df["umaban"]


# 季節 (日付) と性別に基づく交互作用特徴量
df["date_1"] = pd.to_datetime(df["date"])
df["sin_date"] = np.sin(2 * np.pi * df["date_1"].dt.dayofyear / 365)
df["cos_date"] = np.cos(2 * np.pi * df["date_1"].dt.dayofyear / 365) + 1

df["sin_date_sex"] = df["sex"].map({0: -1, 1: 1}) * df["sin_date"]
df["cos_date_sex"] = df["sex"].map({0: -1, 1: 1}) * df["cos_date"]


merged_df = merged_df.merge(
    df[["race_id", "horse_id", "date","wakuban_race_type", "wakuban_around","umaban_race_type","umaban_around", "sin_date_sex", "cos_date_sex"]],
    on=["race_id","date", "horse_id"],
    how="left"
)
merged_df = merged_df.astype({col: 'float32' for col in merged_df.select_dtypes('float64').columns})
merged_df = merged_df.astype({col: 'int32' for col in merged_df.select_dtypes('int64').columns})

merged_df

# self.agg_cross_features_df= merged_df

,race_id,date,horse_id,wakuban_race_type,wakuban_around,umaban_race_type,umaban_around,sin_date_sex,cos_date_sex
0,442587189,2023-12-02,2021104145,8.0,0.0,15.0,0.0,0.478734,-1.877960
1,442587189,2023-12-02,2021107141,6.0,0.0,12.0,0.0,-0.478734,1.877960
2,442587189,2023-12-02,2021104079,5.0,0.0,10.0,0.0,0.478734,-1.877960
3,442587189,2023-12-02,2021102752,2.0,0.0,4.0,0.0,0.478734,-1.877960
4,442587189,2023-12-02,2021103638,3.0,0.0,5.0,0.0,0.478734,-1.877960
...,...,...,...,...,...,...,...,...,...
4069,445588000,2023-12-28,2017104873,-6.0,0.0,-11.0,0.0,0.051620,-1.998667
4070,445588000,2023-12-28,2019100653,-8.0,0.0,-15.0,0.0,-0.051620,1.998667
4071,445588000,2023-12-28,2017106240,-4.0,0.0,-7.0,0.0,0.051620,-1.998667
4072,445588000,2023-12-28,2018103205,-8.0,0.0,-16.0,0.0,0.051620,-1.998667
4073,445588000,2023-12-28,2017102603,-7.0,0.0,-14.0,0.0,0.051620,-1.998667

In [6]:
#特徴量作成
from pathlib import Path

from tqdm.notebook import tqdm
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from tqdm.notebook import tqdm
from webdriver_manager.chrome import ChromeDriverManager
from io import StringIO 

DATA_DIR = Path("..", "data")
POPULATION_DIR = DATA_DIR / "00_population"
INPUT_DIR = DATA_DIR / "01_preprocessed"
OUTPUT_DIR = DATA_DIR / "02_features"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

population_dir = POPULATION_DIR
poplation_filename = "population.csv"
input_dir = INPUT_DIR
results_filename = "results.csv"
race_info_filename = "race_info.csv"
horse_results_filename = "horse_results.csv"
jockey_leading_filename = "jockey_leading.csv"
trainer_leading_filename = "trainer_leading.csv"
peds_filename = "peds.csv"
sire_leading_filename= "sire_leading.csv"
output_dir = OUTPUT_DIR
output_filename = "features.csv"

population = pd.read_csv(population_dir / poplation_filename, sep="\t")
results = pd.read_csv(input_dir / results_filename, sep="\t")
race_info = pd.read_csv(input_dir / race_info_filename, sep="\t")
horse_results = pd.read_csv(input_dir / horse_results_filename, sep="\t")
jockey_leading = pd.read_csv(input_dir / jockey_leading_filename, sep="\t")
trainer_leading = pd.read_csv(
    input_dir / trainer_leading_filename, sep="\t"
)
peds = pd.read_csv(input_dir / peds_filename, sep="\t")
sire_leading = pd.read_csv(input_dir / sire_leading_filename, sep="\t")
output_dir = output_dir
output_filename = output_filename
agg_horse_per_group_cols_dfs = {}

In [31]:

baselog = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)
merged_df = population.copy()
     
df = (
    baselog
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)  
df

,race_id,date,horse_id,course_len,race_type,around,rank_per_horse,date_horse,rank,prize,rank_diff,umaban,wakuban,weather,ground_state,race_class,n_horses,time,time_courselen,nobori,win,rentai,show,place,corner_1_per_horse,corner_2_per_horse,corner_3_per_horse,corner_4_per_horse,corner_1,corner_2,corner_3,corner_4,pase_1,pase_2,sex
0,202309050903,2023-12-28,2021105731,1800,1,0,0.857143,2023-12-23,12.0,0.0,1.6,12,7,1,0,1,14.0,109.9,0.061056,35.0,0,0,0,9,0.428571,0.571429,NaN,NaN,6,8.0,NaN,NaN,35.4,34.4,0
1,202309050903,2023-12-28,2021104215,1800,1,0,1.000000,2023-12-23,14.0,0.0,2.0,9,6,1,0,1,14.0,110.3,0.061278,34.7,0,0,0,9,1.000000,1.000000,NaN,NaN,14,14.0,NaN,NaN,35.4,34.4,1
2,202309050807,2023-12-24,2020102273,1800,0,0,0.916667,2023-12-17,11.0,0.0,2.7,9,7,1,2,2,12.0,117.1,0.065056,40.0,0,0,0,7,0.833333,0.833333,0.833333,0.916667,10,10.0,10.0,11.0,37.5,39.7,0
3,202306050712,2023-12-23,2018105873,1200,1,0,0.687500,2023-12-17,11.0,0.0,1.0,7,4,1,0,5,16.0,69.9,0.058250,35.8,0,0,0,7,0.062500,0.062500,NaN,NaN,1,1.0,NaN,NaN,34.1,34.8,0
4,202306050704,2023-12-23,2021103822,1800,0,0,0.562500,2023-12-17,9.0,0.0,4.2,14,7,1,0,0,16.0,120.9,0.067167,42.1,0,0,0,6,0.875000,0.875000,0.750000,0.812500,14,14.0,12.0,13.0,38.3,40.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121052,202308020109,2023-10-07,2011106610,1600,1,0,0.375000,2014-01-19,6.0,0.0,0.7,14,7,1,0,0,16.0,97.7,0.061062,37.4,0,0,0,6,0.125000,0.062500,0.125000,NaN,2,1.0,2.0,NaN,36.0,36.7,2
121053,202309020607,2023-04-09,2011106610,1600,1,0,0.375000,2014-01-19,6.0,0.0,0.7,14,7,1,0,0,16.0,97.7,0.061062,37.4,0,0,0,6,0.125000,0.062500,0.125000,NaN,2,1.0,2.0,NaN,36.0,36.7,2
121054,202307030412,2023-07-09,2011106610,1600,1,1,0.375000,2014-01-19,6.0,0.0,0.7,14,7,1,0,0,16.0,97.7,0.061062,37.4,0,0,0,6,0.125000,0.062500,0.125000,NaN,2,1.0,2.0,NaN,36.0,36.7,2
121055,202309040510,2023-09-18,2011106610,1600,1,0,0.375000,2014-01-19,6.0,0.0,0.7,14,7,1,0,0,16.0,97.7,0.061062,37.4,0,0,0,6,0.125000,0.062500,0.125000,NaN,2,1.0,2.0,NaN,36.0,36.7,2
121056,202305020808,2023-05-14,2011106610,1600,1,1,0.375000,2014-01-19,6.0,0.0,0.7,14,7,1,0,0,16.0,97.7,0.061062,37.4,0,0,0,6,0.125000,0.062500,0.125000,NaN,2,1.0,2.0,NaN,36.0,36.7,2

In [30]:
#過去情報の交互特徴量

baselog = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)
merged_df = population.copy()
     
df = (
    baselog
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)  




# 距離/タイプ
df["distance_type"] = (df["course_len"].astype(str) + df["race_type"].astype(str)).astype(int)

# 距離/競馬場/タイプ
df["distance_place_type"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク
df["distance_place_type_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順
df["distance_place_type_wakuban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番
df["distance_place_type_umaban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/レースランク
df["distance_place_type_wakuban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/レースランク
df["distance_place_type_umaban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/直線
df["distance_place_type_wakuban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/直線
df["distance_place_type_umaban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態
df["distance_place_type_wakuban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態
df["distance_place_type_umaban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態/直線
df["distance_place_type_wakuban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態/直線
df["distance_place_type_umaban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/天気
df["distance_type_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/天気
df["distance_place_type_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/天気
df["distance_place_type_race_class_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/馬場状態
df["distance_type_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬場状態
df["distance_place_type_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/馬場状態
df["distance_place_type_race_class_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/性別
df["distance_type_sex"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別
df["distance_place_type_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別
df["distance_place_type_race_class_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/タイプ/性別/天気
df["distance_type_sex_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/天気
df["distance_place_type_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/天気
df["distance_place_type_race_class_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/性別/馬場状態
df["distance_type_sex_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/馬場状態
df["distance_place_type_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/馬場状態
df["distance_place_type_race_class_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/直線
df["distance_type_straight"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線
df["distance_place_type_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線
df["distance_place_type_race_class_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/直線/馬場状態
df["distance_type_straight_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線/馬場状態
df["distance_place_type_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線/馬場状態
df["distance_place_type_race_class_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)



# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df.groupby("distance_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_type_encoded"] = df["distance_type"].map(target_mean_1)


# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_2 = df.groupby("distance_place_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_place_type_encoded"] = df["distance_place_type"].map(target_mean_2)

# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_3 = df.groupby("distance_place_type_race_class")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_place_type_race_class_encoded"] = df["distance_place_type_race_class"].map(target_mean_3)

# 距離/競馬場/タイプ/枠順
target_mean_4 = df.groupby("distance_place_type_wakuban")["time"].mean()
df["distance_place_type_wakuban_encoded"] = df["distance_place_type_wakuban"].map(target_mean_4)

# 距離/競馬場/タイプ/馬番
target_mean_5 = df.groupby("distance_place_type_umaban")["time"].mean()
df["distance_place_type_umaban_encoded"] = df["distance_place_type_umaban"].map(target_mean_5)

# 距離/競馬場/タイプ/枠順/レースランク
target_mean_6 = df.groupby("distance_place_type_wakuban_race_class")["time"].mean()
df["distance_place_type_wakuban_race_class_encoded"] = df["distance_place_type_wakuban_race_class"].map(target_mean_6)

# 距離/競馬場/タイプ/馬番/レースランク
target_mean_7 = df.groupby("distance_place_type_umaban_race_class")["time"].mean()
df["distance_place_type_umaban_race_class_encoded"] = df["distance_place_type_umaban_race_class"].map(target_mean_7)

# 距離/競馬場/タイプ/枠順/直線
target_mean_8 = df.groupby("distance_place_type_wakuban_straight")["time"].mean()
df["distance_place_type_wakuban_straight_encoded"] = df["distance_place_type_wakuban_straight"].map(target_mean_8)

# 距離/競馬場/タイプ/馬番/直線
target_mean_9 = df.groupby("distance_place_type_umaban_straight")["time"].mean()
df["distance_place_type_umaban_straight_encoded"] = df["distance_place_type_umaban_straight"].map(target_mean_9)

# 距離/競馬場/タイプ/枠順/馬場状態
target_mean_10 = df.groupby("distance_place_type_wakuban_ground_state")["time"].mean()
df["distance_place_type_wakuban_ground_state_encoded"] = df["distance_place_type_wakuban_ground_state"].map(target_mean_10)

# 距離/競馬場/タイプ/馬番/馬場状態
target_mean_11 = df.groupby("distance_place_type_umaban_ground_state")["time"].mean()
df["distance_place_type_umaban_ground_state_encoded"] = df["distance_place_type_umaban_ground_state"].map(target_mean_11)

# 距離/競馬場/タイプ/枠順/馬場状態/直線
target_mean_12 = df.groupby("distance_place_type_wakuban_ground_state_straight")["time"].mean()
df["distance_place_type_wakuban_ground_state_straight_encoded"] = df["distance_place_type_wakuban_ground_state_straight"].map(target_mean_12)

# 距離/競馬場/タイプ/馬番/馬場状態/直線
target_mean_13 = df.groupby("distance_place_type_umaban_ground_state_straight")["time"].mean()
df["distance_place_type_umaban_ground_state_straight_encoded"] = df["distance_place_type_umaban_ground_state_straight"].map(target_mean_13)

# 距離/タイプ/天気
target_mean_14 = df.groupby("distance_type_weather")["time"].mean()
df["distance_type_weather_encoded"] = df["distance_type_weather"].map(target_mean_14)

# 距離/競馬場/タイプ/天気
target_mean_15 = df.groupby("distance_place_type_weather")["time"].mean()
df["distance_place_type_weather_encoded"] = df["distance_place_type_weather"].map(target_mean_15)

# 距離/競馬場/タイプ/レースランク/天気
target_mean_16 = df.groupby("distance_place_type_race_class_weather")["time"].mean()
df["distance_place_type_race_class_weather_encoded"] = df["distance_place_type_race_class_weather"].map(target_mean_16)


# 距離/タイプ/馬場状態
target_mean_17 = df.groupby("distance_type_ground_state")["time"].mean()
df["distance_type_ground_state_encoded"] = df["distance_type_ground_state"].map(target_mean_17)

# 距離/競馬場/タイプ/馬場状態
target_mean_18 = df.groupby("distance_place_type_ground_state")["time"].mean()
df["distance_place_type_ground_state_encoded"] = df["distance_place_type_ground_state"].map(target_mean_18)

# 距離/競馬場/タイプ/レースランク/馬場状態
target_mean_19 = df.groupby("distance_place_type_race_class_ground_state")["time"].mean()
df["distance_place_type_race_class_ground_state_encoded"] = df["distance_place_type_race_class_ground_state"].map(target_mean_19)

# 距離/タイプ/性別
target_mean_20 = df.groupby("distance_type_sex")["time"].mean()
df["distance_type_sex_encoded"] = df["distance_type_sex"].map(target_mean_20)

# 距離/競馬場/タイプ/性別
target_mean_21 = df.groupby("distance_place_type_sex")["time"].mean()
df["distance_place_type_sex_encoded"] = df["distance_place_type_sex"].map(target_mean_21)

# 距離/競馬場/タイプ/レースランク/性別
target_mean_22 = df.groupby("distance_place_type_race_class_sex")["time"].mean()
df["distance_place_type_race_class_sex_encoded"] = df["distance_place_type_race_class_sex"].map(target_mean_22)

# 距離/タイプ/性別/天気
target_mean_23 = df.groupby("distance_type_sex_weather")["time"].mean()
df["distance_type_sex_weather_encoded"] = df["distance_type_sex_weather"].map(target_mean_23)

# 距離/競馬場/タイプ/性別/天気
target_mean_24 = df.groupby("distance_place_type_sex_weather")["time"].mean()
df["distance_place_type_sex_weather_encoded"] = df["distance_place_type_sex_weather"].map(target_mean_24)

# 距離/競馬場/タイプ/レースランク/性別/天気
target_mean_25 = df.groupby("distance_place_type_race_class_sex_weather")["time"].mean()
df["distance_place_type_race_class_sex_weather_encoded"] = df["distance_place_type_race_class_sex_weather"].map(target_mean_25)

# 距離/タイプ/性別/馬場状態
target_mean_26 = df.groupby("distance_type_sex_ground_state")["time"].mean()
df["distance_type_sex_ground_state_encoded"] = df["distance_type_sex_ground_state"].map(target_mean_26)

# 距離/競馬場/タイプ/性別/馬場状態
target_mean_27 = df.groupby("distance_place_type_sex_ground_state")["time"].mean()
df["distance_place_type_sex_ground_state_encoded"] = df["distance_place_type_sex_ground_state"].map(target_mean_27)

# 距離/競馬場/タイプ/レースランク/性別/馬場状態
target_mean_28 = df.groupby("distance_place_type_race_class_sex_ground_state")["time"].mean()
df["distance_place_type_race_class_sex_ground_state_encoded"] = df["distance_place_type_race_class_sex_ground_state"].map(target_mean_28)

# 距離/タイプ/直線
target_mean_29 = df.groupby("distance_type_straight")["time"].mean()
df["distance_type_straight_encoded"] = df["distance_type_straight"].map(target_mean_29)

# 距離/競馬場/タイプ/直線
target_mean_30 = df.groupby("distance_place_type_straight")["time"].mean()
df["distance_place_type_straight_encoded"] = df["distance_place_type_straight"].map(target_mean_30)

# 距離/競馬場/タイプ/レースランク/直線
target_mean_31 = df.groupby("distance_place_type_race_class_straight")["time"].mean()
df["distance_place_type_race_class_straight_encoded"] = df["distance_place_type_race_class_straight"].map(target_mean_31)

# 距離/タイプ/直線/馬場状態
target_mean_31 = df.groupby("distance_type_straight_ground_state")["time"].mean()
df["distance_type_straight_ground_state_encoded"] = df["distance_type_straight_ground_state"].map(target_mean_31)

# 距離/競馬場/タイプ/直線/馬場状態
target_mean_32 = df.groupby("distance_place_type_straight_ground_state")["time"].mean()
df["distance_place_type_straight_ground_state_encoded"] = df["distance_place_type_straight_ground_state"].map(target_mean_32)

# 距離/競馬場/タイプ/レースランク/直線/馬場状態
target_mean_33 = df.groupby("distance_place_type_race_class_straight_ground_state")["time"].mean()
df["distance_place_type_race_class_straight_ground_state_encoded"] = df["distance_place_type_race_class_straight_ground_state"].map(target_mean_33)

# 計算結果を格納する辞書
new_columns = {}

# 各ターゲットエンコーディング列に対して計算
for col in df.columns:
    if "_encoded" in col:  # ターゲットエンコーディング列を対象
        # 平均タイムとの差
        new_columns[f"{col}_time_diff"] = df[col] - df["time"]
        
        if "_class" in col:
        
            # # rank と平均タイムの和
            # new_columns[f"{col}_rank_sumprod"] = df[col] + df["rank"]
            
            # # rank と平均タイムの積
            # new_columns[f"{col}_rank_multiprod"] = df[col] * df["rank"]
            
            # rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (df["rank_diff"] + 1)
            
            # rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (df["rank_diff"] + 1)

        elif "_wakuban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))

        

        elif "_umaban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))

# 新しい列を一括で追加
df = pd.concat([df, pd.DataFrame(new_columns)], axis=1)


# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', 100)
# pd.reset_option('display.precision')
# pd.reset_option('display.float_format')
# df.head(100)
print(df.columns.tolist())

['race_id', 'date', 'horse_id', 'course_len', 'race_type', 'around', 'rank_per_horse', 'date_horse', 'rank', 'prize', 'rank_diff', 'umaban', 'wakuban', 'weather', 'ground_state', 'race_class', 'n_horses', 'time', 'time_courselen', 'nobori', 'win', 'rentai', 'show', 'place', 'corner_1_per_horse', 'corner_2_per_horse', 'corner_3_per_horse', 'corner_4_per_horse', 'corner_1', 'corner_2', 'corner_3', 'corner_4', 'pase_1', 'pase_2', 'sex', 'distance_type', 'distance_place_type', 'distance_place_type_race_class', 'distance_place_type_wakuban', 'distance_place_type_umaban', 'distance_place_type_wakuban_race_class', 'distance_place_type_umaban_race_class', 'distance_place_type_wakuban_straight', 'distance_place_type_umaban_straight', 'distance_place_type_wakuban_ground_state', 'distance_place_type_umaban_ground_state', 'distance_place_type_wakuban_ground_state_straight', 'distance_place_type_umaban_ground_state_straight', 'distance_type_weather', 'distance_place_type_weather', 'distance_place_type_race_class_weather', 'distance_type_ground_state', 'distance_place_type_ground_state', 'distance_place_type_race_class_ground_state', 'distance_type_sex', 'distance_place_type_sex', 'distance_place_type_race_class_sex', 'distance_type_sex_weather', 'distance_place_type_sex_weather', 'distance_place_type_race_class_sex_weather', 'distance_type_sex_ground_state', 'distance_place_type_sex_ground_state', 'distance_place_type_race_class_sex_ground_state', 'distance_type_straight', 'distance_place_type_straight', 'distance_place_type_race_class_straight', 'distance_type_straight_ground_state', 'distance_place_type_straight_ground_state', 'distance_place_type_race_class_straight_ground_state', 'distance_type_encoded', 'distance_place_type_encoded', 'distance_place_type_race_class_encoded', 'distance_place_type_wakuban_encoded', 'distance_place_type_umaban_encoded', 'distance_place_type_wakuban_race_class_encoded', 'distance_place_type_umaban_race_class_encoded', 'distance_place_type_wakuban_straight_encoded', 'distance_place_type_umaban_straight_encoded', 'distance_place_type_wakuban_ground_state_encoded', 'distance_place_type_umaban_ground_state_encoded', 'distance_place_type_wakuban_ground_state_straight_encoded', 'distance_place_type_umaban_ground_state_straight_encoded', 'distance_type_weather_encoded', 'distance_place_type_weather_encoded', 'distance_place_type_race_class_weather_encoded', 'distance_type_ground_state_encoded', 'distance_place_type_ground_state_encoded', 'distance_place_type_race_class_ground_state_encoded', 'distance_type_sex_encoded', 'distance_place_type_sex_encoded', 'distance_place_type_race_class_sex_encoded', 'distance_type_sex_weather_encoded', 'distance_place_type_sex_weather_encoded', 'distance_place_type_race_class_sex_weather_encoded', 'distance_type_sex_ground_state_encoded', 'distance_place_type_sex_ground_state_encoded', 'distance_place_type_race_class_sex_ground_state_encoded', 'distance_type_straight_encoded', 'distance_place_type_straight_encoded', 'distance_place_type_race_class_straight_encoded', 'distance_type_straight_ground_state_encoded', 'distance_place_type_straight_ground_state_encoded', 'distance_place_type_race_class_straight_ground_state_encoded', 'distance_type_encoded_time_diff', 'distance_place_type_encoded_time_diff', 'distance_place_type_race_class_encoded_time_diff', 'distance_place_type_race_class_encoded_rank_diff_sumprod', 'distance_place_type_race_class_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_encoded_time_diff', 'distance_place_type_wakuban_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_encoded_rank_diff_multiprod', 'distance_place_type_umaban_encoded_time_diff', 'distance_place_type_umaban_encoded_rank_diff_sumprod', 'distance_place_type_umaban_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_race_class_encoded_time_diff', 'distance_place_type_wakuban_race_class_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_race_class_encoded_rank_diff_multiprod', 'distance_place_type_umaban_race_class_encoded_time_diff', 'distance_place_type_umaban_race_class_encoded_rank_diff_sumprod', 'distance_place_type_umaban_race_class_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_straight_encoded_time_diff', 'distance_place_type_wakuban_straight_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_straight_encoded_rank_diff_multiprod', 'distance_place_type_umaban_straight_encoded_time_diff', 'distance_place_type_umaban_straight_encoded_rank_diff_sumprod', 'distance_place_type_umaban_straight_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_ground_state_encoded_time_diff', 'distance_place_type_wakuban_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_ground_state_encoded_rank_diff_multiprod', 'distance_place_type_umaban_ground_state_encoded_time_diff', 'distance_place_type_umaban_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_umaban_ground_state_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_ground_state_straight_encoded_time_diff', 'distance_place_type_wakuban_ground_state_straight_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_ground_state_straight_encoded_rank_diff_multiprod', 'distance_place_type_umaban_ground_state_straight_encoded_time_diff', 'distance_place_type_umaban_ground_state_straight_encoded_rank_diff_sumprod', 'distance_place_type_umaban_ground_state_straight_encoded_rank_diff_multiprod', 'distance_type_weather_encoded_time_diff', 'distance_place_type_weather_encoded_time_diff', 'distance_place_type_race_class_weather_encoded_time_diff', 'distance_place_type_race_class_weather_encoded_rank_diff_sumprod', 'distance_place_type_race_class_weather_encoded_rank_diff_multiprod', 'distance_type_ground_state_encoded_time_diff', 'distance_place_type_ground_state_encoded_time_diff', 'distance_place_type_race_class_ground_state_encoded_time_diff', 'distance_place_type_race_class_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_race_class_ground_state_encoded_rank_diff_multiprod', 'distance_type_sex_encoded_time_diff', 'distance_place_type_sex_encoded_time_diff', 'distance_place_type_race_class_sex_encoded_time_diff', 'distance_place_type_race_class_sex_encoded_rank_diff_sumprod', 'distance_place_type_race_class_sex_encoded_rank_diff_multiprod', 'distance_type_sex_weather_encoded_time_diff', 'distance_place_type_sex_weather_encoded_time_diff', 'distance_place_type_race_class_sex_weather_encoded_time_diff', 'distance_place_type_race_class_sex_weather_encoded_rank_diff_sumprod', 'distance_place_type_race_class_sex_weather_encoded_rank_diff_multiprod', 'distance_type_sex_ground_state_encoded_time_diff', 'distance_place_type_sex_ground_state_encoded_time_diff', 'distance_place_type_race_class_sex_ground_state_encoded_time_diff', 'distance_place_type_race_class_sex_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_race_class_sex_ground_state_encoded_rank_diff_multiprod', 'distance_type_straight_encoded_time_diff', 'distance_place_type_straight_encoded_time_diff', 'distance_place_type_race_class_straight_encoded_time_diff', 'distance_place_type_race_class_straight_encoded_rank_diff_sumprod', 'distance_place_type_race_class_straight_encoded_rank_diff_multiprod', 'distance_type_straight_ground_state_encoded_time_diff', 'distance_place_type_straight_ground_state_encoded_time_diff', 'distance_place_type_race_class_straight_ground_state_encoded_time_diff', 'distance_place_type_race_class_straight_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_race_class_straight_ground_state_encoded_rank_diff_multiprod']

In [7]:

baselog = (
    population.merge(
        race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)
merged_df = population.copy()
     
df = (
    baselog
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)  


# 距離/タイプ
df["distance_type"] = (df["course_len"].astype(str) + df["race_type"].astype(str)).astype(int)

# 距離/競馬場/タイプ
df["distance_place_type"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク
df["distance_place_type_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順
df["distance_place_type_wakuban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番
df["distance_place_type_umaban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/レースランク
df["distance_place_type_wakuban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/レースランク
df["distance_place_type_umaban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["race_class"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/枠順/直線
# df["distance_place_type_wakuban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["around"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/馬番/直線
# df["distance_place_type_umaban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態
df["distance_place_type_wakuban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態
df["distance_place_type_umaban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/枠順/馬場状態/直線
# df["distance_place_type_wakuban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/馬番/馬場状態/直線
# df["distance_place_type_umaban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/天気
df["distance_type_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/天気
df["distance_place_type_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/天気
df["distance_place_type_race_class_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/馬場状態
df["distance_type_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬場状態
df["distance_place_type_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/馬場状態
df["distance_place_type_race_class_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/タイプ/性別
# df["distance_type_sex"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/性別
# df["distance_place_type_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/レースランク/性別
# df["distance_place_type_race_class_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str)).astype(int)
# # 距離/タイプ/性別/天気
# df["distance_type_sex_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/性別/天気
# df["distance_place_type_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/レースランク/性別/天気
# df["distance_place_type_race_class_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# # 距離/タイプ/性別/馬場状態
# df["distance_type_sex_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/性別/馬場状態
# df["distance_place_type_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/レースランク/性別/馬場状態
# df["distance_place_type_race_class_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/タイプ/直線
# df["distance_type_straight"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/直線
# df["distance_place_type_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/レースランク/直線
# df["distance_place_type_race_class_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str)).astype(int)
# # 距離/タイプ/直線/馬場状態
# df["distance_type_straight_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/直線/馬場状態
# df["distance_place_type_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# # 距離/競馬場/タイプ/レースランク/直線/馬場状態
# df["distance_place_type_race_class_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)



# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df.groupby("distance_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_type_encoded"] = df["distance_type"].map(target_mean_1)


# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df.groupby("distance_place_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_place_type_encoded"] = df["distance_place_type"].map(target_mean_1)

# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df.groupby("distance_place_type_race_class")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df["distance_place_type_race_class_encoded"] = df["distance_place_type_race_class"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順
target_mean_1 = df.groupby("distance_place_type_wakuban")["time"].mean()
df["distance_place_type_wakuban_encoded"] = df["distance_place_type_wakuban"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番
target_mean_1 = df.groupby("distance_place_type_umaban")["time"].mean()
df["distance_place_type_umaban_encoded"] = df["distance_place_type_umaban"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/レースランク
target_mean_1 = df.groupby("distance_place_type_wakuban_race_class")["time"].mean()
df["distance_place_type_wakuban_race_class_encoded"] = df["distance_place_type_wakuban_race_class"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/レースランク
target_mean_1 = df.groupby("distance_place_type_umaban_race_class")["time"].mean()
df["distance_place_type_umaban_race_class_encoded"] = df["distance_place_type_umaban_race_class"].map(target_mean_1)

# # 距離/競馬場/タイプ/枠順/直線
# target_mean_1 = df.groupby("distance_place_type_wakuban_straight")["time"].mean()
# df["distance_place_type_wakuban_straight_encoded"] = df["distance_place_type_wakuban_straight"].map(target_mean_1)

# # 距離/競馬場/タイプ/馬番/直線
# target_mean_1 = df.groupby("distance_place_type_umaban_straight")["time"].mean()
# df["distance_place_type_umaban_straight_encoded"] = df["distance_place_type_umaban_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/馬場状態
target_mean_1 = df.groupby("distance_place_type_wakuban_ground_state")["time"].mean()
df["distance_place_type_wakuban_ground_state_encoded"] = df["distance_place_type_wakuban_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/馬場状態
target_mean_1 = df.groupby("distance_place_type_umaban_ground_state")["time"].mean()
df["distance_place_type_umaban_ground_state_encoded"] = df["distance_place_type_umaban_ground_state"].map(target_mean_1)

# # 距離/競馬場/タイプ/枠順/馬場状態/直線
# target_mean_1 = df.groupby("distance_place_type_wakuban_ground_state_straight")["time"].mean()
# df["distance_place_type_wakuban_ground_state_straight_encoded"] = df["distance_place_type_wakuban_ground_state_straight"].map(target_mean_1)

# # 距離/競馬場/タイプ/馬番/馬場状態/直線
# target_mean_1 = df.groupby("distance_place_type_umaban_ground_state_straight")["time"].mean()
# df["distance_place_type_umaban_ground_state_straight_encoded"] = df["distance_place_type_umaban_ground_state_straight"].map(target_mean_1)

# 距離/タイプ/天気
target_mean_1 = df.groupby("distance_type_weather")["time"].mean()
df["distance_type_weather_encoded"] = df["distance_type_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/天気
target_mean_1 = df.groupby("distance_place_type_weather")["time"].mean()
df["distance_place_type_weather_encoded"] = df["distance_place_type_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/天気
target_mean_1 = df.groupby("distance_place_type_race_class_weather")["time"].mean()
df["distance_place_type_race_class_weather_encoded"] = df["distance_place_type_race_class_weather"].map(target_mean_1)


# 距離/タイプ/馬場状態
target_mean_1 = df.groupby("distance_type_ground_state")["time"].mean()
df["distance_type_ground_state_encoded"] = df["distance_type_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/馬場状態
target_mean_1 = df.groupby("distance_place_type_ground_state")["time"].mean()
df["distance_place_type_ground_state_encoded"] = df["distance_place_type_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/馬場状態
target_mean_1 = df.groupby("distance_place_type_race_class_ground_state")["time"].mean()
df["distance_place_type_race_class_ground_state_encoded"] = df["distance_place_type_race_class_ground_state"].map(target_mean_1)

# # 距離/タイプ/性別
# target_mean_1 = df.groupby("distance_type_sex")["time"].mean()
# df["distance_type_sex_encoded"] = df["distance_type_sex"].map(target_mean_1)

# # 距離/競馬場/タイプ/性別
# target_mean_1 = df.groupby("distance_place_type_sex")["time"].mean()
# df["distance_place_type_sex_encoded"] = df["distance_place_type_sex"].map(target_mean_1)

# # 距離/競馬場/タイプ/レースランク/性別
# target_mean_1 = df.groupby("distance_place_type_race_class_sex")["time"].mean()
# df["distance_place_type_race_class_sex_encoded"] = df["distance_place_type_race_class_sex"].map(target_mean_1)

# # 距離/タイプ/性別/天気
# target_mean_1 = df.groupby("distance_type_sex_weather")["time"].mean()
# df["distance_type_sex_weather_encoded"] = df["distance_type_sex_weather"].map(target_mean_1)

# # 距離/競馬場/タイプ/性別/天気
# target_mean_1 = df.groupby("distance_place_type_sex_weather")["time"].mean()
# df["distance_place_type_sex_weather_encoded"] = df["distance_place_type_sex_weather"].map(target_mean_1)

# # 距離/競馬場/タイプ/レースランク/性別/天気
# target_mean_1 = df.groupby("distance_place_type_race_class_sex_weather")["time"].mean()
# df["distance_place_type_race_class_sex_weather_encoded"] = df["distance_place_type_race_class_sex_weather"].map(target_mean_1)

# # 距離/タイプ/性別/馬場状態
# target_mean_1 = df.groupby("distance_type_sex_ground_state")["time"].mean()
# df["distance_type_sex_ground_state_encoded"] = df["distance_type_sex_ground_state"].map(target_mean_1)

# # 距離/競馬場/タイプ/性別/馬場状態
# target_mean_1 = df.groupby("distance_place_type_sex_ground_state")["time"].mean()
# df["distance_place_type_sex_ground_state_encoded"] = df["distance_place_type_sex_ground_state"].map(target_mean_1)

# # 距離/競馬場/タイプ/レースランク/性別/馬場状態
# target_mean_1 = df.groupby("distance_place_type_race_class_sex_ground_state")["time"].mean()
# df["distance_place_type_race_class_sex_ground_state_encoded"] = df["distance_place_type_race_class_sex_ground_state"].map(target_mean_1)

# # 距離/タイプ/直線
# target_mean_1 = df.groupby("distance_type_straight")["time"].mean()
# df["distance_type_straight_encoded"] = df["distance_type_straight"].map(target_mean_1)

# # 距離/競馬場/タイプ/直線
# target_mean_1 = df.groupby("distance_place_type_straight")["time"].mean()
# df["distance_place_type_straight_encoded"] = df["distance_place_type_straight"].map(target_mean_1)

# # 距離/競馬場/タイプ/レースランク/直線
# target_mean_1 = df.groupby("distance_place_type_race_class_straight")["time"].mean()
# df["distance_place_type_race_class_straight_encoded"] = df["distance_place_type_race_class_straight"].map(target_mean_1)

# # 距離/タイプ/直線/馬場状態
# target_mean_1 = df.groupby("distance_type_straight_ground_state")["time"].mean()
# df["distance_type_straight_ground_state_encoded"] = df["distance_type_straight_ground_state"].map(target_mean_1)

# # 距離/競馬場/タイプ/直線/馬場状態
# target_mean_1 = df.groupby("distance_place_type_straight_ground_state")["time"].mean()
# df["distance_place_type_straight_ground_state_encoded"] = df["distance_place_type_straight_ground_state"].map(target_mean_1)

# # 距離/競馬場/タイプ/レースランク/直線/馬場状態
# target_mean_1 = df.groupby("distance_place_type_race_class_straight_ground_state")["time"].mean()
# df["distance_place_type_race_class_straight_ground_state_encoded"] = df["distance_place_type_race_class_straight_ground_state"].map(target_mean_1)

# 計算結果を格納する辞書
new_columns = {}

# 各ターゲットエンコーディング列に対して計算
for col in df.columns:
    if "_encoded" in col:  # ターゲットエンコーディング列を対象
        # 平均タイムとの差
        new_columns[f"{col}_time_diff"] = df[col] - df["time"]
        
        if "_class" in col:
        
            # # rank と平均タイムの和
            # new_columns[f"{col}_rank_sumprod"] = df[col] + df["rank"]
            
            # # rank と平均タイムの積
            # new_columns[f"{col}_rank_multiprod"] = df[col] * df["rank"]
            
            # rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (df["rank_diff"] + 1)
            
            # rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (df["rank_diff"] + 1)

        elif "_wakuban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))

        

        elif "_umaban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))



# 新しい列を一括で追加
df = pd.concat([df, pd.DataFrame(new_columns)], axis=1)

print(df.columns.tolist())

['race_id', 'date', 'horse_id', 'course_len', 'race_type', 'around', 'rank_per_horse', 'date_horse', 'rank', 'prize', 'rank_diff', 'umaban', 'wakuban', 'weather', 'ground_state', 'race_class', 'n_horses', 'time', 'time_courselen', 'nobori', 'win', 'rentai', 'show', 'place', 'corner_1_per_horse', 'corner_2_per_horse', 'corner_3_per_horse', 'corner_4_per_horse', 'corner_1', 'corner_2', 'corner_3', 'corner_4', 'pase_1', 'pase_2', 'sex', 'distance_type', 'distance_place_type', 'distance_place_type_race_class', 'distance_place_type_wakuban', 'distance_place_type_umaban', 'distance_place_type_wakuban_race_class', 'distance_place_type_umaban_race_class', 'distance_place_type_wakuban_ground_state', 'distance_place_type_umaban_ground_state', 'distance_type_weather', 'distance_place_type_weather', 'distance_place_type_race_class_weather', 'distance_type_ground_state', 'distance_place_type_ground_state', 'distance_place_type_race_class_ground_state', 'distance_type_encoded', 'distance_place_type_encoded', 'distance_place_type_race_class_encoded', 'distance_place_type_wakuban_encoded', 'distance_place_type_umaban_encoded', 'distance_place_type_wakuban_race_class_encoded', 'distance_place_type_umaban_race_class_encoded', 'distance_place_type_wakuban_ground_state_encoded', 'distance_place_type_umaban_ground_state_encoded', 'distance_type_weather_encoded', 'distance_place_type_weather_encoded', 'distance_place_type_race_class_weather_encoded', 'distance_type_ground_state_encoded', 'distance_place_type_ground_state_encoded', 'distance_place_type_race_class_ground_state_encoded', 'distance_type_encoded_time_diff', 'distance_place_type_encoded_time_diff', 'distance_place_type_race_class_encoded_time_diff', 'distance_place_type_race_class_encoded_rank_diff_sumprod', 'distance_place_type_race_class_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_encoded_time_diff', 'distance_place_type_wakuban_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_encoded_rank_diff_multiprod', 'distance_place_type_umaban_encoded_time_diff', 'distance_place_type_umaban_encoded_rank_diff_sumprod', 'distance_place_type_umaban_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_race_class_encoded_time_diff', 'distance_place_type_wakuban_race_class_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_race_class_encoded_rank_diff_multiprod', 'distance_place_type_umaban_race_class_encoded_time_diff', 'distance_place_type_umaban_race_class_encoded_rank_diff_sumprod', 'distance_place_type_umaban_race_class_encoded_rank_diff_multiprod', 'distance_place_type_wakuban_ground_state_encoded_time_diff', 'distance_place_type_wakuban_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_wakuban_ground_state_encoded_rank_diff_multiprod', 'distance_place_type_umaban_ground_state_encoded_time_diff', 'distance_place_type_umaban_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_umaban_ground_state_encoded_rank_diff_multiprod', 'distance_type_weather_encoded_time_diff', 'distance_place_type_weather_encoded_time_diff', 'distance_place_type_race_class_weather_encoded_time_diff', 'distance_place_type_race_class_weather_encoded_rank_diff_sumprod', 'distance_place_type_race_class_weather_encoded_rank_diff_multiprod', 'distance_type_ground_state_encoded_time_diff', 'distance_place_type_ground_state_encoded_time_diff', 'distance_place_type_race_class_ground_state_encoded_time_diff', 'distance_place_type_race_class_ground_state_encoded_rank_diff_sumprod', 'distance_place_type_race_class_ground_state_encoded_rank_diff_multiprod']

In [5]:
fc = FeatureCreator()
features = fc.create_features()

ValueError: You are trying to merge on int64 and object columns for key 'race_id'. If you wish to proceed you should use pd.concat

In [6]:
pfc = PredictionFeatureCreator()
# 過去成績集計は事前に行うことができる
pfc.create_baselog()

fetching shutuba page html...
fetching shutuba page html...comp

ValueError: No tables found

In [ ]:
import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from tqdm.notebook import tqdm
from webdriver_manager.chrome import ChromeDriverManager
from io import StringIO 

# commonディレクトリのパス
COMMON_DATA_DIR = Path("..", "..", "common", "data")
POPULATION_DIR = COMMON_DATA_DIR / "prediction_population"
MAPPING_DIR = COMMON_DATA_DIR / "mapping"


DATA_DIR = Path("..", "data")
OLD_POPULATION_DIR = DATA_DIR / "00_population"
INPUT_DIR = DATA_DIR / "01_preprocessed"
OUTPUT_DIR = DATA_DIR / "02_features"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# カテゴリ変数を数値に変換するためのマッピング
with open(MAPPING_DIR / "sex.json", "r") as f:
    sex_mapping = json.load(f)
with open(MAPPING_DIR / "race_type.json", "r") as f:
    race_type_mapping = json.load(f)
with open(MAPPING_DIR / "around.json", "r") as f:
    around_mapping = json.load(f)
with open(MAPPING_DIR / "weather.json", "r") as f:
    weather_mapping = json.load(f)
with open(MAPPING_DIR / "ground_state.json", "r") as f:
    ground_state_mapping = json.load(f)
with open(MAPPING_DIR / "race_class.json", "r") as f:
    race_class_mapping = json.load(f)


population_dir = POPULATION_DIR,
population_filename = "population.csv",

old_population_dir = OLD_POPULATION_DIR,
old_population_filename = "population.csv",
old_results_filename = "results.csv",
old_race_info_filename= "race_info.csv",
old_horse_results_filename = "horse_results.csv",

input_dir = INPUT_DIR,

horse_results_filename = "horse_results_prediction.csv",
jockey_leading_filename = "jockey_leading.csv",
trainer_leading_filename = "trainer_leading.csv",
peds_filename = "peds_prediction.csv",
sire_leading_filename = "sire_leading.csv",
output_dir = OUTPUT_DIR,
output_filename = "features_prediction.csv",

population = pd.read_csv(population_dir / population_filename, sep="\t")
old_results = pd.read_csv(input_dir / old_results_filename, sep="\t")
old_race_info = pd.read_csv(input_dir / old_race_info_filename, sep="\t")
old_population = pd.read_csv(old_population_dir / old_population_filename, sep="\t")
old_horse_results = pd.read_csv(input_dir / old_horse_results_filename, sep="\t")

horse_results = pd.read_csv(input_dir / horse_results_filename, sep="\t")
jockey_leading = pd.read_csv(input_dir / jockey_leading_filename, sep="\t")
trainer_leading = pd.read_csv(
    input_dir / trainer_leading_filename, sep="\t"
)
peds = pd.read_csv(input_dir / peds_filename, sep="\t")
sire_leading = pd.read_csv(input_dir / sire_leading_filename, sep="\t")
output_dir = output_dir
output_filename = output_filename
htmls = {}
self.agg_horse_per_group_cols_dfs = {}

In [ ]:


"""
カテゴリ・過去成績集計
"""
#過去情報の交互特徴量
merged_df = self.population.copy()

#oldでカテゴリごとの平均タイムを出す
#新しいhorseの過去タイムと比較していきます
#それをnで集計します

baselog_old = (
    old_population.merge(
        old_race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        old_horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

     
df_old = (
    baselog_old
    .merge(old_results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df_old["place"] = df_old["place"].astype(int)
df_old["race_class"] = df["race_class"].astype(int)
df_old["ground_state"] = df["ground_state"].astype(int)
df_old["around"] = df_old["around"].fillna(3).astype(int)
df_old["weather"] = df_old["weather"].astype(int)  



baselog = (
    self.population.merge(
        self.race_info[["race_id", "course_len", "race_type", "around"]], on="race_id"
    )
    .merge(
        horse_results,
        on=["horse_id", "course_len", "race_type"],
        suffixes=("", "_horse"),
    )
    .query("date_horse < date")
    .sort_values("date_horse", ascending=False)
)

df = (
    baselog
    .merge(results[["race_id", "horse_id", "sex"]], on=["race_id", "horse_id"])
)
df["place"] = df["place"].astype(int)
df["race_class"] = df["race_class"].astype(int)
df["ground_state"] = df["ground_state"].astype(int)
df["around"] = df["around"].fillna(3).astype(int)
df["weather"] = df["weather"].astype(int)  





# 距離/タイプ
df_old["distance_type"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str)).astype(int)

# 距離/競馬場/タイプ
df_old["distance_place_type"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク
df_old["distance_place_type_race_class"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順
df_old["distance_place_type_wakuban"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["wakuban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番
df_old["distance_place_type_umaban"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["umaban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/レースランク
df_old["distance_place_type_wakuban_race_class"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["wakuban"].astype(str) + df_old["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/レースランク
df_old["distance_place_type_umaban_race_class"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["umaban"].astype(str) + df_old["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/直線
df_old["distance_place_type_wakuban_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["wakuban"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/直線
df_old["distance_place_type_umaban_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["umaban"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態
df_old["distance_place_type_wakuban_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["wakuban"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態
df_old["distance_place_type_umaban_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["umaban"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態/直線
df_old["distance_place_type_wakuban_ground_state_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["wakuban"].astype(str) + df_old["ground_state"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態/直線
df_old["distance_place_type_umaban_ground_state_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["umaban"].astype(str) + df_old["ground_state"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/タイプ/天気
df_old["distance_type_weather"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/天気
df_old["distance_place_type_weather"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/天気
df_old["distance_place_type_race_class_weather"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/タイプ/馬場状態
df_old["distance_type_ground_state"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬場状態
df_old["distance_place_type_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/馬場状態
df_old["distance_place_type_race_class_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/タイプ/性別
df_old["distance_type_sex"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別
df_old["distance_place_type_sex"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別
df_old["distance_place_type_race_class_sex"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["sex"].astype(str)).astype(int)
# 距離/タイプ/性別/天気
df_old["distance_type_sex_weather"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/天気
df_old["distance_place_type_sex_weather"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/天気
df_old["distance_place_type_race_class_sex_weather"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["sex"].astype(str) + df_old["weather"].astype(str)).astype(int)
# 距離/タイプ/性別/馬場状態
df_old["distance_type_sex_ground_state"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/馬場状態
df_old["distance_place_type_sex_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["sex"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/馬場状態
df_old["distance_place_type_race_class_sex_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["sex"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/タイプ/直線
df_old["distance_type_straight"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線
df_old["distance_place_type_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線
df_old["distance_place_type_race_class_straight"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["around"].astype(str)).astype(int)
# 距離/タイプ/直線/馬場状態
df_old["distance_type_straight_ground_state"] = (df_old["course_len"].astype(str) + df_old["race_type"].astype(str) + df_old["around"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線/馬場状態
df_old["distance_place_type_straight_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["around"].astype(str) + df_old["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線/馬場状態
df_old["distance_place_type_race_class_straight_ground_state"] = (df_old["course_len"].astype(str) + df_old["place"].astype(str) + df_old["race_type"].astype(str) + df_old["race_class"].astype(str) + df_old["around"].astype(str) + df_old["ground_state"].astype(str)).astype(int)






# 距離/タイプ
df["distance_type"] = (df["course_len"].astype(str) + df["race_type"].astype(str)).astype(int)

# 距離/競馬場/タイプ
df["distance_place_type"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク
df["distance_place_type_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順
df["distance_place_type_wakuban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番
df["distance_place_type_umaban"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/レースランク
df["distance_place_type_wakuban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/レースランク
df["distance_place_type_umaban_race_class"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["race_class"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/直線
df["distance_place_type_wakuban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/直線
df["distance_place_type_umaban_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態
df["distance_place_type_wakuban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態
df["distance_place_type_umaban_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/枠順/馬場状態/直線
df["distance_place_type_wakuban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["wakuban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬番/馬場状態/直線
df["distance_place_type_umaban_ground_state_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["umaban"].astype(str) + df["ground_state"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/天気
df["distance_type_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/天気
df["distance_place_type_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/天気
df["distance_place_type_race_class_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/馬場状態
df["distance_type_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/馬場状態
df["distance_place_type_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/馬場状態
df["distance_place_type_race_class_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/性別
df["distance_type_sex"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別
df["distance_place_type_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別
df["distance_place_type_race_class_sex"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str)).astype(int)
# 距離/タイプ/性別/天気
df["distance_type_sex_weather"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/天気
df["distance_place_type_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/天気
df["distance_place_type_race_class_sex_weather"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["weather"].astype(str)).astype(int)
# 距離/タイプ/性別/馬場状態
df["distance_type_sex_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/性別/馬場状態
df["distance_place_type_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/性別/馬場状態
df["distance_place_type_race_class_sex_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["sex"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/タイプ/直線
df["distance_type_straight"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線
df["distance_place_type_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線
df["distance_place_type_race_class_straight"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str)).astype(int)
# 距離/タイプ/直線/馬場状態
df["distance_type_straight_ground_state"] = (df["course_len"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/直線/馬場状態
df["distance_place_type_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)
# 距離/競馬場/タイプ/レースランク/直線/馬場状態
df["distance_place_type_race_class_straight_ground_state"] = (df["course_len"].astype(str) + df["place"].astype(str) + df["race_type"].astype(str) + df["race_class"].astype(str) + df["around"].astype(str) + df["ground_state"].astype(str)).astype(int)



# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df_old.groupby("distance_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_type_encoded"] = df_old["distance_type"].map(target_mean_1)


# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df_old.groupby("distance_place_type")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_place_type_encoded"] = df_old["distance_place_type"].map(target_mean_1)

# ターゲットエンコーディングを計算（カテゴリごとのtimeの平均）
target_mean_1 = df_old.groupby("distance_place_type_race_class")["time"].mean()
# 平均値をカテゴリ変数にマッピング
df_old["distance_place_type_race_class_encoded"] = df_old["distance_place_type_race_class"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順
target_mean_1 = df_old.groupby("distance_place_type_wakuban")["time"].mean()
df_old["distance_place_type_wakuban_encoded"] = df_old["distance_place_type_wakuban"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番
target_mean_1 = df_old.groupby("distance_place_type_umaban")["time"].mean()
df_old["distance_place_type_umaban_encoded"] = df_old["distance_place_type_umaban"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/レースランク
target_mean_1 = df_old.groupby("distance_place_type_wakuban_race_class")["time"].mean()
df_old["distance_place_type_wakuban_race_class_encoded"] = df_old["distance_place_type_wakuban_race_class"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/レースランク
target_mean_1 = df_old.groupby("distance_place_type_umaban_race_class")["time"].mean()
df_old["distance_place_type_umaban_race_class_encoded"] = df_old["distance_place_type_umaban_race_class"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/直線
target_mean_1 = df_old.groupby("distance_place_type_wakuban_straight")["time"].mean()
df_old["distance_place_type_wakuban_straight_encoded"] = df_old["distance_place_type_wakuban_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/直線
target_mean_1 = df_old.groupby("distance_place_type_umaban_straight")["time"].mean()
df_old["distance_place_type_umaban_straight_encoded"] = df_old["distance_place_type_umaban_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_wakuban_ground_state")["time"].mean()
df_old["distance_place_type_wakuban_ground_state_encoded"] = df_old["distance_place_type_wakuban_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_umaban_ground_state")["time"].mean()
df_old["distance_place_type_umaban_ground_state_encoded"] = df_old["distance_place_type_umaban_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/枠順/馬場状態/直線
target_mean_1 = df_old.groupby("distance_place_type_wakuban_ground_state_straight")["time"].mean()
df_old["distance_place_type_wakuban_ground_state_straight_encoded"] = df_old["distance_place_type_wakuban_ground_state_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/馬番/馬場状態/直線
target_mean_1 = df_old.groupby("distance_place_type_umaban_ground_state_straight")["time"].mean()
df_old["distance_place_type_umaban_ground_state_straight_encoded"] = df_old["distance_place_type_umaban_ground_state_straight"].map(target_mean_1)

# 距離/タイプ/天気
target_mean_1 = df_old.groupby("distance_type_weather")["time"].mean()
df_old["distance_type_weather_encoded"] = df_old["distance_type_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/天気
target_mean_1 = df_old.groupby("distance_place_type_weather")["time"].mean()
df_old["distance_place_type_weather_encoded"] = df_old["distance_place_type_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/天気
target_mean_1 = df_old.groupby("distance_place_type_race_class_weather")["time"].mean()
df_old["distance_place_type_race_class_weather_encoded"] = df_old["distance_place_type_race_class_weather"].map(target_mean_1)


# 距離/タイプ/馬場状態
target_mean_1 = df_old.groupby("distance_type_ground_state")["time"].mean()
df_old["distance_type_ground_state_encoded"] = df_old["distance_type_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_ground_state")["time"].mean()
df_old["distance_place_type_ground_state_encoded"] = df_old["distance_place_type_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_race_class_ground_state")["time"].mean()
df_old["distance_place_type_race_class_ground_state_encoded"] = df_old["distance_place_type_race_class_ground_state"].map(target_mean_1)

# 距離/タイプ/性別
target_mean_1 = df_old.groupby("distance_type_sex")["time"].mean()
df_old["distance_type_sex_encoded"] = df_old["distance_type_sex"].map(target_mean_1)

# 距離/競馬場/タイプ/性別
target_mean_1 = df_old.groupby("distance_place_type_sex")["time"].mean()
df_old["distance_place_type_sex_encoded"] = df_old["distance_place_type_sex"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/性別
target_mean_1 = df_old.groupby("distance_place_type_race_class_sex")["time"].mean()
df_old["distance_place_type_race_class_sex_encoded"] = df_old["distance_place_type_race_class_sex"].map(target_mean_1)

# 距離/タイプ/性別/天気
target_mean_1 = df_old.groupby("distance_type_sex_weather")["time"].mean()
df_old["distance_type_sex_weather_encoded"] = df_old["distance_type_sex_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/性別/天気
target_mean_1 = df_old.groupby("distance_place_type_sex_weather")["time"].mean()
df_old["distance_place_type_sex_weather_encoded"] = df_old["distance_place_type_sex_weather"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/性別/天気
target_mean_1 = df_old.groupby("distance_place_type_race_class_sex_weather")["time"].mean()
df_old["distance_place_type_race_class_sex_weather_encoded"] = df_old["distance_place_type_race_class_sex_weather"].map(target_mean_1)

# 距離/タイプ/性別/馬場状態
target_mean_1 = df_old.groupby("distance_type_sex_ground_state")["time"].mean()
df_old["distance_type_sex_ground_state_encoded"] = df_old["distance_type_sex_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/性別/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_sex_ground_state")["time"].mean()
df_old["distance_place_type_sex_ground_state_encoded"] = df_old["distance_place_type_sex_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/性別/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_race_class_sex_ground_state")["time"].mean()
df_old["distance_place_type_race_class_sex_ground_state_encoded"] = df_old["distance_place_type_race_class_sex_ground_state"].map(target_mean_1)

# 距離/タイプ/直線
target_mean_1 = df_old.groupby("distance_type_straight")["time"].mean()
df_old["distance_type_straight_encoded"] = df_old["distance_type_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/直線
target_mean_1 = df_old.groupby("distance_place_type_straight")["time"].mean()
df_old["distance_place_type_straight_encoded"] = df_old["distance_place_type_straight"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/直線
target_mean_1 = df_old.groupby("distance_place_type_race_class_straight")["time"].mean()
df_old["distance_place_type_race_class_straight_encoded"] = df_old["distance_place_type_race_class_straight"].map(target_mean_1)

# 距離/タイプ/直線/馬場状態
target_mean_1 = df_old.groupby("distance_type_straight_ground_state")["time"].mean()
df_old["distance_type_straight_ground_state_encoded"] = df_old["distance_type_straight_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/直線/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_straight_ground_state")["time"].mean()
df_old["distance_place_type_straight_ground_state_encoded"] = df_old["distance_place_type_straight_ground_state"].map(target_mean_1)

# 距離/競馬場/タイプ/レースランク/直線/馬場状態
target_mean_1 = df_old.groupby("distance_place_type_race_class_straight_ground_state")["time"].mean()
df_old["distance_place_type_race_class_straight_ground_state_encoded"] = df_old["distance_place_type_race_class_straight_ground_state"].map(target_mean_1)

In [ ]:


df = pd.merge(df, df_old, on="id")

# 必要な列だけをdf2から取得
df2_subset = df_old[["distance_type", "distance_place_type", 
                "distance_place_type_race_class", "distance_place_type_wakuban", "distance_place_type_umaban", 
                "distance_place_type_wakuban_race_class", "distance_place_type_umaban_race_class", 
                "distance_place_type_wakuban_straight", "distance_place_type_umaban_straight", 
                "distance_place_type_wakuban_ground_state", "distance_place_type_umaban_ground_state", 
                "distance_place_type_wakuban_ground_state_straight", "distance_place_type_umaban_ground_state_straight", 
                "distance_type_weather", "distance_place_type_weather", "distance_place_type_race_class_weather", 
                "distance_type_ground_state", "distance_place_type_ground_state", "distance_place_type_race_class_ground_state", 
                "distance_type_sex", "distance_place_type_sex", "distance_place_type_race_class_sex", 
                "distance_type_sex_weather", "distance_place_type_sex_weather", "distance_place_type_race_class_sex_weather", 
                "distance_type_sex_ground_state", "distance_place_type_sex_ground_state", 
                "distance_place_type_race_class_sex_ground_state", "distance_type_straight", 
                "distance_place_type_straight", "distance_place_type_race_class_straight", 
                "distance_type_straight_ground_state", "distance_place_type_straight_ground_state", 
                "distance_place_type_race_class_straight_ground_state", 
                'distance_type_encoded', 'distance_place_type_encoded', 'distance_place_type_race_class_encoded', 'distance_place_type_wakuban_encoded', 'distance_place_type_umaban_encoded', 'distance_place_type_wakuban_race_class_encoded', 'distance_place_type_umaban_race_class_encoded', 'distance_place_type_wakuban_straight_encoded', 'distance_place_type_umaban_straight_encoded', 'distance_place_type_wakuban_ground_state_encoded', 'distance_place_type_umaban_ground_state_encoded', 'distance_place_type_wakuban_ground_state_straight_encoded', 'distance_place_type_umaban_ground_state_straight_encoded', 'distance_type_weather_encoded', 'distance_place_type_weather_encoded', 'distance_place_type_race_class_weather_encoded', 'distance_type_ground_state_encoded', 'distance_place_type_ground_state_encoded', 'distance_place_type_race_class_ground_state_encoded', 'distance_type_sex_encoded', 'distance_place_type_sex_encoded', 'distance_place_type_race_class_sex_encoded', 'distance_type_sex_weather_encoded', 'distance_place_type_sex_weather_encoded', 'distance_place_type_race_class_sex_weather_encoded', 'distance_type_sex_ground_state_encoded', 'distance_place_type_sex_ground_state_encoded', 'distance_place_type_race_class_sex_ground_state_encoded', 'distance_type_straight_encoded', 'distance_place_type_straight_encoded', 'distance_place_type_race_class_straight_encoded', 'distance_type_straight_ground_state_encoded', 'distance_place_type_straight_ground_state_encoded', 'distance_place_type_race_class_straight_ground_state_encoded'
                    ]]
# 重複を削除して圧縮
df2_subset = df2_subset.drop_duplicates(subset=["distance_type", "distance_place_type", 
                "distance_place_type_race_class", "distance_place_type_wakuban", "distance_place_type_umaban", 
                "distance_place_type_wakuban_race_class", "distance_place_type_umaban_race_class", 
                "distance_place_type_wakuban_straight", "distance_place_type_umaban_straight", 
                "distance_place_type_wakuban_ground_state", "distance_place_type_umaban_ground_state", 
                "distance_place_type_wakuban_ground_state_straight", "distance_place_type_umaban_ground_state_straight", 
                "distance_type_weather", "distance_place_type_weather", "distance_place_type_race_class_weather", 
                "distance_type_ground_state", "distance_place_type_ground_state", "distance_place_type_race_class_ground_state", 
                "distance_type_sex", "distance_place_type_sex", "distance_place_type_race_class_sex", 
                "distance_type_sex_weather", "distance_place_type_sex_weather", "distance_place_type_race_class_sex_weather", 
                "distance_type_sex_ground_state", "distance_place_type_sex_ground_state", 
                "distance_place_type_race_class_sex_ground_state", "distance_type_straight", 
                "distance_place_type_straight", "distance_place_type_race_class_straight", 
                "distance_type_straight_ground_state", "distance_place_type_straight_ground_state", 
                "distance_place_type_race_class_straight_ground_state", 
                'distance_type_encoded', 'distance_place_type_encoded', 'distance_place_type_race_class_encoded', 'distance_place_type_wakuban_encoded', 'distance_place_type_umaban_encoded', 'distance_place_type_wakuban_race_class_encoded', 'distance_place_type_umaban_race_class_encoded', 'distance_place_type_wakuban_straight_encoded', 'distance_place_type_umaban_straight_encoded', 'distance_place_type_wakuban_ground_state_encoded', 'distance_place_type_umaban_ground_state_encoded', 'distance_place_type_wakuban_ground_state_straight_encoded', 'distance_place_type_umaban_ground_state_straight_encoded', 'distance_type_weather_encoded', 'distance_place_type_weather_encoded', 'distance_place_type_race_class_weather_encoded', 'distance_type_ground_state_encoded', 'distance_place_type_ground_state_encoded', 'distance_place_type_race_class_ground_state_encoded', 'distance_type_sex_encoded', 'distance_place_type_sex_encoded', 'distance_place_type_race_class_sex_encoded', 'distance_type_sex_weather_encoded', 'distance_place_type_sex_weather_encoded', 'distance_place_type_race_class_sex_weather_encoded', 'distance_type_sex_ground_state_encoded', 'distance_place_type_sex_ground_state_encoded', 'distance_place_type_race_class_sex_ground_state_encoded', 'distance_type_straight_encoded', 'distance_place_type_straight_encoded', 'distance_place_type_race_class_straight_encoded', 'distance_type_straight_ground_state_encoded', 'distance_place_type_straight_ground_state_encoded', 'distance_place_type_race_class_straight_ground_state_encoded'])


# df1にdf2のエンコード列をマージ
df = df.merge(
    df2_subset,  # マージ元のデータフレーム
    on="distance_type", "distance_place_type", 
        "distance_place_type_race_class", "distance_place_type_wakuban", "distance_place_type_umaban", 
        "distance_place_type_wakuban_race_class", "distance_place_type_umaban_race_class", 
        "distance_place_type_wakuban_straight", "distance_place_type_umaban_straight", 
        "distance_place_type_wakuban_ground_state", "distance_place_type_umaban_ground_state", 
        "distance_place_type_wakuban_ground_state_straight", "distance_place_type_umaban_ground_state_straight", 
        "distance_type_weather", "distance_place_type_weather", "distance_place_type_race_class_weather", 
        "distance_type_ground_state", "distance_place_type_ground_state", "distance_place_type_race_class_ground_state", 
        "distance_type_sex", "distance_place_type_sex", "distance_place_type_race_class_sex", 
        "distance_type_sex_weather", "distance_place_type_sex_weather", "distance_place_type_race_class_sex_weather", 
        "distance_type_sex_ground_state", "distance_place_type_sex_ground_state", 
        "distance_place_type_race_class_sex_ground_state", "distance_type_straight", 
        "distance_place_type_straight", "distance_place_type_race_class_straight", 
        "distance_type_straight_ground_state", "distance_place_type_straight_ground_state", 
        "distance_place_type_race_class_straight_ground_state",   # キーとなる列
    how="left"  # df1に行を合わせる（行数を増やさない）
)

In [ ]:
# 計算結果を格納する辞書
new_columns = {}

# 各ターゲットエンコーディング列に対して計算
for col in df.columns:
    if "_encoded" in col:  # ターゲットエンコーディング列を対象
        # 平均タイムとの差
        new_columns[f"{col}_time_diff"] = df[col] - df["time"]
        
        if "_class" in col:
        
            # # rank と平均タイムの和
            # new_columns[f"{col}_rank_sumprod"] = df[col] + df["rank"]
            
            # # rank と平均タイムの積
            # new_columns[f"{col}_rank_multiprod"] = df[col] * df["rank"]
            
            # rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (df["rank_diff"] + 1)
            
            # rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (df["rank_diff"] + 1)

        elif "_wakuban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))

        

        elif "_umaban" in col:
            
            # 頭数/rankdiff + 1 と平均タイムの和
            new_columns[f"{col}_rank_diff_sumprod"] = df[col] + (1/(df["rank_diff"] + 1))
            
            # 頭数/rankdiff + 1 と平均タイムの積
            new_columns[f"{col}_rank_diff_multiprod"] = df[col] * (1/(df["rank_diff"] + 1))
# 新しい列を一括で追加
df = pd.concat([df, pd.DataFrame(new_columns)], axis=1)

In [15]:
import pandas as pd

# df1 の例
data1 = {
    "distance_place_type_race_class_straight_ground_state": [1, 2,3,1,2],
    "time": [100, 200,3,4,5]
}
df1 = pd.DataFrame(data1)

# df2 の例
data2 = {
    "distance_place_type_race_class_straight_ground_state": [1, 2,3],  # 4 は df1 にない
    "encoded_value": [0.5, 0.7,3]
}
df2 = pd.DataFrame(data2)

# df1 に df2 の列を追加 (merge)
df1 = df1.merge(
    df2,
    on="distance_place_type_race_class_straight_ground_state" , # キーを指定
    how="left"  # 左外部結合で df1 を基準にする
)

df1

   distance_place_type_race_class_straight_ground_state  time  encoded_value
0                                                  1      100            0.5
1                                                  2      200            0.7
2                                                  3        3            3.0
3                                                  1        4            0.5
4                                                  2        5            0.7