In [33]:
import create_population_turf
import create_population_turf_newbie
import create_population_turf_nowin
import create_population_obstract
import create_population_dirt
import create_population_dirt_newbie
import create_population_dirt_nowin
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction


import pandas as pd
import numpy as np


import condition_prediction


from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lightgbm_time import Trainer_lightgbm_time
from train_lgbm_time_cross import Trainer_lightgbm_time_cv

from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki

from evaluation_shaft_time_kaiki_cross import Evaluator_lightgbm_time_kaiki_shaft

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross
from evaluation_shaft_rank_cross import Evaluator_lightgbm_rank_niti_shaft


%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
%autoreload

In [35]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 800)

In [31]:
df = pd.read_csv("../data/03_train/evaluation_lightgbm_rank_niti_cv_dev_.csv",sep="\t")
df

# df = pd.read_csv("../data/03_train/evaluation_lightgbm_rank_niti_cv_dev_turf.csv",sep="\t")
# df

#期待値
# df["expect_return"] = df["tansho_odds"] * df["pred"]
# df["payoff"] = df["target"] * df["tansho_odds"]
df["pred"] = df.groupby("race_id")["pred"].transform(lambda x: x / x.sum())
df["expect_return"] = df["tansho_odds"] * df["pred"]
df.loc[(df["rank"] == 1) & (df["target"] == 1), "payoff"] = df["target"] * df["tansho_odds"]
df["payoff"] = df["payoff"].fillna(0)
df

,race_id,horse_id,target,rank,course_len,weather,ground_state,race_class,age,median_age,mean_age,place,tansho_odds,popularity,umaban,pred,pred_binary,expect_return,payoff
0,201704030603,2011103430,0,6,1800,3,1,2,6,4.0,4.000000,4,18.2,6,12,0.036480,0,0.663937,0.0
1,201704030606,2014100798,0,4,1200,3,1,2,3,3.0,3.533333,4,10.1,5,12,0.117122,0,1.182930,0.0
2,201704030603,2013106365,0,7,1800,3,1,2,4,4.0,4.000000,4,24.8,7,5,0.137517,0,3.410417,0.0
3,201704030603,2014100078,0,9,1800,3,1,2,3,4.0,4.000000,4,36.5,8,4,0.151710,0,5.537402,0.0
4,201705040908,2013102854,1,1,1400,3,3,5,4,4.0,4.200000,5,21.1,6,8,1.000000,0,21.100000,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94151,202505010811,2020100273,0,15,1600,1,0,8,5,5.0,5.812500,5,159.6,15,3,0.020218,0,3.226852,0.0
94152,202505010811,2020102745,0,14,1600,1,0,8,5,5.0,5.812500,5,90.6,13,13,0.004254,0,0.385417,0.0
94153,202505010811,2018100829,0,13,1600,1,0,8,7,5.0,5.812500,5,84.6,12,4,0.058437,0,4.943804,0.0
94154,202505010811,2016102370,0,11,1600,1,0,8,9,5.0,5.812500,5,308.5,16,16,0.024703,0,7.620757,0.0
94155,202505010811,2020103626,0,11,1600,1,0,8,5,5.0,5.812500,5,29.4,7,8,0.084605,1,2.487400,0.0

In [62]:
bet_df = df.query("expect_return > 1.0 and pred > 0.08")
bet_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary,expect_return
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1,1.168142
41,201706040711,2012104678,0,10,13.5,7,4,0.142301,1,1.921062
55,201706040711,2012104008,0,3,5.4,3,9,0.242821,1,1.311235
58,201709040807,2013104488,0,12,15.7,8,12,0.125473,1,1.969930
60,201709040810,2012103929,0,3,20.1,8,5,0.108937,1,2.189640
...,...,...,...,...,...,...,...,...,...,...
89143,202407040110,2021100935,0,5,10.2,6,3,0.141294,1,1.441199
89145,202407040110,2021105926,0,3,4.7,2,4,0.277356,1,1.303575
89146,202407040110,2020103241,0,2,5.7,4,6,0.275453,1,1.570082
89147,202407040108,2021106118,0,15,13.2,6,3,0.165345,1,2.182559
89154,202407040108,2021104918,0,8,23.9,8,10,0.139651,1,3.337669

In [63]:
#単勝オッズ（払い戻し）xターゲットは当たったか当たってないか、単勝
#的中率は調べてない、賭け方が1以上の場合にかけているから関係ない
bet_df = bet_df.copy()
bet_df.loc[:, "payoff"] = bet_df["target"] * bet_df["tansho_odds"]

bet_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary,expect_return,payoff
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1,1.168142,0.0
41,201706040711,2012104678,0,10,13.5,7,4,0.142301,1,1.921062,0.0
55,201706040711,2012104008,0,3,5.4,3,9,0.242821,1,1.311235,0.0
58,201709040807,2013104488,0,12,15.7,8,12,0.125473,1,1.969930,0.0
60,201709040810,2012103929,0,3,20.1,8,5,0.108937,1,2.189640,0.0
...,...,...,...,...,...,...,...,...,...,...,...
89143,202407040110,2021100935,0,5,10.2,6,3,0.141294,1,1.441199,0.0
89145,202407040110,2021105926,0,3,4.7,2,4,0.277356,1,1.303575,0.0
89146,202407040110,2020103241,0,2,5.7,4,6,0.275453,1,1.570082,0.0
89147,202407040108,2021106118,0,15,13.2,6,3,0.165345,1,2.182559,0.0
89154,202407040108,2021104918,0,8,23.9,8,10,0.139651,1,3.337669,0.0

In [64]:
#払い戻しの合計
total_payoff = bet_df["payoff"].sum()
total_payoff

np.float64(9967.9)

In [65]:
#払い戻し、馬券購入回数、回収率
total_bet = len(bet_df)
return_rate = total_payoff / total_bet
total_payoff,total_bet,return_rate

(np.float64(9967.9), 12027, np.float64(0.8287935478506693))

In [66]:
#期待値がどれくらい上になるかを検証
np.linspace(0.8,10,10)

array([ 0.8       ,  1.82222222,  2.84444444,  3.86666667,  4.88888889,
        5.91111111,  6.93333333,  7.95555556,  8.97777778, 10.        ])

In [32]:
from collections import defaultdict
# and tansho_odds < 25 

result = defaultdict(list)
for exp in np.linspace(0,10,140):
    bet_df = df.query(f"expect_return > {exp} and pred > 0.1 and 2 < tansho_odds < 100")
    total_payoff = bet_df["payoff"].sum()
    total_bet = len(bet_df)
    return_rate = total_payoff / total_bet
    result["expect_return"].append(exp)
    result["total_bet"].append(total_bet)    
    result["total_payoff"].append(total_payoff)
    result["return_rate"].append(return_rate)
result_df = pd.DataFrame(result)
result_df.head(140)

     expect_return  total_bet  total_payoff  return_rate
0         0.000000      20417       16511.3     0.808704
1         0.071942      20417       16511.3     0.808704
2         0.143885      20417       16511.3     0.808704
3         0.215827      20417       16511.3     0.808704
4         0.287770      20335       16452.3     0.809063
5         0.359712      20008       16208.8     0.810116
6         0.431655      19354       15646.7     0.808448
7         0.503597      18348       14817.6     0.807587
8         0.575540      17028       13815.7     0.811352
9         0.647482      15652       12662.7     0.809015
10        0.719424      14216       11480.3     0.807562
11        0.791367      12774       10325.5     0.808322
12        0.863309      11463        9217.6     0.804118
13        0.935252      10242        8251.5     0.805653
14        1.007194       9060        7350.8     0.811347
15        1.079137       8107        6514.2     0.803528
16        1.151079       7315        5872.0     0.802734
17        1.223022       6553        5288.4     0.807020
18        1.294964       5941        4806.6     0.809056
19        1.366906       5433        4384.9     0.807086
20        1.438849       4933        3945.5     0.799818
21        1.510791       4497        3572.6     0.794441
22        1.582734       4093        3140.9     0.767383
23        1.654676       3750        2836.8     0.756480
24        1.726619       3448        2659.3     0.771259
25        1.798561       3195        2496.1     0.781252
26        1.870504       2949        2371.7     0.804239
27        1.942446       2741        2270.5     0.828347
28        2.014388       2558        2085.5     0.815285
29        2.086331       2373        1907.3     0.803751
30        2.158273       2200        1779.5     0.808864
31        2.230216       2062        1692.4     0.820757
32        2.302158       1927        1554.7     0.806798
33        2.374101       1777        1390.0     0.782217
34        2.446043       1676        1261.8     0.752864
35        2.517986       1582        1204.3     0.761252
36        2.589928       1495        1089.5     0.728763
37        2.661871       1398         979.8     0.700858
38        2.733813       1325         948.3     0.715698
39        2.805755       1241         811.7     0.654069
40        2.877698       1173         764.2     0.651492
41        2.949640       1115         694.2     0.622601
42        3.021583       1052         639.8     0.608175
43        3.093525        995         595.5     0.598492
44        3.165468        942         555.2     0.589384
45        3.237410        899         555.2     0.617575
46        3.309353        845         555.2     0.657041
47        3.381295        806         528.9     0.656203
48        3.453237        759         495.6     0.652964
49        3.525180        727         458.1     0.630124
50        3.597122        685         437.3     0.638394
51        3.669065        668         437.3     0.654641
52        3.741007        643         413.4     0.642924
53        3.812950        615         397.0     0.645528
54        3.884892        583         351.1     0.602230
55        3.956835        557         351.1     0.630341
56        4.028777        527         335.4     0.636433
57        4.100719        500         284.5     0.569000
58        4.172662        478         284.5     0.595188
59        4.244604        463         268.4     0.579698
60        4.316547        440         268.4     0.610000
61        4.388489        417         268.4     0.643645
62        4.460432        399         268.4     0.672682
63        4.532374        379         240.7     0.635092
64        4.604317        368         240.7     0.654076
65        4.676259        349         240.7     0.689685
66        4.748201        337         240.7     0.714243
67        4.820144        325         240.7     0.740615
68        4.892086        305         240.7     0.789180
69        4.964029        287         240.7     0.838676
70        5.035971        279         240.7     0.862724
71        5.107914        273         240.7     0.881685
72        5.179856        261         168.8     0.646743
73        5.251799        253         168.8     0.667194
74        5.323741        243         168.8     0.694650
75        5.395683        233         168.8     0.724464
76        5.467626        228         168.8     0.740351
77        5.539568        219         168.8     0.770776
78        5.611511        212         132.3     0.624057
79        5.683453        211         132.3     0.627014
80        5.755396        203         132.3     0.651724
81        5.827338        198         132.3     0.668182
82        5.899281        191         132.3     0.692670
83        5.971223        184          75.5     0.410326
84        6.043165        179          75.5     0.421788
85        6.115108        173          75.5     0.436416
86        6.187050        166          75.5     0.454819
87        6.258993        162          75.5     0.466049
88        6.330935        156          75.5     0.483974
89        6.402878        153          75.5     0.493464
90        6.474820        149          75.5     0.506711
91        6.546763        149          75.5     0.506711
92        6.618705        143          75.5     0.527972
93        6.690647        139          75.5     0.543165
94        6.762590        133          75.5     0.567669
95        6.834532        128          75.5     0.589844
96        6.906475        125          75.5     0.604000
97        6.978417        122          75.5     0.618852
98        7.050360        116          75.5     0.650862
99        7.122302        114          75.5     0.662281
100       7.194245        111          75.5     0.680180
101       7.266187        107          75.5     0.705607
102       7.338129        103          75.5     0.733010
103       7.410072        101          75.5     0.747525
104       7.482014         95          75.5     0.794737
105       7.553957         94          75.5     0.803191
106       7.625899         93          75.5     0.811828
107       7.697842         92          75.5     0.820652
108       7.769784         88          75.5     0.857955
109       7.841727         87          75.5     0.867816
110       7.913669         84          75.5     0.898810
111       7.985612         82          75.5     0.920732
112       8.057554         79          75.5     0.955696
113       8.129496         79          75.5     0.955696
114       8.201439         75          75.5     1.006667
115       8.273381         72          75.5     1.048611
116       8.345324         69          75.5     1.094203
117       8.417266         66          75.5     1.143939
118       8.489209         62          75.5     1.217742
119       8.561151         61          75.5     1.237705
120       8.633094         61          75.5     1.237705
121       8.705036         58          75.5     1.301724
122       8.776978         57          75.5     1.324561
123       8.848921         56          75.5     1.348214
124       8.920863         55          21.1     0.383636
125       8.992806         54          21.1     0.390741
126       9.064748         54          21.1     0.390741
127       9.136691         53          21.1     0.398113
128       9.208633         49          21.1     0.430612
129       9.280576         48          21.1     0.439583
130       9.352518         45          21.1     0.468889
131       9.424460         43          21.1     0.490698
132       9.496403         43          21.1     0.490698
133       9.568345         43          21.1     0.490698
134       9.640288         43          21.1     0.490698
135       9.712230         39          21.1     0.541026
136       9.784173         38          21.1     0.555263
137       9.856115         38          21.1     0.555263
138       9.928058         36          21.1     0.586111
139      10.000000         35          21.1     0.602857

In [39]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

ModuleNotFoundError: No module named 'seaborn'

In [40]:
sns.lineplot(result_df,x="expect_return",y="return_rate")

NameError: name 'sns' is not defined

In [42]:
result_df.sort_values("return_rate",ascending = False).head()

    expect_return  total_bet  total_payoff  return_rate
2        0.824242       4445        3306.5     0.743870
3        0.836364       4385        3255.4     0.742395
1        0.812121       4491        3313.9     0.737898
0        0.800000       4547        3342.0     0.734990
10       0.921212       3988        2927.5     0.734077

In [66]:
#他の三連単系にも適応させる
import math
from pathlib import Path

import pandas as pd

DATA_DIR = Path("..", "data")
PREPROCESSED_DIR = DATA_DIR / "01_preprocessed"
TRAIN_DIR = DATA_DIR / "03_train"
OUTPUT_DIR = DATA_DIR / "04_evaluation"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

return_tables_filepath = PREPROCESSED_DIR / "return_tables.pickle"
train_dir = TRAIN_DIR
evaluation_filename = "evaluation_lightgbm_rank_niti_odds_removed.csv"
output_dir = OUTPUT_DIR
return_tables = pd.read_pickle(return_tables_filepath)
evaluation_df = pd.read_csv(train_dir / evaluation_filename, sep="\t")
output_dir = output_dir
evaluation_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred
0,202306030301,2020102181,1,1,1.9,1,12,0.227220
1,202306030301,2020101572,0,2,3.1,2,6,0.308430
2,202306030301,2020102135,0,3,23.4,6,10,0.082764
3,202306030301,2020103975,0,4,6.1,3,13,0.193020
4,202306030301,2020100381,0,5,54.8,7,2,0.019120
...,...,...,...,...,...,...,...,...
35150,202309050912,2017104873,0,12,172.3,13,11,0.008107
35151,202309050912,2019100653,0,13,94.7,12,15,0.013465
35152,202309050912,2017106240,0,14,75.0,10,7,0.029081
35153,202309050912,2018103205,0,15,368.3,15,16,0.009866
35154,202309050912,2017102603,0,16,347.8,14,14,0.004825

In [86]:
"""
sort_colで指定した列でソートし、上位n件のBOX馬券の的中率・回収率を
シミュレーションする関数。
"""
bet_df = (
    evaluation_df.sort_values("pred", ascending = False)
    .groupby("race_id")
    .head(3)
    .groupby("race_id")["umaban"]    
    # 払い戻しテーブルの馬番は文字列型なので合わせる
    .apply(lambda x: list(x.astype(str)))
    .reset_index()
         )
pred_df = (
    evaluation_df.sort_values("pred", ascending = False)
    .sort_values("pred", ascending = False)
    .groupby("race_id")
    .head(3)
    .groupby("race_id")["pred"]
    .apply(lambda x: list(x))
    .reset_index()
)
pred_df

           race_id                                               pred
0     202301010101  [0.5077941893501549, 0.3208448203097965, 0.095...
1     202301010102  [0.3981832041800139, 0.2223949812396349, 0.092...
2     202301010103  [0.2373154014957641, 0.1784663199491415, 0.162...
3     202301010104  [0.1677502822473391, 0.1558535863536714, 0.124...
4     202301010105  [0.1507361826165545, 0.1198399329579728, 0.119...
...            ...                                                ...
2587  202310030808  [0.1865958325642172, 0.1520041532233221, 0.090...
2588  202310030809  [0.4517475478237358, 0.1288483883944573, 0.101...
2589  202310030810  [0.1904262978210795, 0.1258844150211567, 0.112...
2590  202310030811  [0.2223973151855648, 0.1828288977248285, 0.171...
2591  202310030812  [0.1658039725112311, 0.1232718706222467, 0.110...

[2592 rows x 2 columns]

In [90]:
df = bet_df.merge(return_tables, on="race_id")
df = df.merge(pred_df, on="race_id")
df

,race_id,umaban,bet_type,win_umaban,return,pred
0,202301010101,"[5, 8, 1]",単勝,[5],120,"[0.5077941893501549, 0.3208448203097965, 0.095..."
1,202301010101,"[5, 8, 1]",複勝,[5],100,"[0.5077941893501549, 0.3208448203097965, 0.095..."
2,202301010101,"[5, 8, 1]",複勝,[8],110,"[0.5077941893501549, 0.3208448203097965, 0.095..."
3,202301010101,"[5, 8, 1]",複勝,[6],310,"[0.5077941893501549, 0.3208448203097965, 0.095..."
4,202301010101,"[5, 8, 1]",馬連,"[5, 8]",170,"[0.5077941893501549, 0.3208448203097965, 0.095..."
...,...,...,...,...,...,...
28495,202310030812,"[11, 6, 2]",ワイド,"[6, 8]",410,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28496,202310030812,"[11, 6, 2]",ワイド,"[6, 11]",470,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28497,202310030812,"[11, 6, 2]",馬単,"[8, 11]",1580,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28498,202310030812,"[11, 6, 2]",三連複,"[6, 8, 11]",1590,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28499,202310030812,"[11, 6, 2]",三連単,"[8, 11, 6]",6860,"[0.1658039725112311, 0.1232718706222467, 0.110..."

,race_id,umaban,bet_type,win_umaban,return,pred,numeric_values
0,202301010101,"[5, 8, 1]",単勝,[5],120,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
1,202301010101,"[5, 8, 1]",複勝,[5],100,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
2,202301010101,"[5, 8, 1]",複勝,[8],110,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
3,202301010101,"[5, 8, 1]",複勝,[6],310,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
4,202301010101,"[5, 8, 1]",馬連,"[5, 8]",170,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
...,...,...,...,...,...,...,...
28495,202310030812,"[11, 6, 2]",ワイド,"[6, 8]",410,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28496,202310030812,"[11, 6, 2]",ワイド,"[6, 11]",470,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28497,202310030812,"[11, 6, 2]",馬単,"[8, 11]",1580,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28498,202310030812,"[11, 6, 2]",三連複,"[6, 8, 11]",1590,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28499,202310030812,"[11, 6, 2]",三連単,"[8, 11, 6]",6860,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."

In [ ]:
#期待値
df["expect_return"] = df["return"] * df["pred"]
df

In [94]:
#無理そうだし、期待値が1.78になるくらいの選択肢を評価するのは良さそう
#要するに手動で計算して、その値が出るように