In [44]:
import create_population_turf
import create_population_turf_newbie
import create_population_turf_nowin
import create_population_obstract
import create_population_dirt
import create_population_dirt_newbie
import create_population_dirt_nowin
import preprocessing
from feature_engineering import FeatureCreator
from feature_engineering_prediction import PredictionFeatureCreator

import prediction


import pandas as pd
import numpy as np


import condition_prediction


from train_lgbm_rank_niti_cross import Trainer_lightgbm_rank_niti_cv
from train_lightgbm_time import Trainer_lightgbm_time
from train_lgbm_time_cross import Trainer_lightgbm_time_cv
from train_lgbm_index_cross import Trainer_lightgbm_index_cv

from evaluation_lightgbm_time_kaiki import Evaluator_lightgbm_time_kaiki

from evaluation_shaft_time_kaiki_cross import Evaluator_lightgbm_time_kaiki_shaft

from evaluation_lgbm_rank_niti_cross import Evaluator_lightgbm_rank_niti_cross
from evaluation_shaft_rank_cross import Evaluator_lightgbm_rank_niti_shaft

from evaluation_lightgbm_index import Evaluator_lightgbm_index

from evaluation_shaft_index import Evaluator_lightgbm_index_shaft


%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [45]:
%autoreload

In [60]:
df = pd.read_csv("../data/03_train/evaluation_lightgbm_rank_niti_cv_dev_turf.csv",sep="\t")
df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary
0,201709040710,2012104823,0,8,49.9,10,5,0.016370,0
1,201709040710,2012104772,0,7,28.9,7,6,0.029154,0
2,201709040710,2009103405,0,6,36.5,8,2,0.042665,0
3,201709040710,2012100740,0,5,37.9,9,9,0.024153,0
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1
...,...,...,...,...,...,...,...,...,...
89164,202406050112,2020106384,0,11,153.9,14,10,0.011299,0
89165,202406050112,2020103366,0,10,47.6,10,9,0.015416,0
89166,202406050112,2019101270,0,9,19.8,7,7,0.013935,0
89167,202406050112,2021100356,0,8,27.3,8,15,0.060320,0
89168,202406050112,2021104006,0,7,12.0,6,2,0.032104,0

In [61]:
#期待値
df["expect_return"] = df["tansho_odds"] * df["pred"]
df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary,expect_return
0,201709040710,2012104823,0,8,49.9,10,5,0.016370,0,0.816877
1,201709040710,2012104772,0,7,28.9,7,6,0.029154,0,0.842562
2,201709040710,2009103405,0,6,36.5,8,2,0.042665,0,1.557255
3,201709040710,2012100740,0,5,37.9,9,9,0.024153,0,0.915417
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1,1.168142
...,...,...,...,...,...,...,...,...,...,...
89164,202406050112,2020106384,0,11,153.9,14,10,0.011299,0,1.738899
89165,202406050112,2020103366,0,10,47.6,10,9,0.015416,0,0.733821
89166,202406050112,2019101270,0,9,19.8,7,7,0.013935,0,0.275920
89167,202406050112,2021100356,0,8,27.3,8,15,0.060320,0,1.646738
89168,202406050112,2021104006,0,7,12.0,6,2,0.032104,0,0.385246

In [62]:
bet_df = df.query("expect_return > 1.0 and pred > 0.08")
bet_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary,expect_return
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1,1.168142
41,201706040711,2012104678,0,10,13.5,7,4,0.142301,1,1.921062
55,201706040711,2012104008,0,3,5.4,3,9,0.242821,1,1.311235
58,201709040807,2013104488,0,12,15.7,8,12,0.125473,1,1.969930
60,201709040810,2012103929,0,3,20.1,8,5,0.108937,1,2.189640
...,...,...,...,...,...,...,...,...,...,...
89143,202407040110,2021100935,0,5,10.2,6,3,0.141294,1,1.441199
89145,202407040110,2021105926,0,3,4.7,2,4,0.277356,1,1.303575
89146,202407040110,2020103241,0,2,5.7,4,6,0.275453,1,1.570082
89147,202407040108,2021106118,0,15,13.2,6,3,0.165345,1,2.182559
89154,202407040108,2021104918,0,8,23.9,8,10,0.139651,1,3.337669

In [63]:
#単勝オッズ（払い戻し）xターゲットは当たったか当たってないか、単勝
#的中率は調べてない、賭け方が1以上の場合にかけているから関係ない
bet_df = bet_df.copy()
bet_df.loc[:, "payoff"] = bet_df["target"] * bet_df["tansho_odds"]

bet_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred,pred_binary,expect_return,payoff
4,201709040710,2013104956,0,3,7.7,4,10,0.151707,1,1.168142,0.0
41,201706040711,2012104678,0,10,13.5,7,4,0.142301,1,1.921062,0.0
55,201706040711,2012104008,0,3,5.4,3,9,0.242821,1,1.311235,0.0
58,201709040807,2013104488,0,12,15.7,8,12,0.125473,1,1.969930,0.0
60,201709040810,2012103929,0,3,20.1,8,5,0.108937,1,2.189640,0.0
...,...,...,...,...,...,...,...,...,...,...,...
89143,202407040110,2021100935,0,5,10.2,6,3,0.141294,1,1.441199,0.0
89145,202407040110,2021105926,0,3,4.7,2,4,0.277356,1,1.303575,0.0
89146,202407040110,2020103241,0,2,5.7,4,6,0.275453,1,1.570082,0.0
89147,202407040108,2021106118,0,15,13.2,6,3,0.165345,1,2.182559,0.0
89154,202407040108,2021104918,0,8,23.9,8,10,0.139651,1,3.337669,0.0

In [64]:
#払い戻しの合計
total_payoff = bet_df["payoff"].sum()
total_payoff

np.float64(9967.9)

In [65]:
#払い戻し、馬券購入回数、回収率
total_bet = len(bet_df)
return_rate = total_payoff / total_bet
total_payoff,total_bet,return_rate

(np.float64(9967.9), 12027, np.float64(0.8287935478506693))

In [66]:
#期待値がどれくらい上になるかを検証
np.linspace(0.8,10,10)

array([ 0.8       ,  1.82222222,  2.84444444,  3.86666667,  4.88888889,
        5.91111111,  6.93333333,  7.95555556,  8.97777778, 10.        ])

In [67]:
df["payoff"] = df["target"] * df["tansho_odds"]

In [68]:
from collections import defaultdict

result = defaultdict(list)
for exp in np.linspace(0.8,2,100):
    bet_df = df.query(f"expect_return > {exp}")
    total_payoff = bet_df["payoff"].sum()
    total_bet = len(bet_df)
    return_rate = total_payoff / total_bet
    result["expect_return"].append(exp)
    result["total_bet"].append(total_bet)    
    result["total_payoff"].append(total_payoff)
    result["return_rate"].append(return_rate)
result_df = pd.DataFrame(result)
result_df.head(100)

    expect_return  total_bet  total_payoff  return_rate
0        0.800000      52054       38854.8     0.746433
1        0.812121      51350       38210.0     0.744109
2        0.824242      50622       37568.9     0.742146
3        0.836364      49853       37179.6     0.745785
4        0.848485      49149       36640.1     0.745490
5        0.860606      48465       36009.8     0.743006
6        0.872727      47754       35510.4     0.743611
7        0.884848      47086       35068.3     0.744771
8        0.896970      46408       34497.5     0.743352
9        0.909091      45790       34107.8     0.744874
10       0.921212      45173       33646.3     0.744832
11       0.933333      44512       33217.0     0.746248
12       0.945455      43857       32734.7     0.746396
13       0.957576      43228       32281.0     0.746761
14       0.969697      42663       31873.1     0.747090
15       0.981818      42082       31479.1     0.748042
16       0.993939      41494       30946.4     0.745804
17       1.006061      40921       30514.6     0.745695
18       1.018182      40371       29902.7     0.740698
19       1.030303      39816       29409.3     0.738630
20       1.042424      39264       29117.6     0.741585
21       1.054545      38706       28736.2     0.742422
22       1.066667      38192       28351.8     0.742349
23       1.078788      37666       28095.5     0.745911
24       1.090909      37133       27534.9     0.741521
25       1.103030      36617       27156.3     0.741631
26       1.115152      36119       26915.2     0.745181
27       1.127273      35595       26351.2     0.740306
28       1.139394      35096       26058.7     0.742498
29       1.151515      34637       25711.3     0.742307
30       1.163636      34177       24933.8     0.729549
31       1.175758      33709       24737.3     0.733849
32       1.187879      33257       24350.9     0.732204
33       1.200000      32802       24117.5     0.735245
34       1.212121      32388       23708.7     0.732021
35       1.224242      31977       23326.7     0.729484
36       1.236364      31529       23079.9     0.732021
37       1.248485      31125       22815.4     0.733025
38       1.260606      30726       22356.9     0.727622
39       1.272727      30307       21884.2     0.722084
40       1.284848      29886       21649.4     0.724399
41       1.296970      29522       21471.4     0.727302
42       1.309091      29105       21192.3     0.728133
43       1.321212      28719       20841.7     0.725711
44       1.333333      28343       20643.3     0.728339
45       1.345455      27962       20326.3     0.726926
46       1.357576      27584       20000.2     0.725065
47       1.369697      27245       19820.4     0.727488
48       1.381818      26851       19485.4     0.725686
49       1.393939      26514       19318.2     0.728604
50       1.406061      26158       19118.3     0.730878
51       1.418182      25826       18985.8     0.735143
52       1.430303      25519       18824.5     0.737666
53       1.442424      25191       18695.1     0.742134
54       1.454545      24853       18404.9     0.740550
55       1.466667      24540       18084.4     0.736936
56       1.478788      24225       17858.4     0.737189
57       1.490909      23963       17800.2     0.742820
58       1.503030      23613       17473.3     0.739986
59       1.515152      23312       17352.8     0.744372
60       1.527273      23009       17115.7     0.743870
61       1.539394      22719       17058.8     0.750861
62       1.551515      22386       16933.7     0.756442
63       1.563636      22090       16739.4     0.757782
64       1.575758      21799       16575.1     0.760361
65       1.587879      21527       16318.2     0.758034
66       1.600000      21261       16088.8     0.756728
67       1.612121      20971       15973.2     0.761680
68       1.624242      20712       15729.2     0.759424
69       1.636364      20473       15511.6     0.757661
70       1.648485      20208       15288.6     0.756562
71       1.660606      19966       15168.8     0.759732
72       1.672727      19727       15137.5     0.767349
73       1.684848      19501       14962.2     0.767253
74       1.696970      19261       14754.5     0.766030
75       1.709091      19019       14416.7     0.758016
76       1.721212      18795       14221.2     0.756648
77       1.733333      18574       14153.8     0.762022
78       1.745455      18375       14023.1     0.763162
79       1.757576      18155       13654.1     0.752085
80       1.769697      17960       13317.2     0.741492
81       1.781818      17750       13202.8     0.743820
82       1.793939      17536       13150.5     0.749914
83       1.806061      17335       12924.8     0.745590
84       1.818182      17122       12791.4     0.747074
85       1.830303      16907       12583.4     0.744272
86       1.842424      16724       12554.0     0.750658
87       1.854545      16524       12372.0     0.748729
88       1.866667      16347       12296.0     0.752187
89       1.878788      16138       12086.0     0.748916
90       1.890909      15950       11947.9     0.749085
91       1.903030      15760       11615.9     0.737049
92       1.915152      15581       11560.2     0.741942
93       1.927273      15405       11413.9     0.740922
94       1.939394      15208       11339.5     0.745627
95       1.951515      15011       11310.4     0.753474
96       1.963636      14821       11249.0     0.758991
97       1.975758      14667       11063.8     0.754333
98       1.987879      14490       10968.9     0.756998
99       2.000000      14313       10779.6     0.753134

In [ ]:
from collections import defaultdict

result = defaultdict(list)
for exp in np.linspace(0.8,10,100):
    bet_df = df.query(f"expect_return > {exp}")
    total_payoff = bet_df["payoff"].sum()
    total_bet = len(bet_df)
    return_rate = total_payoff / total_bet
    result["expect_return"].append(exp)
    result["total_bet"].append(total_bet)    
    result["total_payoff"].append(total_payoff)
    result["return_rate"].append(return_rate)
result_df = pd.DataFrame(result)
result_df.head(100)

In [39]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

ModuleNotFoundError: No module named 'seaborn'

In [40]:
sns.lineplot(result_df,x="expect_return",y="return_rate")

NameError: name 'sns' is not defined

In [42]:
result_df.sort_values("return_rate",ascending = False).head()

    expect_return  total_bet  total_payoff  return_rate
2        0.824242       4445        3306.5     0.743870
3        0.836364       4385        3255.4     0.742395
1        0.812121       4491        3313.9     0.737898
0        0.800000       4547        3342.0     0.734990
10       0.921212       3988        2927.5     0.734077

In [66]:
#他の三連単系にも適応させる
import math
from pathlib import Path

import pandas as pd

DATA_DIR = Path("..", "data")
PREPROCESSED_DIR = DATA_DIR / "01_preprocessed"
TRAIN_DIR = DATA_DIR / "03_train"
OUTPUT_DIR = DATA_DIR / "04_evaluation"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

return_tables_filepath = PREPROCESSED_DIR / "return_tables.pickle"
train_dir = TRAIN_DIR
evaluation_filename = "evaluation_lightgbm_rank_niti_odds_removed.csv"
output_dir = OUTPUT_DIR
return_tables = pd.read_pickle(return_tables_filepath)
evaluation_df = pd.read_csv(train_dir / evaluation_filename, sep="\t")
output_dir = output_dir
evaluation_df

,race_id,horse_id,target,rank,tansho_odds,popularity,umaban,pred
0,202306030301,2020102181,1,1,1.9,1,12,0.227220
1,202306030301,2020101572,0,2,3.1,2,6,0.308430
2,202306030301,2020102135,0,3,23.4,6,10,0.082764
3,202306030301,2020103975,0,4,6.1,3,13,0.193020
4,202306030301,2020100381,0,5,54.8,7,2,0.019120
...,...,...,...,...,...,...,...,...
35150,202309050912,2017104873,0,12,172.3,13,11,0.008107
35151,202309050912,2019100653,0,13,94.7,12,15,0.013465
35152,202309050912,2017106240,0,14,75.0,10,7,0.029081
35153,202309050912,2018103205,0,15,368.3,15,16,0.009866
35154,202309050912,2017102603,0,16,347.8,14,14,0.004825

In [86]:
"""
sort_colで指定した列でソートし、上位n件のBOX馬券の的中率・回収率を
シミュレーションする関数。
"""
bet_df = (
    evaluation_df.sort_values("pred", ascending = False)
    .groupby("race_id")
    .head(3)
    .groupby("race_id")["umaban"]    
    # 払い戻しテーブルの馬番は文字列型なので合わせる
    .apply(lambda x: list(x.astype(str)))
    .reset_index()
         )
pred_df = (
    evaluation_df.sort_values("pred", ascending = False)
    .sort_values("pred", ascending = False)
    .groupby("race_id")
    .head(3)
    .groupby("race_id")["pred"]
    .apply(lambda x: list(x))
    .reset_index()
)
pred_df

           race_id                                               pred
0     202301010101  [0.5077941893501549, 0.3208448203097965, 0.095...
1     202301010102  [0.3981832041800139, 0.2223949812396349, 0.092...
2     202301010103  [0.2373154014957641, 0.1784663199491415, 0.162...
3     202301010104  [0.1677502822473391, 0.1558535863536714, 0.124...
4     202301010105  [0.1507361826165545, 0.1198399329579728, 0.119...
...            ...                                                ...
2587  202310030808  [0.1865958325642172, 0.1520041532233221, 0.090...
2588  202310030809  [0.4517475478237358, 0.1288483883944573, 0.101...
2589  202310030810  [0.1904262978210795, 0.1258844150211567, 0.112...
2590  202310030811  [0.2223973151855648, 0.1828288977248285, 0.171...
2591  202310030812  [0.1658039725112311, 0.1232718706222467, 0.110...

[2592 rows x 2 columns]

In [90]:
df = bet_df.merge(return_tables, on="race_id")
df = df.merge(pred_df, on="race_id")
df

,race_id,umaban,bet_type,win_umaban,return,pred
0,202301010101,"[5, 8, 1]",単勝,[5],120,"[0.5077941893501549, 0.3208448203097965, 0.095..."
1,202301010101,"[5, 8, 1]",複勝,[5],100,"[0.5077941893501549, 0.3208448203097965, 0.095..."
2,202301010101,"[5, 8, 1]",複勝,[8],110,"[0.5077941893501549, 0.3208448203097965, 0.095..."
3,202301010101,"[5, 8, 1]",複勝,[6],310,"[0.5077941893501549, 0.3208448203097965, 0.095..."
4,202301010101,"[5, 8, 1]",馬連,"[5, 8]",170,"[0.5077941893501549, 0.3208448203097965, 0.095..."
...,...,...,...,...,...,...
28495,202310030812,"[11, 6, 2]",ワイド,"[6, 8]",410,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28496,202310030812,"[11, 6, 2]",ワイド,"[6, 11]",470,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28497,202310030812,"[11, 6, 2]",馬単,"[8, 11]",1580,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28498,202310030812,"[11, 6, 2]",三連複,"[6, 8, 11]",1590,"[0.1658039725112311, 0.1232718706222467, 0.110..."
28499,202310030812,"[11, 6, 2]",三連単,"[8, 11, 6]",6860,"[0.1658039725112311, 0.1232718706222467, 0.110..."

,race_id,umaban,bet_type,win_umaban,return,pred,numeric_values
0,202301010101,"[5, 8, 1]",単勝,[5],120,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
1,202301010101,"[5, 8, 1]",複勝,[5],100,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
2,202301010101,"[5, 8, 1]",複勝,[8],110,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
3,202301010101,"[5, 8, 1]",複勝,[6],310,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
4,202301010101,"[5, 8, 1]",馬連,"[5, 8]",170,"[0.5077941893501549, 0.3208448203097965, 0.095...","[0.5077941893501549, 0.3208448203097965, 0.095..."
...,...,...,...,...,...,...,...
28495,202310030812,"[11, 6, 2]",ワイド,"[6, 8]",410,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28496,202310030812,"[11, 6, 2]",ワイド,"[6, 11]",470,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28497,202310030812,"[11, 6, 2]",馬単,"[8, 11]",1580,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28498,202310030812,"[11, 6, 2]",三連複,"[6, 8, 11]",1590,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."
28499,202310030812,"[11, 6, 2]",三連単,"[8, 11, 6]",6860,"[0.1658039725112311, 0.1232718706222467, 0.110...","[0.1658039725112311, 0.1232718706222467, 0.110..."

In [ ]:
#期待値
df["expect_return"] = df["return"] * df["pred"]
df

In [94]:
#無理そうだし、期待値が1.78になるくらいの選択肢を評価するのは良さそう
#要するに手動で計算して、その値が出るように